"""Sketch 102 — the overlay census. ONE source of truth for index.html, README.md's
table, the page-doc subsections and the published artifact. Edit here, run build.py.

Body rows:  ["sect", label] · ["item", label, sub, on?, kbd?] · ["fact", k, v, em?]
            ["field", label, value, placeholder?] · ["two", [label,value,ph?], [label,value,ph?]]
            ["note", text] · ["quiet", text] · ["hold", text] · ["btns", [label, pri?], ...]
            ["chips", [label, on], ...] · ["table", [cols], [rows...]] · ["alert", head, text]
            ["text", paragraph] · ["mono", text] · ["frame", caption]
Statuses:   built · migrate · owed · target · retire · delete · none
Every name, figure and date below is EXAMPLE DATA, not a tenant."""

META = dict(sketch=102, name="modal-census", date="2026-09-05",
            tree="feat/mudavym-design-p4 @ origin tip, read 2026-09-05",
            primitive="apps/web/src/components/mudavym/Sheet.tsx (Sheet · Panel · Popover)")

def O(name, status, shape=None, **k):
    d = dict(name=name, status=status, shape=shape, wide=False, modal=False, seal=False,
             eyebrow=None, title=None, action=None, close="Close", body=[], footer=None,
             why=None, source=None, acts=None, went=None, fork=None)
    d.update(k); return d

PAGES = []
def P(route, slug, doc, verdict, overlays, rebuilt=True, flag=None, alias=None):
    PAGES.append(dict(route=route, slug=slug, doc=doc, verdict=verdict, overlays=overlays,
                      rebuilt=rebuilt, flag=flag, alias=alias or []))

# ─────────────────────────────────────────── the shell ──
P("shell", "shell", None,
  "Nine overlays render over every page. Eight wear the house shape while a rebuilt page is on "
  "screen and their legacy markup otherwise (lib/mudavym/shellGround.ts). Two of them now exist twice.",
  rebuilt=True, overlays=[
  O("Command palette", "built", "panel", title="Command palette",
    source="components/command/CommandPalette.tsx:260",
    body=[["field","","Search pages, actions, insights…",True],
          ["sect","Pages"],["item","Orders","/orders",True,"↵"],["item","Inventory","/inventory"],
          ["sect","Actions"],["item","Approve what is waiting","3 orders on the ledger"],["item","Write a letter","/communications"],
          ["sect","Insights"],["item","Öküzgözü sold 41% above its 30-day pace","reports · 2 Sept"]],
    footer="↑↓ to navigate · ↵ to run · esc closes",
    why="A question the reader answers by typing: the middle of the screen, the page dimmed, focus trapped."),
  O("Ask AI", "built", "panel", title="Ask AI",
    source="components/askai/AskAiBar.tsx:166",
    body=[["field","","Ask for an action — reorder stock, draft a vendor reply…",True],
          ["note","<b>Ask AI proposes; you confirm.</b> Nothing runs until you do."],
          ["quiet","Drafts only — nothing reaches a vendor without a second approval."]],
    footer="esc closes", why="A question; the answer is a proposal the person still has to hold."),
  O("Keyboard shortcuts", "built", "panel", eyebrow="The house", title="Keyboard shortcuts",
    source="components/command/ShortcutsSheet.tsx:67",
    body=[["item","Open the palette","",False,"⌘ K"],["item","Ask AI","",False,"⌘ J"],["item","Recently viewed","",False,"⌘ E"],
          ["quiet","Page-specific shortcuts appear in each page's toolbar."]],
    why="A reference the reader consults and dismisses — a panel, never a sheet: there is no object."),
  O("Recently viewed", "built", "panel", eyebrow="Where you have been", title="Recently viewed",
    source="components/command/RecentlyViewed.tsx:69",
    body=[["item","Orders","2 minutes ago"],["item","Reports","14 minutes ago"],["item","Team","yesterday"],
          ["quiet","No recent pages yet — they collect as you navigate."]],
    why="A list to jump from."),
  O("The bell", "built", "popover", eyebrow="3 folded lines", title="Notifications",
    source="components/mudavym/HouseBell.tsx:127 survives; components/layout/Header.tsx:147 (the shell header's house branch) is deleted — decided 2026-09-05 (F6); its legacy branch stays byte-identical",
    body=[["item","Kavaklıdere confirmed order 118","12 min ago · a reply on the thread"],
          ["item","Öküzgözü 2022 is below par","2 left · 6 is par"],
          ["item","Week 37 is published","yesterday · 5 have opened it"]],
    footer="Rule all off · Read the whole book",
    why="A control's own menu. It never carries the seal (founder, 2026-09-04) — approving from here opens the panel first."),
  O("User menu", "built", "popover", eyebrow="ayse@example.com", title="Ayşe Yılmaz",
    source="components/mudavym/HouseUserMenu.tsx:79 survives; components/layout/Header.tsx:351 is deleted — decided 2026-09-05 (F6)",
    body=[["item","Profile"],["item","Settings"],["item","Help & Support"],["item","Log out"]],
    why="A control's own menu."),
  O("Theme", "built", "popover", title="Theme", source="components/layout/ThemeMenu.tsx:65",
    body=[["item","Paper","",True],["item","Charcoal"],["item","Follow the system"]],
    why="Dimming the whole page to pick 'Dark' is ceremony; this house rations ceremony."),
  O("Switch location", "built", "popover", eyebrow="3 locations", title="Switch location",
    source="components/layout/RestaurantBranchSwitcher.tsx:80",
    body=[["item","Meyhane Sim · Kaleiçi","Active",True],["item","Meyhane Sim · Lara","live sync"],["item","The Grill Co."]],
    footer="Add location · Manage locations", why="A choice from a short list, hanging off the control that shows the choice."),
  O("Mobile navigation scrim", "none", None, source="components/layout/DashboardLayout.tsx:60",
    acts="Dims the page behind the drawer on small screens", went="Paint only (`.mdv-scrim`) — not a shape, and it never was one."),
  O("Nav-rail hint", "none", None, source="components/layout/Sidebar.tsx:255",
    acts="The label that appears when the collapsed rail is hovered", went="An anchored, non-interactive label, portalled only so it can wear the ground. Not a shape."),
  O("Header search", "retire", None, source="components/layout/Header.tsx:464",
    acts="'Search wines, orders, reports…' — a second search box in the header", went="The palette is the search."),
])

# ─────────────────────────────────────────── dashboard ──
P("/", "dashboard", "dashboard.md",
  "Four legacy modals, none of which survives as an overlay: three retire into surfaces the rebuilt page already has, and the figure detail becomes an in-place expansion under the KPI row (decided 2026-09-05, F7 — still to build).",
  flag="mudavym_design_dashboard", overlays=[
  O("The working behind a figure", "retire", None, fork="F7",
    source="pages/Dashboard.tsx:1109 — the Vendor Spend · Active Inventory · Pending Orders · Low Stock detail modals; nothing on pages/dashboard/next/KpiRow.tsx opens today",
    acts="What one dashboard figure is made of: the orders, vendors and rows it summed",
    went="Decided 2026-09-05 (F7): the KPI row expands in place — 'show the working' under the figure, like DayDetail under the sales calendar. Not an overlay; the expansion is still owed on KpiRow.tsx."),
  O("A one-tap action of your own", "owed", "sheet", eyebrow="The rail", title="A one-tap action of your own", fork="F4",
    source="components/dashboard/QuickActionsPanel.tsx:332 and pages/Notifications.tsx:1705 (legacy); built by the founder's ruling 2026-09-05",
    body=[["field","What it does","Reorder Öküzgözü to par"],["sect","Runs"],
          ["chips",["When I tap it",True],["On a threshold",False],["On a schedule",False]],
          ["fact","Threshold","2 bottles left · 6 is par"],["fact","Then","a draft order to Kavaklıdere — you hold to send"],
          ["note","One tap runs the act; the seal still sits on any write it makes (ADR 0112, ADR 0125)."],["btns",["Put it on the rail",True]]],
    footer="An action names what it will do before it does it.",
    why="A person's own act is one object on the rail; the rail stays producer-defined otherwise."),
  O("Add an important date", "retire", None, source="components/dashboard/AddImportantDateModal.tsx:125",
    acts="Add events, deadlines and reminders: title, date, time, type, colour, notes",
    went="The calendar's entry sheet — the house has one day-book (ADR 0111)."),
  O("Edit a quick action", "retire", None, source="components/dashboard/QuickActionsPanel.tsx:332", fork="F4",
    acts="A person-authored quick action: title, description, URL, icon, colour theme",
    went="One-tap actions moved to the dashboard rail (OneTapPanel). A person's own action is built as the sheet drawn above (decided 2026-09-05, F4)."),
  O("Daily sales report (a day)", "retire", None, source="pages/Dashboard.tsx:1414",
    acts="Everything that happened on one day: spend, bottles sold, top seller, events",
    went="DayDetail expands in place under the sales calendar (pages/dashboard/next/SalesCalendar.tsx:217)."),
])

# ─────────────────────────────────────────── orders ──
P("/orders", "orders", "orders.md",
  "Three house overlays are built. The manual 'new order' sheet and its guard are owed — the founder chose the sheet as the manual entry (F5, 2026-09-05); six legacy modals retire into what is built; two dead files are deleted.",
  flag="mudavym_design_orders", overlays=[
  O("What was agreed", "built", "panel", eyebrow="New agreement", title="What was agreed",
    source="pages/orders/next/AgreementSheet.tsx:349",
    body=[["two",["Wine","Öküzgözü 2022 · Kavaklıdere"],["Vendor","Kavaklıdere"]],
          ["two",["Quantity","5"],["Order unit","case · 12 bottles"]],
          ["two",["Agreed price","₺ 2,400.00"],["Price unit","per case"]],
          ["field","Currency","TRY"],
          ["note","An agreed price states its unit (ADR 0119). <b>unit not stated</b> is written down as exactly that."],
          ["btns",["Write it down",True]]],
    why="A question the house asks before it writes a price."),
  O("Make this order repeat", "built", "panel", eyebrow="New recurrence", title="Make this order repeat",
    source="pages/orders/next/RecurrenceSheet.tsx:222",
    body=[["field","How often","Every month"],["field","On which day","the 1st — 1 to 28, so that every month has one"],
          ["field","Starting from","1 Oct 2026"],["fact","What this will ask for","5 cases Öküzgözü 2022 · ₺ 2,400 per case"],
          ["btns",["Set a recurring order",True],["Pause it"],["End it"]]],
    why="A commitment about the future — a question, answered once."),
  O("Vendor answers", "built", "sheet", wide=True, eyebrow="Vendor answers", title="Öküzgözü 2022", action="Previous · Next",
    source="pages/orders/next/ResponsesSheet.tsx:353",
    body=[["sect","Answer 2 of 3 · Kavaklıdere · 3 Sept"],
          ["text","We can deliver Thursday. The 2022 is ₺2,400 per case and we can hold that until the 15th. — Hasan"],
          ["fact","Read as","a confirmation · price unchanged"],
          ["sect","Why this order is rejected"],["field","","In words: what is wrong with this answer",True],
          ["hold","Hold to reject"]],
    footer="Left and right arrows step through the answers.",
    why="One order's correspondence is one object, read at 640 because letters are prose — the wide case ADR 0112 anticipated."),
  O("A new order", "owed", "sheet", eyebrow="The order book", title="A new order", fork="F5",
    source="pages/orders/CreateOrderModal.tsx:123 and pages/Orders.tsx:2903 (wine config); OrdersNext has only DraftRail (AI drafts) — no manual create path was found",
    body=[["field","","Search the register — Öküzgözü, Banfi, gin…",True],["sect","Lines"],
          ["item","Öküzgözü 2022 · Kavaklıdere","5 cases · ₺ 2,400 per case",False,"₺ 12,000"],
          ["item","Chianti Classico 2021 · Banfi","2 cases · $ 210 per case",False,"$ 420"],
          ["fact","Vendor","Kavaklıdere"],
          ["note","Price and unit come from the agreement on the vendor's row; a line without one asks first (<b>What was agreed</b>)."]],
    footer="Nothing is sent by saving a draft.",
    why="The order being written is one object. Decided 2026-09-05 (F5): this sheet is the manual entry; owed on OrdersNext."),
  O("Add a vendor first", "owed", "panel", eyebrow="Before an order", title="Add a vendor to place orders",
    source="components/orders/OrderGuardModal.tsx:27",
    body=[["quiet","An order needs someone to send it to. There is no vendor in the book yet."],
          ["btns",["Go to Providers",True],["Back to the order"]]],
    why="A question with two answers. Travels with the new-order sheet."),
  O("Wine config", "retire", None, source="pages/Orders.tsx:2903",
    acts="Order unit (bottles/cases), bottles per case, custom price vs 'ask provider', providers to contact",
    went="What was agreed (unit · price · currency) on the ledger row."),
  O("Reject this order?", "retire", None, source="pages/Orders.tsx:3359 (SealedRejectDie)",
    acts="A confirmation naming the wine before a rejection", went="Vendor answers — 'Hold to reject', with the reason in words."),
  O("Provider comms thread", "retire", None, source="components/orders/CommsThreadDrawer.tsx:436", fork="F4",
    acts="One order's thread: DKIM state, Resume/Pause AI, a manual reply in the same email thread",
    went="Vendor answers reads the thread; the composer writes. <b>Pause / resume the AI on this thread</b> becomes a control in the responses sheet's head (decided 2026-09-05, F4) — a switch, not an overlay."),
  O("AI-detected deal", "retire", None, source="components/orders/DealApprovalModal.tsx:45",
    acts="A deal read from a vendor's mail: quantity, total, terms, a low-confidence warning; Decline / Ask for more",
    went="An answer kind inside Vendor answers; 'what the AI read' survives as the provenance line."),
  O("Active drafts", "retire", None, source="components/orders/ActiveConversationsPanel.tsx:65",
    acts="The AI's pending drafts: view, quick approve, discard", went="/communications lists threads with their drafts; approval is the panel drawn there."),
  O("AI draft ready", "retire", None, source="components/orders/DraftEmailApprovalPanel.tsx:130",
    acts="Review, edit and send the reply the house drafted", went="Drawn on /communications as <b>The house's reply, drafted</b> (owed)."),
  O("Recurring order (page)", "delete", None, source="pages/RecurringOrders.tsx:530 — nobody imports the page",
    acts="Automated reordering with a negotiated price, deal duration and manager override",
    went="Recurrence lives on the order (Make this order repeat). Delete."),
  O("Record an auction purchase", "retire", None, source="components/orders/AuctionPurchaseModal.tsx:133 — nobody imports it", fork="F4",
    acts="Hammer price, buyer's premium, lot number, into inventory", went="Built as a fourth start of <b>Carry this bottle</b> on /inventory — 'An auction lot' (decided 2026-09-05, F4). The dead file is deleted once that start exists."),
])

# ─────────────────────────────────────────── receiving · door · receipts · documents ──
P("/receiving · /receiving/:orderId/door", "receiving", "receiving.md",
  "No overlays. The door is six points on one page; a sealed step is a panel-shaped section inside the page, not a portal (DoorNext.tsx:697 declares a local Panel).",
  flag="mudavym_design_receiving · mudavym_design_receiving_door", overlays=[])
P("/receipts", "receipts", "receipts.md",
  "No overlays. Editable-and-confirmable in one step wants no dialog; SwipeToConfirm is inline.",
  flag="mudavym_design_receipts", overlays=[])
P("/documents/:id", "document", "documents-reports.md",
  "No overlays. CanonicalSheet is a page section, not a portal.", flag="mudavym_design_document", overlays=[])

# ─────────────────────────────────────────── inventory ──
P("/inventory", "inventory", "inventory.md",
  "The one page whose flag turns on nothing new: legacy and next are the same component (App.tsx:311), so its eight fixed-inset modals are live inside a house-flagged page today. Seven migrate; one retires to /receipts.",
  flag="mudavym_design_inventory", overlays=[
  O("Carry this bottle", "migrate", "sheet", eyebrow="The register", title="Carry this bottle",
    source="components/inventory/AddWineToInventoryModal.tsx:253 (opened at InventoryCommandPage.tsx:1438)",
    body=[["sect","Start from"],["item","The library","search the 4,120 bottles the house knows",True],
          ["item","A label photo","the reader names it; you confirm"],["item","A menu scan","many at once"],
          ["field","","Search the library — Öküzgözü, Banfi, Talisker…",True],
          ["two",["Initial quantity","12 bottles"],["Cost per bottle","₺ 190.00"]],
          ["two",["Vendor","Kavaklıdere"],["Zone","Cellar · rack B"]],
          ["btns",["Carry it",True]]],
    footer="A house item exists only through 'carry this' (ADR 0115). One component, shared with /cellar.",
    why="One bottle entering the book is one object; three ways to start, one sheet."),
  O("Carry this bottle · an auction lot", "owed", "sheet", eyebrow="The register", title="Carry this bottle", fork="F4",
    source="components/orders/AuctionPurchaseModal.tsx:133 (legacy, unreachable); built by the founder's ruling 2026-09-05 as a start of the carry sheet",
    body=[["sect","Start from"],["item","The library","",False],["item","A label photo",""],["item","A menu scan",""],["item","An auction lot","hammer price and premium make the cost",True],
          ["two",["Auction house","Sotheby's"],["Lot","118"]],["two",["Hammer price","$ 1,900"],["Buyer's premium","25% · $ 475"]],
          ["fact","Cost per bottle","$ 395.83 · 6 bottles · written to the lot"],["two",["Auction date","28 Aug 2026"],["Zone","Cellar · rack A"]],
          ["btns",["Carry it",True]]],
    footer="A lot's cost is the hammer plus the premium; the ledger keeps both (ADR 0070).",
    why="The same sheet, a fourth start: an auction bottle is still one bottle entering the book."),
  O("Place 14 bottles by their zones?", "migrate", "panel", eyebrow="Auto-locate · preview", title="Place 14 bottles by their zones?",
    source="components/inventory/AutoLocatePreviewModal.tsx:70",
    body=[["table",["Bottle","Proposed zone","Score","Why"],
           [["Öküzgözü 2022","Cellar · rack B","0.92","same producer shelved here"],
            ["Talisker 10","Bar · back shelf","0.81","spirits zone, room left"],
            ["Efes Pilsen","Walk-in · door","0.77","beer, kept cold"]]],
          ["fact","Skipped","3 · no zone matched"],["chips",["Include bottles already placed",False]],
          ["btns",["Place them",True],["Leave them"]]],
    why="A question about a batch. Bulk, so no wax — the plain die."),
  O("A delivery without an order", "migrate", "sheet", wide=True, eyebrow="Receiving", title="A delivery without an order", fork="F3",
    source="components/inventory/ManualReceiptWorkspace.tsx:234",
    body=[["two",["Vendor","Sevilen"],["Invoice or reference","INV-4471"]],["field","Default zone for new lines","Cellar · rack C"],
          ["field","","Search the library to add a line…",True],["sect","Lines"],
          ["item","Sevilen Kalecik Karası 2021","6 bottles · ₺ 240.00",False,"₺ 1,440"],
          ["item","Free sample · Sevilen Blanc de Noir","2 bottles · ₺ 0.00 (sample)",False,"₺ 0"],
          ["quiet","Stock that arrived without a purchase order — including free samples."],["btns",["Record the delivery",True]]],
    why="Lines read as a table; 640 like the composer. Decided 2026-09-05 (F3): a sheet here, not a route."),
  O("POS buttons and stock", "migrate", "sheet", eyebrow="The queue", title="POS buttons and stock",
    source="components/inventory/PosMappingPanel.tsx:294",
    body=[["quiet","12 POS lines have arrived and moved no stock. 41 units unaccounted for across 4 buttons — a floor, not the total."],
          ["sect","Öküzgözü glass · 27 sales"],["btns",["One glass",True],["One bottle"],["Not this"]],
          ["sect","Efes 50cl · 9 sales"],["btns",["One bottle",True],["Not this"]]],
    footer="No inventory row matched 'Rakı Yeni' — carry the bottle first.",
    why="One queue, worked line by line, the register still visible beneath."),
  O("Write off 6 bottles?", "migrate", "panel", seal=True, eyebrow="Öküzgözü 2022 · Kavaklıdere", title="Write off 6 bottles?",
    source="components/inventory/RemoveFromInventoryModal.tsx:121",
    body=[["fact","On-hand value","₺ 1,140.00 leaves the book"],["field","Reason","Broken in transit — 2 Sept delivery"],
          ["quiet","Keeps the bottle in the library — carry it again anytime."],["hold","Hold to write it off"]],
    why="A ledger write is a real commitment — wax."),
  O("The zones", "migrate", "sheet", eyebrow="Cellar floor", title="The zones",
    source="components/inventory/StorageLocationManager.tsx:327",
    body=[["item","Cellar · rack A","capacity 96 · 88 bottles"],["item","Cellar · rack B","capacity 96 · 61 bottles"],
          ["item","Bar · back shelf","capacity not recorded · 24 bottles"],["item","Walk-in · door","12 bottles"],
          ["btns",["Add a zone"]],["quiet","Drag to reorder. A zone holding bottles cannot be deleted until they are moved."]],
    footer="Zones are confirmed on the cellar floor first (2026-09-04) — this is that same list, opened from /inventory.",
    why="The zones are one object the house owns."),
  O("Spot count", "migrate", "sheet", seal=True, eyebrow="Öküzgözü 2022 · Cellar · rack B", title="Spot count",
    source="pages/inventory/command/SpotCountPanel.tsx:210 (opened from RowExpansion.tsx:384)",
    body=[["two",["Counted","9"],["On the book","11"]],["fact","Difference","−2 bottles"],
          ["field","","Why, if you know — e.g. two poured for a tasting, unrecorded",True],["hold","Hold to record the count"]],
    footer="The count writes a correction; the book keeps both figures.",
    why="Opened from the row expander; one bottle's count is one record."),
  O("Receipt record", "retire", None, source="pages/inventory/command/ReceivingWorkspace.tsx:376",
    acts="Ordered · shipped · invoiced · accepted per line, agreed vs invoice price, credit due, a line not on the invoice",
    went="/receipts is the receipts desk (ReceiptsNext). /inventory links there and never overlays it."),
])

# ─────────────────────────────────────────── cellar ──
P("/cellar · /wines · /beer · /whiskey · /cocktails · /spirits · /non-alcoholic · /soft-drinks", "cellar", "wines.md",
  "The old library added a bottle through six modals and a scanner. The register keeps one — 'carry this bottle', shared with /inventory — plus two panels for the reader's questions. The register still mounts one legacy modal today.",
  flag="mudavym_design_cellar", overlays=[
  O("Carry these bottles (from a menu scan)", "migrate", "sheet", eyebrow="The register", title="Carry these bottles",
    source="pages/cellar/next/WineRegister.tsx imports components/wines/MenuScannerModal.tsx:21 (legacy, fixed-inset)",
    body=[["sect","From the menu scan · 9 found"],
          ["item","Öküzgözü 2022 · Kavaklıdere","read with confidence 0.91",True],
          ["item","Boğazkere 2021 · Kavaklıdere","0.88",True],
          ["item","Chianti Classico 2021 · Banfi","0.74 — check the producer"],
          ["btns",["Carry the 8 I ticked",True]]],
    footer="The detection half is real; the approve half wrote nothing before (WineRegister.tsx:32-47).",
    why="The same sheet as /inventory's, opened at its 'menu scan' start."),
  O("Is this the bottle?", "owed", "panel", eyebrow="The label reader", title="Is this the bottle?",
    source="components/wines/WineValidationModal.tsx:162 · components/wines/AddWineModal.tsx:148 ('Wine detected')",
    body=[["two",["Name","Öküzgözü"],["Producer","Kavaklıdere"]],["two",["Vintage","2022"],["Type","Red"]],
          ["two",["Region","Elazığ"],["Grape","Öküzgözü"]],
          ["note","The reader is sure of the producer and unsure of the vintage — check the <b>2</b> before you confirm."],
          ["btns",["Yes, carry it",True],["Fix a field"],["Not this bottle"]]],
    why="A question the reader must answer before anything is written."),
  O("Photograph the label", "target", "panel", eyebrow="Camera", title="Photograph the label",
    source="components/scanner/CameraCapture.tsx:607 — also mounted by /get-started and the orders scanner",
    body=[["frame","viewfinder"],["quiet","Hold the bottle so the label fills the frame."],
          ["btns",["Take the photo",True],["Upload a file instead"]]],
    why="A step answered once; the page stays dimmed beneath."),
  O("Wine detail", "retire", None, source="pages/WineLibrary.tsx:1297",
    acts="Country and region, grape, vintage, stock against threshold; add to inventory, reorder, remove",
    went="The register row expands in place (sketch 095 — the house pattern for ledger tables)."),
  O("Reorder wine", "retire", None, source="pages/WineLibrary.tsx:1486",
    acts="Quantity, custom price vs 'ask provider', providers, notes, auto-reorder frequency",
    went="An order is written on /orders (What was agreed · Make this order repeat)."),
  O("How to add (chooser)", "retire", None, source="components/wines/AddWineSelectionModal.tsx:33",
    acts="Single wine · Menu scanner · Receive a delivery · Spreadsheet", went="The carry sheet's 'Start from'."),
  O("Add wine (label photo)", "retire", None, source="components/wines/AddWineModal.tsx:148",
    acts="Upload a label, the AI reads it, detected fields", went="Carry this bottle + Is this the bottle?"),
  O("Add to inventory from the library", "retire", None, source="components/wines/AddToInventoryFromLibraryModal.tsx:498",
    acts="Quick add; already in inventory → add stock or a separate entry; presets, cost, providers", went="Carry this bottle."),
  O("Dev: manual wine entry", "delete", None, source="components/wines/DevManualWineEntry.tsx:330",
    acts="Keyboard rapid entry for developers", went="Dev-only. Delete, or move under /dev-sandbox."),
  O("Dev: label test photos", "delete", None, source="components/wines/DevWinePhotoUpload.tsx:106",
    acts="'YOLOv8 + OCR detection — programmer access only'", went="Dev-only. Delete."),
  O("Add wine (unified chooser)", "delete", None, source="components/wines/AddWineUnifiedModal.tsx:53 — nobody imports it",
    acts="Choose how to add wines", went="Dead code. Delete."),
  O("Wine research queue", "delete", None, source="components/wines/WineResearchQueue.tsx:225 — nobody imports it",
    acts="Queue unknown wines for research", went="Dead code. Delete."),
])

# ─────────────────────────────────────────── providers ──
P("/providers", "providers", "providers.md",
  "The twin sheet is built and carries the vendor's terms. Adding a vendor is owed: the catalogue search, the custom vendor and the duplicate check are one sheet and one question.",
  flag="mudavym_design_providers", overlays=[
  O("The vendor's twin", "built", "sheet", eyebrow="Wine distributor", title="Kavaklıdere",
    source="pages/providers/next/TwinSheet.tsx:68",
    body=[["sect","What the platform has learned"],["fact","Contact","Hasan Demir"],["fact","Phone","+90 312 000 00 00"],
          ["fact","Lead time","4 days · from 11 deliveries"],["fact","Payment terms","Net 30 · written 2 Sept by Ayşe"],
          ["fact","Minimum order","₺ 5,000"],["fact","Regions","Ankara · Antalya"],["fact","Last contact","3 Sept · a reply on order 118"]],
    footer="Terms sit on the vendor's row with a provenance per field (ADR 0116).",
    why="One vendor, opened from the list you can still see."),
  O("A new vendor", "owed", "sheet", eyebrow="The book of vendors", title="A new vendor",
    source="components/providers/AddProviderModal.tsx:361 (+ Add Provider Type :629) · components/providers/VendorSearchModal.tsx:161",
    body=[["field","","Search the catalogue — Sevilen",False],["sect","From the catalogue · 2 found"],
          ["item","Sevilen Şarapları","İzmir · importer and distributor · verified",True],["item","Sevilen US Imports","New Jersey · importer"],
          ["sect","Or a vendor of your own"],["two",["Name","Premium Wine Distributors",True],["Contact","First and last name",True]],
          ["two",["Phone","",True],["Email","",True]],["field","Address","Start typing the address…",True],
          ["btns",["Add to the book",True]]],
    footer="Terms are written on the vendor's row afterwards, each with its provenance.",
    why="The vendor being added is one object; the old page split it across three modals."),
  O("A vendor you already have?", "owed", "panel", eyebrow="Possible duplicate", title="This looks like a vendor already in the book",
    source="components/providers/VendorMatchModal.tsx:108",
    body=[["item","Kavaklıdere","in your providers · 14 orders",True],["item","Kavaklidere Şarapları (new)","same phone, same city"],
          ["btns",["Use the one on file",True],["Keep both — they are different"]]],
    why="A question with two answers before a write."),
  O("Edit provider", "retire", None, source="components/providers/EditProviderModal.tsx:678",
    acts="Rating, type, terms, minimum order, contact, recent orders", went="The twin sheet's edit half; terms on the row."),
  O("Send message", "retire", None, source="components/providers/SendMessageSlideOver.tsx:319",
    acts="Email or SMS from a template", went="The composer (letters); the text sender is ADR 0121."),
  O("Provider card", "retire", None, source="pages/Providers.tsx:1355",
    acts="Email, website, portfolio, address, contacts, regions; favourite, edit, remove, call", went="The twin sheet."),
  O("Add provider type", "retire", None, source="components/providers/AddProviderModal.tsx:629",
    acts="A custom business type with an icon", went="A field inside the new-vendor sheet."),
])

# ─────────────────────────────────────────── communications ──
P("/communications", "communications", "communications.md",
  "The composer and the template library are built at 640. Eight legacy modals retire with the two builders (ADR 0118). One act is owed: approving a reply the house drafted.",
  flag="mudavym_design_communications", overlays=[
  O("A letter from the house", "built", "sheet", wide=True, seal=True, eyebrow="The house writes", title="A letter from the house",
    source="pages/communications/next/Compose/ComposeSheet.tsx:209",
    body=[["sect","Start from"],["chips",["A blank letter",True],["Something the house noticed",False]],
          ["two",["To","Hasan Demir · Kavaklıdere"],["From","orders@meyhanesim.mudavym.com"]],
          ["field","Subject","Order 118 — delivery Thursday"],
          ["text","Hasan Bey, thank you for confirming Thursday. Five cases of the 2022 at ₺2,400 per case, held to the 15th — we will take it. Ayşe"],
          ["hold","Hold to send"]],
    footer="Nothing was queued and nothing was sent.",
    why="A letter is prose; 440 minus padding is ~46 characters — the one wide case ADR 0112 anticipated."),
  O("Templates", "built", "sheet", wide=True, eyebrow="House letters", title="Templates",
    source="pages/communications/next/TemplateSheet.tsx:132",
    body=[["btns",["Write a new template",True]],["sect","Start from something the house noticed"],
          ["item","Öküzgözü sold 41% above its 30-day pace","reports · 2 Sept · the engine's sentence, with its provenance"],
          ["sect","On file · 4"],["item","Delivery confirmation","used 12 times · last 3 Sept"],["item","Price check","used 3 times"],
          ["two",["Name","Delivery confirmation"],["Purpose","Confirm a delivery day with the vendor"]],
          ["field","Subject","Order {{order}} — delivery {{day}}"]],
    why="The library is one object; a template is edited in place inside it."),
  O("The house's reply, drafted", "owed", "panel", seal=True, eyebrow="Drafted · order 118 · round 2", title="The house's reply, drafted",
    source="components/orders/DraftEmailApprovalPanel.tsx:130 (legacy, on /orders)",
    body=[["fact","To","Hasan Demir · Kavaklıdere"],["field","Subject","Re: Order 118 — five cases"],
          ["text","Thank you — five cases of the 2022 at ₺2,400 per case, delivery Thursday. Please confirm the hold to the 15th."],
          ["quiet","The Mudavym disclaimer is appended and cannot be removed."],
          ["hold","Hold to send"],["btns",["Edit first"],["Discard"]]],
    footer="A draft never looks sent (prc-02).",
    why="A question with the seal — nothing reaches a vendor without a person's hold (ADR 0118)."),
  O("Gmail template builder", "retire", None, source="components/documents/GmailTemplateBuilder.tsx:852",
    acts="The old email builder: subject, to, cc, bcc, blocks, categories", went="The composer and the template library (ADR 0118 retires both builders)."),
  O("SMS template builder", "retire", None, source="components/documents/SMSTemplateBuilder.tsx:423",
    acts="SMS templates with variables", went="The house's text sender (ADR 0121, research)."),
  O("Select report type", "retire", None, source="components/communications/ReportTypeModal.tsx:122",
    acts="Pick a report type and a template for a report email", went="'Start from something the house noticed'."),
  O("Create category", "retire", None, source="components/documents/NewCategoryModal.tsx:112",
    acts="A template category with icon and colour", went="A template's Purpose."),
  O("Switch component type", "retire", None, source="components/documents/VariationSelectorModal.tsx:124",
    acts="Convert a builder block to another format", went="Builder-internal; goes with the builder."),
  O("Quick Gmail send", "retire", None, source="components/emails/QuickGmailModal.tsx:238",
    acts="Send from a saved template or compose custom; CC/BCC", went="The composer."),
  O("Send email (saved template)", "retire", None, source="components/documents/SavedTemplates.tsx:580",
    acts="Recipient, subject, 'Email sent!'", went="The composer; the seal on the subdomain, an undo window on the house's own mailbox."),
  O("Send SMS (saved template)", "retire", None, source="components/documents/SavedSMSTemplates.tsx:619",
    acts="Recipient phone, preview, 'SMS sent!'", went="The text sender (ADR 0121)."),
  O("Template library (new template · sent)", "delete", None, source="components/documents/TemplateLibrary.tsx:606 and :945 — nobody imports it",
    acts="'Choose how you'd like to start' and a 'Sent!' confirmation", went="Dead code. Delete."),
])

# ─────────────────────────────────────────── calendar ──
P("/calendar", "calendar", "calendar.md",
  "The entry sheet is built and says a failed save in words. The meeting-note prompt is owed as a panel; the ⌘K day-book assistant (ADR 0111) is planned as a panel.",
  flag="mudavym_design_calendar", overlays=[
  O("The entry", "built", "sheet", eyebrow="The entry", title="Kavaklıdere delivery",
    source="pages/calendar/next/EventSheet.tsx:230",
    body=[["chips",["Delivery",True],["Meeting",False],["Shift",False],["Reminder",False],["custom",False]],
          ["field","Title","Kavaklıdere delivery"],["two",["Date","Thu 11 Sept"],["All day","No"]],
          ["two",["Starts","10:00"],["Ends","11:00"]],["field","Repeat","Does not repeat"],["field","Status","Expected"],
          ["alert","Not saved","The gateway refused the dates: 'Ends' is before 'Starts'. The entry is unchanged."],
          ["btns",["Keep it",True],["Remove"]]],
    why="One entry is one object; the month stays readable beneath."),
  O("A note from this meeting?", "owed", "panel", eyebrow="Tuesday's meeting · Kavaklıdere tasting", title="A note from this meeting?",
    source="pages/calendar/MeetingMemoPrompt.tsx:109",
    body=[["field","","What was said, what was decided…",True],
          ["two",["Filed under","Vendors · Kavaklıdere"],["Document type","Meeting note"]],
          ["quiet","Obsidian sync — coming soon."],["btns",["Save the note",True],["Later"],["Skip"]]],
    why="A question asked once, after the meeting ends (ADR 0111 unifies meetings, notes and reminders)."),
  O("Ask the day-book", "target", "panel", eyebrow="⌘K on the calendar", title="Ask the day-book",
    source="sketch 098 · ADR 0111 (planned, not built)",
    body=[["field","","Move Thursday's delivery to Friday…",True],["sect","It would do"],
          ["item","Move 'Kavaklıdere delivery' to Fri 12 Sept, 10:00","one entry changes"],
          ["item","Tell Hasan Demir","a letter, drafted — you hold to send"],
          ["btns",["Do it",True],["Not that"]]],
    footer="The assistant proposes; the seal applies (ADR 0113).",
    why="A question — the palette's shape, scoped to one page."),
  O("Event modal", "retire", None, source="pages/calendar/EventModal.tsx:1511 (1,593 lines)",
    acts="The old event editor", went="The entry sheet."),
  O("Mobile sidebar scrim", "none", None, source="pages/calendar/CalendarPage.tsx:597",
    acts="Dims the page behind the calendar's mobile sidebar", went="Paint only — not a shape."),
])

# ─────────────────────────────────────────── reports ──
P("/reports", "reports", "reports.md",
  "Ask the book is built; the insight palette and the KPI spotlight retire into it and into cuttings that expand in place. Seven dashboard-builder modals are dead code.",
  flag="mudavym_design_reports", overlays=[
  O("Ask the book", "built", "panel", title="Ask the book", source="pages/reports/next/AskTheBook.tsx:94",
    body=[["field","","Search what the engine has already said…",True],["sect","The register · 2 match"],
          ["item","Öküzgözü sold 41% above its 30-day pace","2 Sept · velocity · confidence high"],
          ["item","Kavaklıdere's price is 6% under its 30-day average","1 Sept · market price"],
          ["quiet","The book holds no sentence about 'labour' for this house — nothing is invented to fill the gap (ADR 0020)."]],
    why="A question; the answer is only what the engine already said."),
  O("Insight palette", "retire", None, source="components/reports/organisms/AICommandPalette.tsx:77",
    acts="Search insights (⌘K)", went="Ask the book."),
  O("KPI spotlight", "retire", None, source="components/reports/molecules/KPISpotlightView.tsx:507",
    acts="Detailed breakdown of one KPI", went="A cutting is a question and expands in place (sketch 096)."),
  O("Arrange charts", "delete", None, source="components/reports/ChartArrangementModal.tsx:108 — nobody imports it",
    acts="Drag to reorder, toggle visibility, reset", went="The sheet is arranged from the keyboard (sketch 096). Delete."),
  O("Configure chart", "delete", None, source="components/reports/ChartConfigModal.tsx:104 — reached only from dead files",
    acts="Data source, chart type, size", went="Dead code. Delete."),
  O("Add widget", "delete", None, source="components/reports/DashboardGrid.tsx:361 — nobody imports it", acts="Choose a widget type", went="Dead code. Delete."),
  O("Edit layout", "delete", None, source="components/reports/EditLayoutPanel.tsx:223 — nobody imports it", acts="Layout presets, edit mode", went="Dead code. Delete."),
  O("Widget selector", "delete", None, source="components/reports/WidgetSelector.tsx:119 — nobody imports it", acts="Search widget options", went="Dead code. Delete."),
  O("Choose KPI metric · Add KPI card", "delete", None, source="components/reports/organisms/KPISection.tsx:148 and :217 — nobody imports it",
    acts="Pick what a KPI card displays", went="Dead code. Delete."),
  O("Preview overlay", "delete", None, source="components/reports/preview/PreviewOverlay.tsx:73 — nobody imports it", acts="Full-screen preview", went="Dead code. Delete."),
])

# ─────────────────────────────────────────── documents-reports ──
P("/documents-reports", "documents-reports", "documents-reports.md",
  "No overlay on the rebuilt page: the Sorting Office's reading pane is the detail surface (Direction D). One legacy preview retires.",
  flag="mudavym_design_documents_reports", overlays=[
  O("Document preview", "retire", None, source="pages/DocumentsPage.tsx:985",
    acts="Preview a report: download, print, email, copy link, delete", went="The reading pane."),
])

# ─────────────────────────────────────────── notifications ──
P("/notifications", "notifications", "notifications.md",
  "The rebuilt page opens a row in place and has no overlay of its own. The ratified rule is drawn: a one-click approval from the bell opens the panel first.",
  flag="mudavym_design_notifications", overlays=[
  O("Approve from the bell", "owed", "panel", seal=True, eyebrow="From the bell · order 118", title="Approve the Kavaklıdere order?",
    source="ADR 0112, founder answer 2026-09-04 — 'a one-click approval from the bell opens the panel first'; not built",
    body=[["fact","Lines","5 cases Öküzgözü 2022"],["fact","Agreed","₺ 2,400 per case · ₺ 12,000"],["fact","Delivery","Thu 11 Sept"],
          ["hold","Hold to approve"]],
    footer="The seal never sits in a popover; the bell hands off to this panel.",
    why="The bell is a menu; a commitment needs a room that cannot be dismissed by accident."),
  O("Notification detail", "retire", None, source="pages/Notifications.tsx:1513",
    acts="'Gathering context…', suggested next steps, review and approve a draft, take action",
    went="The row expands in place (`.nt-expand`); a sealed act opens the panel above."),
  O("Create one-tap action", "retire", None, source="pages/Notifications.tsx:1705", fork="F4",
    acts="Categories, quick-start templates, a trigger: time-based, threshold or manual",
    went="One-tap actions moved to the dashboard rail; a person-authored action is built as <b>A one-tap action of your own</b> on / (decided 2026-09-05, F4)."),
  O("Add vendor deadline", "delete", None, source="components/notifications/VendorDeadlineSettings.tsx:184 — nobody imports it",
    acts="A vendor's order cutoff by weekday and time, hours-before notice", went="Cutoffs live in vendor terms (ADR 0116). Delete."),
])

# ─────────────────────────────────────────── recommendations ──
P("/recommendations", "recommendations", "recommendations.md",
  "The docket dismisses inline and schedules through a route. The old assignee picker is rebuilt as the popover drawn here (F4 rule, 2026-09-05 — confirm).",
  flag="mudavym_design_recommendations", overlays=[
  O("Who takes this?", "owed", "popover", eyebrow="Assign", title="Who takes this?", fork="F4",
    source="pages/Recommendations.tsx:980 — not on the rebuilt docket",
    body=[["item","Mehmet Kaya","bar",True],["item","Elif Şahin","floor"],["item","Nobody — clear it"]],
    why="A choice from a short list, anchored to the entry's control. Built by the F4 rule of 2026-09-05 (every legacy act gets rebuilt to its full purpose) — this fifth act was not on the option list, so it is stated here for the founder to confirm."),
])

# ─────────────────────────────────────────── settings ──
P("/settings", "settings", "settings.md",
  "The four location dialogs migrated on 2026-09-04. Two shared dialogs still render legacy inside the rebuilt page — both are questions.",
  flag="mudavym_design_settings", overlays=[
  O("Add a location", "built", "sheet", eyebrow="The locations", title="Add New Location",
    source="components/locations/AddLocationDialog.tsx:185 (opened at pages/settings/next/LocationsSection.tsx)",
    body=[["field","Location name","Meyhane Sim · Lara"],["field","Chain / Brand","Meyhane Sim"],["field","Country","Türkiye"],
          ["field","Street address","Lara Cd. 112"],["two",["City","Antalya"],["Postal","07230"]],["field","Phone","",True],
          ["btns",["Add the location",True]],["quiet","Not added — nothing is written until you do."]],
    why="One location being written."),
  O("New chain", "built", "sheet", eyebrow="The locations", title="New chain", source="components/locations/CreateChainDialog.tsx:121",
    body=[["field","Chain name","Meyhane Sim"],["sect","Add locations to this chain"],
          ["chips",["Kaleiçi",True],["Lara",True],["The Grill Co.",False]],["btns",["Create the chain",True]]],
    why="One chain being written."),
  O("Edit location", "built", "sheet", eyebrow="The locations", title="Edit location", source="components/locations/EditLocationChainDialog.tsx:134",
    body=[["two",["Name","Meyhane Sim · Lara"],["City","Antalya"]],["field","Chain","Meyhane Sim"],
          ["note","Moving from <b>Standalone</b> — this places Lara under Meyhane Sim in the branch switcher."],["btns",["Save",True]]],
    why="One location's record."),
  O("Add to Meyhane Sim", "built", "panel", eyebrow="The locations", title="Add to Meyhane Sim", source="components/locations/AssignToChainDialog.tsx:106",
    body=[["quiet","Pick existing locations to move into this chain."],["chips",["Lara",True],["Kaş",False]],
          ["btns",["Add them",True],["Create a brand-new location instead"]]],
    why="A question about which."),
  O("Share this with the engine?", "migrate", "panel", eyebrow="Consent", title="Turn on the reading of sales?",
    source="components/settings/ConsentDialog.tsx:71 (opened from components/settings/ServicesPermissions.tsx:300)",
    body=[["sect","What gets shared"],["item","Sale lines by item and hour"],["item","Stock levels"],
          ["sect","What never leaves"],["item","Guest names, card details, staff pay"],
          ["quiet","Read the privacy notice."],["btns",["Turn it on",True],["Keep it off"]]],
    why="A question. Settings stay asserted, not sealed (2026-09-04)."),
  O("Carry your vendors to the new location?", "migrate", "panel", eyebrow="Lara · just added", title="Carry your vendors to the new location?",
    source="components/providers/BranchProviderTransferModal.tsx:109",
    body=[["chips",["Kavaklıdere",True],["Sevilen",True],["Southern Glazer's",False]],["btns",["Carry them",True],["Skip for now"]]],
    why="A question about a batch, asked once after a write."),
])

# ─────────────────────────────────────────── team ──
P("/team", "team", "team.md",
  "Eleven house overlays are built, including the wave's one named exception. The legacy desk's seven surfaces retire with it the day a house's flag turns on; certifications have no house surface (fork F4).",
  flag="mudavym_design_team", overlays=[
  O("People", "built", "sheet", eyebrow="The roster", title="People", action="Add", source="pages/team/next/RosterSheet.tsx:219",
    body=[["item","Mehmet Kaya","bar · full time · Kaleiçi"],["item","Elif Şahin","floor · part time"],
          ["item","Team member","display name not yet linked — 'links the account on signup'"]],
    why="The roster is one object."),
  O("On the roster", "built", "sheet", eyebrow="On the roster", title="Mehmet Kaya", source="pages/team/next/RosterSheet.tsx:392 (MemberSheet)",
    body=[["two",["Name","Mehmet Kaya"],["Email","mehmet@example.com"]],["two",["Phone","+90 5xx"],["Position","Bartender"]],
          ["two",["Employment","Full time"],["Home location","Kaleiçi"]],["two",["Hourly wage","₺ 180"],["Status","Active"]],
          ["field","Skills","bar, somm, closer"],["btns",["Keep them",True],["Remove"]]],
    why="One person's record."),
  O("Edit this shift", "built", "sheet", eyebrow="Shift on the schedule", title="Edit this shift", source="pages/team/next/ShiftSheet.tsx:98",
    body=[["field","Who","Mehmet Kaya"],["two",["Date","Thu 11 Sept"],["Station","Main bar"]],["two",["Start","16:00"],["End","00:30"]],
          ["field","Kind","Service"],["alert","Not removed","The shift was not removed. It is still on the schedule."],
          ["btns",["Keep it",True],["Remove"]]],
    why="One shift's record; the week stays visible beneath."),
  O("Publish this week", "built", "panel", seal=True, eyebrow="8–14 Sept", title="Publish this week", source="pages/team/next/TeamOverlays.tsx:90 (PublishPanel)",
    body=[["fact","Shifts","34 · 2 open"],["sect","Who has opened the week"],["item","Elif Şahin","yesterday"],["item","Mehmet Kaya","not yet"],
          ["field","","The week's note",True],["hold","Hold to publish"],["btns",["Not yet"]]],
    why="A commitment the whole crew sees — wax."),
  O("Copy last week", "built", "panel", seal=True, eyebrow="into 15–21 Sept", title="Copy last week", source="pages/team/next/TeamOverlays.tsx:167 (CopyWeekPanel)",
    body=[["fact","Last week","34 shifts · 6 people"],["note","Replaces what is on 15–21 Sept."],["hold","Hold to replace the week"],["btns",["Leave it"]]],
    why="A question about a batch that overwrites — the hold, because it replaces."),
  O("A note to the crew", "built", "sheet", eyebrow="On the week of 8 Sept", title="A note to the crew", source="pages/team/next/TeamOverlays.tsx:519 (CrewNoteSheet)",
    body=[["field","Note","Saturday is the Kavaklıdere tasting — Mehmet opens the bar at 15:00."],["sect","Delivered · read"],
          ["item","Elif Şahin","read 09:12"],["item","Mehmet Kaya","delivered"],["btns",["Send",True],["Cancel"]]],
    footer="Inbox and push only (2026-09-04).", why="One note with its receipts."),
  O("Time off", "built", "sheet", eyebrow="Requests on file", title="Time off", source="pages/team/next/TeamOverlays.tsx:640 (TimeOffSheet)",
    body=[["sect","Waiting on you"],["item","Elif Şahin · 20–22 Sept","family"],["btns",["Approve",True],["Deny"]],
          ["sect","Decided"],["item","Mehmet Kaya · 3 Sept","approved by Ayşe"],["btns",["File a request for someone"]],
          ["alert","Not recorded","The decision was not recorded, so the request is still where it was."]],
    why="The requests are one register."),
  O("Export the week", "built", "popover", title="Export the week", source="pages/team/next/TeamOverlays.tsx:828 (ExportPopover)",
    body=[["item","Print the floor sheet","opens the print dialog"]], why="A control's own menu."),
  O("Shift actions", "built", "popover", title="Shift actions", source="pages/team/next/WeekGrid.tsx:424",
    body=[["item","Edit shift"],["item","Duplicate onto the same day"],["item","Report a call-out"],["item","Offer cover","Cover, if this falls through"],["item","Delete shift"],
          ["alert","Did not send","The cover offer did not send. Nobody was asked."]],
    why="A row's own menu."),
  O("What changed here", "built", "sheet", eyebrow="The record", title="What changed here", source="pages/team/next/TeamRecord.tsx:273 (TrailSheet)",
    body=[["item","labor_target_pct 28 → unset","3 Sept · Ayşe · a default rendered as unset"],
          ["item","Mehmet Kaya · wage ₺160 → ₺180","1 Sept · Ayşe"],["item","Week 36 published","31 Aug · Ayşe"]],
    why="The audit trail of one record."),
  O("Invite a team member", "built", "popover", modal=True, eyebrow="The exception", title="Invite a team member",
    source="components/team/InviteTeamDialog.tsx:199 — 'Popover modal', the one exception ADR 0112 names; also opened from /get-started and /settings",
    body=[["field","Email (optional)","colleague@restaurant.com",True],["chips",["Manager",False],["Staff",True]],
          ["fact","Expires","7 days from generation · single-use"],["chips",["Add roster-only staff (no Mudavym login)",False]],
          ["btns",["Generate the code",True],["Cancel"]]],
    why="Anchored under its button like a popover, but a form that commits — so it traps focus and dims. The one exception; the studio invite reuses this component (F2, 2026-09-05)."),
  O("Certifications on file", "owed", "sheet", eyebrow="The roster · Mehmet Kaya", title="Certifications on file", fork="F4",
    source="pages/team/command/OpsRulesPanel.tsx:37 (legacy desk); team_certifications has no role or applies-to column; built by the founder's ruling 2026-09-05",
    body=[["item","Alcohol service","issued 12 Mar 2026 · expires 12 Mar 2028",True],["item","Food handler","issued 3 Jan 2025 · expires 3 Jan 2027"],
          ["alert","Expiring","Food handler expires in 120 days. The roster will say so on the shift."],
          ["sect","Add one"],["two",["Type","Fire safety"],["Issued","",True]],["field","Expires","",True],["btns",["Put it on file",True]]],
    footer="A certificate is a fact with two dates; the schedule reads the second one.",
    why="One person's certificates are one record; opened from the roster row."),
  O("Desk row menu", "retire", None, source="pages/team/command/ManagerShiftDesk.tsx:868",
    acts="Message · Edit shift · Duplicate · Delete shift · Copy last week · Re-publish", went="Shift actions, Publish this week, Copy last week."),
  O("Desk message composer", "retire", None, source="pages/team/command/ManagerShiftDesk.tsx:981", acts="A message to the crew", went="A note to the crew."),
  O("Desk confirm sheet", "retire", None, source="pages/team/command/ManagerShiftDesk.tsx:1061", acts="Confirm publish or copy", went="Publish this week · Copy last week."),
  O("Desk people sheet", "retire", None, source="pages/team/command/ManagerShiftDesk.tsx:1132", acts="People · Rules · Add", went="People (the roster sheet)."),
  O("Desk editors", "retire", None, source="pages/team/command/editors.tsx:23", acts="Shift and member editors", went="Edit this shift · On the roster."),
  O("Ops rules", "retire", None, source="pages/team/command/OpsRulesPanel.tsx:37", fork="F4",
    acts="Coverage rules (day, period, minimum staff, role) and certifications (type, issued, expires)",
    went="The first-rule form is inline on the rebuilt page (ADR 0089). <b>Certifications</b> are built as the sheet drawn above (decided 2026-09-05, F4)."),
  O("Import shift configurations", "delete", None, source="components/team/ShiftImportModal.tsx:135 — opened only from the legacy desk",
    acts="Upload CSV, Excel or JSON shift templates; the apply path was simulated (file.size / 80)", went="No import route exists. Delete with the desk."),
])

# ─────────────────────────────────────────── pages not yet rebuilt ──
P("/promotions", "promotions", "promotions.md",
  "Not rebuilt. Two legacy overlays take their shapes now so the rebuild inherits them.", rebuilt=False, overlays=[
  O("The offer", "target", "sheet", eyebrow="Sevilen · by mail · 2 Sept", title="12% off Kalecik Karası, cases of 6",
    source="pages/Promotions.tsx:336",
    body=[["fact","Ends","30 Sept"],["fact","Applies to","Kalecik Karası 2021 · 2022"],["fact","Code","SEV-KK-12"],["fact","Read with confidence","0.86"],
          ["btns",["Apply to a new order",True],["Dismiss"]]],
    footer="Offer dismissed — Undo.", why="One offer is one object."),
  O("Offer menu", "target", "popover", title="Offer", source="pages/Promotions.tsx:328",
    body=[["item","Copy code"],["item","Apply to a new order"],["item","Dismiss"]], why="A row's own menu."),
])
P("/distributors", "distributors", "distributors.md",
  "Not rebuilt. Already a right drawer — the shape was right, the primitive was not.", rebuilt=False, overlays=[
  O("Distributor detail", "target", "sheet", eyebrow="Distributor · verified by Mudavym", title="Southern Glazer's Wine & Spirits",
    source="pages/distributors/command/DistributorDrawer.tsx:125",
    body=[["sect","Contact"],["fact","Phone","+1 312 000 0000"],["fact","Email","orders@example.com"],
          ["sect","Where they can sell"],["fact","Licence territory","Illinois · Michigan"],
          ["sect","Portfolio"],["fact","Producers","Banfi · Kavaklıdere · 214 more"],
          ["sect","Data quality"],["fact","Verified","details verified by Mudavym · 2 Sept"],["btns",["Add to my providers",True]]],
    why="One distributor is one object."),
])
P("/studio/certify", "studio-certify", "studio-certify.md",
  "Not rebuilt. The same act as the team invite: it reuses the one exception component with a second opener (decided 2026-09-05, F2).", rebuilt=False, overlays=[
  O("Invite a contributor", "target", "popover", modal=True, eyebrow="Studio", title="Invite a contributor", fork="F2",
    source="pages/studio/certify/InviteDialog.tsx:106 (Radix dialog today)",
    body=[["field","Email","contributor@example.com",True],["chips",["Certified Contributor",True],["Developer",False],["Review Admin",False]],
          ["fact","Expiry","7 days (standard)"],["btns",["Generate the invite",True],["Cancel"]]],
    why="The same act as Invite a team member. Decided 2026-09-05 (F2): the same component — InviteTeamDialog's Popover modal — with a second opener; one component, however many openers, is one exception."),
])
P("/admin/health", "admin-health", "admin-health.md", "Not rebuilt. One overlay: a payload, which is a record.", rebuilt=False, overlays=[
  O("Live payload", "target", "sheet", eyebrow="Live payload from /api/v1/health/live", title="Live payload",
    source="pages/AdminHealth.tsx:226",
    body=[["mono","{ \"status\": \"ok\",\n  \"commit\": \"a26f265c\",\n  \"bootedAt\": \"2026-09-05T14:02:11Z\" }"],["fact","Fetched","14:02:19Z · 41 ms"]],
    why="One response is one object; reading it wants the page beside it."),
])
P("/get-started", "get-started", "get-started.md",
  "Not rebuilt. Mounts two overlays drawn elsewhere: Photograph the label (cellar) and Invite a team member (team).", rebuilt=False, overlays=[])

NO_OVERLAY = ["/login","/register","/forgot-password","/reset-password","/verify-email","/invite/:code","/no-access","/privacy",
  "/v/:slug","/onboarding (redirect)","/studio","/studio/queue","/studio/invite/:token","/simpos/:restaurantId (+orders, scenarios)",
  "/authorize/:integrationId","/inventory-legacy (redirect)","/vendor-prices","/dev/truth","/recommendations/catalog","/credits","/logs",
  "/profile","/connections","/help","/admin","/sommelier (HOLD)","/services","/dev-sandbox (mounts the retiring builders)","/calendar-classic"]

ANSWERS = {
  "F1": "Ratified 2026-09-05 — ADR 0112 is Locked.",
  "F2": "Reuse InviteTeamDialog with a second opener. One component, however many openers, is one exception.",
  "F5": "The owed sheet on /orders is the manual entry.",
  "F7": "The KPI row expands in place; no overlay.",
  "F3": "A 640 sheet on /inventory, not a route.",
  "F4": "All of them get built, to their full purpose — functionality, endpoints, UI/UX, smoothness and above all the design (the founder's bar, 2026-09-05). Pause/resume the AI becomes a control on the responses sheet; a person's own one-tap action, an auction lot and certifications are drawn as owed sheets; assign-a-recommendation follows the same rule and awaits an explicit yes.",
  "F6": "HouseHeader's bell and user menu survive; Header.tsx's house branch is deleted, its legacy branch stays byte-identical.",
}
FORKS = [
  ("F1","Ratify the three shapes.","ADR 0112 is still Proposed. Everything drawn here assumes Sheet · Panel · Popover; if the founder wants one shape everywhere, this census is the list of what that costs (the sheet exists so the list stays readable; an anchored menu with no anchor has lost its meaning)."),
  ("F2","The studio invite.","Reuse the one exception component (Popover modal) with a second opener — my recommendation: one component, however many openers, is still one exception — or collapse the policy to two modal shapes as the ADR's revisit clause says."),
  ("F3","A delivery without an order.","A 640 sheet on /inventory (drawn), or a route under /receipts where the receipts desk already lives."),
  ("F4","Acts no house surface recreates.","Pause AI on a thread · a person-authored one-tap action or quick-action bookmark · an auction purchase · certifications on file · assign a recommendation to a person. One call per act: delete, or build the drawn shape."),
  ("F5","Where a manual order starts.","The owed 'A new order' sheet on /orders, or from a register row, the palette, or Ask AI — OrdersNext has no create path today."),
  ("F6","Two bells, two user menus.","Header.tsx's house branch and HouseHeader's HouseBell/HouseUserMenu both exist. Which survives when the house header lands on every page."),
  ("F7","The figure behind a dashboard number.","A sheet ('the working', drawn) or the house idiom — the KPI row expands in place."),
]
