"""Sketch 102 — the overlay census. ONE source of truth for index.html, README.md's
table, the page-doc subsections and the published artifact. Edit here, run build.py.

Body rows:  ["sect", label] · ["item", label, sub, on?, kbd?] · ["fact", k, v, em?]
            ["field", label, value, placeholder?] · ["two", [label,value,ph?], [label,value,ph?]]
            ["note", text] · ["quiet", text] · ["hold", text] · ["btns", [label, pri?], ...]
            ["chips", [label, on], ...] · ["table", [cols], [rows...]] · ["alert", head, text]
            ["text", paragraph] · ["mono", text] · ["frame", caption]
Statuses:   built · migrate · owed · target · retire · delete · none
Every name, figure and date below is EXAMPLE DATA, not a tenant."""

META = dict(sketch=102, name="modal-census", date="2026-09-05",
            tree="feat/mudavym-design-p4 @ origin tip, read 2026-09-05",
            primitive="apps/web/src/components/mudavym/Sheet.tsx (Sheet · Panel · Popover)")

def O(name, status, shape=None, **k):
    d = dict(name=name, status=status, shape=shape, wide=False, modal=False, seal=False,
             eyebrow=None, title=None, action=None, close="Close", body=[], footer=None,
             why=None, source=None, acts=None, went=None, fork=None)
    d.update(k); return d

PAGES = []
def P(route, slug, doc, verdict, overlays, rebuilt=True, flag=None, alias=None):
    PAGES.append(dict(route=route, slug=slug, doc=doc, verdict=verdict, overlays=overlays,
                      rebuilt=rebuilt, flag=flag, alias=alias or []))

# ─────────────────────────────────────────── the shell ──
P("shell", "shell", None,
  "Nine overlays render over every page. Eight wear the house shape while a rebuilt page is on "
  "screen and their legacy markup otherwise (lib/mudavym/shellGround.ts). The bell and the user menu "
  "existed twice; HouseHeader's survive and Header.tsx's house branch is deleted (F6, 2026-09-05).",
  rebuilt=True, overlays=[
  O("Command palette", "built", "panel", title="Command palette",
    source="components/command/CommandPalette.tsx:260",
    body=[["field","","Search pages, actions, insights…",True],
          ["sect","Pages"],["item","Orders","/orders",True,"↵"],["item","Inventory","/inventory"],
          ["sect","Actions"],["item","Approve what is waiting","3 orders on the ledger"],["item","Write a letter","/communications"],
          ["sect","Insights"],["item","Öküzgözü sold 41% above its 30-day pace","reports · 2 Sept"]],
    footer="↑↓ to navigate · ↵ to run · esc closes",
    why="A question the reader answers by typing: the middle of the screen, the page dimmed, focus trapped."),
  O("Ask AI", "built", "panel", title="Ask AI",
    source="components/askai/AskAiBar.tsx:166",
    body=[["field","","Ask for an action — reorder stock, draft a vendor reply…",True],
          ["note","<b>Ask AI proposes; you confirm.</b> Nothing runs until you do."],
          ["quiet","Drafts only — nothing reaches a vendor without a second approval."]],
    footer="esc closes", why="A question; the answer is a proposal the person still has to hold."),
  O("Keyboard shortcuts", "built", "panel", eyebrow="The house", title="Keyboard shortcuts",
    source="components/command/ShortcutsSheet.tsx:67",
    body=[["item","Open the palette","",False,"⌘ K"],["item","Ask AI","",False,"⌘ J"],["item","Recently viewed","",False,"⌘ E"],
          ["quiet","Page-specific shortcuts appear in each page's toolbar."]],
    why="A reference the reader consults and dismisses — a panel, never a sheet: there is no object."),
  O("Recently viewed", "built", "panel", eyebrow="Where you have been", title="Recently viewed",
    source="components/command/RecentlyViewed.tsx:69",
    body=[["item","Orders","2 minutes ago"],["item","Reports","14 minutes ago"],["item","Team","yesterday"],
          ["quiet","No recent pages yet — they collect as you navigate."]],
    why="A list to jump from."),
  O("The bell", "built", "popover", eyebrow="3 folded lines", title="Notifications",
    source="components/mudavym/HouseBell.tsx:127 survives; components/layout/Header.tsx:147 (the shell header's house branch) is deleted — decided 2026-09-05 (F6); its legacy branch stays byte-identical",
    body=[["item","Kavaklıdere confirmed order 118","12 min ago · a reply on the thread"],
          ["item","Öküzgözü 2022 is below par","2 left · 6 is par"],
          ["item","Week 37 is published","yesterday · 5 have opened it"]],
    footer="Rule all off · Read the whole book",
    why="A control's own menu. It never carries the seal (founder, 2026-09-04) — approving from here opens the panel first."),
  O("User menu", "built", "popover", eyebrow="ayse@example.com", title="Ayşe Yılmaz",
    source="components/mudavym/HouseUserMenu.tsx:79 survives; components/layout/Header.tsx:351 is deleted — decided 2026-09-05 (F6)",
    body=[["item","Profile"],["item","Settings"],["item","Help & Support"],["item","Log out"]],
    why="A control's own menu."),
  O("Theme", "built", "popover", title="Theme", source="components/layout/ThemeMenu.tsx:65",
    body=[["item","Paper","",True],["item","Charcoal"],["item","Follow the system"]],
    why="Dimming the whole page to pick 'Dark' is ceremony; this house rations ceremony."),
  O("Switch location", "built", "popover", eyebrow="3 locations", title="Switch location",
    source="components/layout/RestaurantBranchSwitcher.tsx:80",
    body=[["item","Meyhane Sim · Kaleiçi","Active",True],["item","Meyhane Sim · Lara","live sync"],["item","The Grill Co."]],
    footer="Add location · Manage locations", why="A choice from a short list, hanging off the control that shows the choice."),
  O("Mobile navigation scrim", "none", None, source="components/layout/DashboardLayout.tsx:60",
    acts="Dims the page behind the drawer on small screens", went="Paint only (`.mdv-scrim`) — not a shape, and it never was one."),
  O("Nav-rail hint", "none", None, source="components/layout/Sidebar.tsx:255",
    acts="The label that appears when the collapsed rail is hovered", went="An anchored, non-interactive label, portalled only so it can wear the ground. Not a shape."),
  O("Header search", "retire", None, source="components/layout/Header.tsx:464",
    acts="'Search wines, orders, reports…' — a second search box in the header", went="The palette is the search."),
])

# ─────────────────────────────────────────── dashboard ──
P("/", "dashboard", "dashboard.md",
  "Four legacy modals, none of which survives as an overlay: three retire into surfaces the rebuilt page already has, and the figure detail becomes an in-place expansion under the KPI row (decided 2026-09-05, F7 — still to build).",
  flag="mudavym_design_dashboard", overlays=[
  O("The working behind a figure", "retire", None, fork="F7",
    source="pages/Dashboard.tsx:1109 — the Vendor Spend · Active Inventory · Pending Orders · Low Stock detail modals; nothing on pages/dashboard/next/KpiRow.tsx opens today",
    acts="What one dashboard figure is made of: the orders, vendors and rows it summed",
    went="Decided 2026-09-05 (F7): the KPI row expands in place — 'show the working' under the figure, like DayDetail under the sales calendar. Not an overlay; the expansion is still owed on KpiRow.tsx."),
  O("A one-tap action of your own", "built", "sheet", eyebrow="The rail", title="A one-tap action of your own", fork="F4",
    source="components/dashboard/QuickActionsPanel.tsx:332 and pages/Notifications.tsx:1705 (legacy); built by the founder's ruling 2026-09-05",
    body=[["field","What it does","Reorder Öküzgözü to par"],["sect","Runs"],
          ["chips",["When I tap it",True],["On a threshold",False],["On a schedule",False]],
          ["fact","Threshold","2 bottles left · 6 is par"],["fact","Then","a draft order to Kavaklıdere — you hold to send"],
          ["note","One tap runs the act; the seal still sits on any write it makes (ADR 0112, ADR 0125)."],["btns",["Put it on the rail",True]]],
    footer="An action names what it will do before it does it.",
    why="A person's own act is one object on the rail; the rail stays producer-defined otherwise. BUILT 2026-09-06 (packet 2): pages/dashboard/next/OneTapSheet.tsx — write, change and take off the rail against POST/PUT/DELETE /one-tap-actions; the mark carries over, the colour theme does not (one chromatic colour), and the two unbuilt triggers say so."),
  O("Add an important date", "retire", None, source="components/dashboard/AddImportantDateModal.tsx:125",
    acts="Add events, deadlines and reminders: title, date, time, type, colour, notes",
    went="The calendar's entry sheet — the house has one day-book (ADR 0111)."),
  O("Edit a quick action", "retire", None, source="components/dashboard/QuickActionsPanel.tsx:332", fork="F4",
    acts="A person-authored quick action: title, description, URL, icon, colour theme",
    went="One-tap actions moved to the dashboard rail (OneTapPanel). A person's own action is built as the sheet drawn above (decided 2026-09-05, F4)."),
  O("Daily sales report (a day)", "retire", None, source="pages/Dashboard.tsx:1414",
    acts="Everything that happened on one day: spend, bottles sold, top seller, events",
    went="DayDetail expands in place under the sales calendar (pages/dashboard/next/SalesCalendar.tsx:217)."),
])

# ─────────────────────────────────────────── orders ──
P("/orders", "orders", "orders.md",
  "Three house overlays are built. The manual 'new order' sheet and its guard are owed — the founder chose the sheet as the manual entry (F5, 2026-09-05); six legacy modals retire into what is built; two dead files are deleted.",
  flag="mudavym_design_orders", overlays=[
  O("What was agreed", "built", "panel", eyebrow="New agreement", title="What was agreed",
    source="pages/orders/next/AgreementSheet.tsx:349",
    body=[["two",["Wine","Öküzgözü 2022 · Kavaklıdere"],["Vendor","Kavaklıdere"]],
          ["two",["Quantity","5"],["Order unit","case · 12 bottles"]],
          ["two",["Agreed price","₺ 2,400.00"],["Price unit","per case"]],
          ["field","Currency","TRY"],
          ["note","An agreed price states its unit (ADR 0119). <b>unit not stated</b> is written down as exactly that."],
          ["btns",["Write it down",True]]],
    why="A question the house asks before it writes a price."),
  O("Make this order repeat", "built", "panel", eyebrow="New recurrence", title="Make this order repeat",
    source="pages/orders/next/RecurrenceSheet.tsx:222",
    body=[["field","How often","Every month"],["field","On which day","the 1st — 1 to 28, so that every month has one"],
          ["field","Starting from","1 Oct 2026"],["fact","What this will ask for","5 cases Öküzgözü 2022 · ₺ 2,400 per case"],
          ["btns",["Set a recurring order",True],["Pause it"],["End it"]]],
    why="A commitment about the future — a question, answered once."),
  O("Vendor answers", "built", "sheet", wide=True, eyebrow="Vendor answers", title="Öküzgözü 2022", action="Previous · Next",
    source="pages/orders/next/ResponsesSheet.tsx:353",
    body=[["sect","Answer 2 of 3 · Kavaklıdere · 3 Sept"],
          ["text","We can deliver Thursday. The 2022 is ₺2,400 per case and we can hold that until the 15th. — Hasan"],
          ["fact","Read as","a confirmation · price unchanged"],
          ["sect","Why this order is rejected"],["field","","In words: what is wrong with this answer",True],
          ["hold","Hold to reject"]],
    footer="Left and right arrows step through the answers.",
    why="One order's correspondence is one object, read at 640 because letters are prose — the wide case ADR 0112 anticipated."),
  O("A new order", "built", "sheet", eyebrow="The order book", title="A new order", fork="F5",
    source="BUILT 2026-09-06 as pages/orders/next/NewOrderSheet.tsx (was pages/orders/CreateOrderModal.tsx:123 and pages/Orders.tsx:2903)",
    body=[["field","","Search the register — Öküzgözü, Banfi, gin…",True],["sect","Lines"],
          ["item","Öküzgözü 2022 · Kavaklıdere","5 cases · ₺ 2,400 per case",False,"₺ 12,000"],
          ["item","Chianti Classico 2021 · Banfi","2 cases · $ 210 per case",False,"$ 420"],
          ["fact","Vendor","Kavaklıdere"],
          ["note","Price and unit come from the agreement on the vendor's row; a line without one asks first (<b>What was agreed</b>)."]],
    footer="Nothing is sent by saving a draft.",
    why="The order being written is one object. Decided 2026-09-05 (F5): this sheet is the manual entry; owed on OrdersNext. BUILT 2026-09-06 (packet 2): several lines, one POST per line because CreateOrderDto carries one, and a per-line account of what landed. The agreed price is OFFERED grey from the NEW route GET /procurement/last-agreement, never applied."),
  O("Add a vendor first", "built", "panel", eyebrow="Before an order", title="Add a vendor to place orders",
    source="BUILT 2026-09-06 as pages/orders/next/VendorFirstPanel.tsx (was components/orders/OrderGuardModal.tsx:27)",
    body=[["quiet","An order needs someone to send it to. There is no vendor in the book yet."],
          ["btns",["Go to Providers",True],["Back to the order"]]],
    why="A question with two answers. Travels with the new-order sheet. BUILT 2026-09-06: reached before the composer opens on an empty vendor list, and again on the gateway's 403 no_vendors, where it says the order was NOT placed. An unreadable vendor list never opens it."),
  O("Wine config", "retire", None, source="pages/Orders.tsx:2903",
    acts="Order unit (bottles/cases), bottles per case, custom price vs 'ask provider', providers to contact",
    went="What was agreed (unit · price · currency) on the ledger row."),
  O("Reject this order?", "retire", None, source="pages/Orders.tsx:3359 (SealedRejectDie)",
    acts="A confirmation naming the wine before a rejection", went="Vendor answers — 'Hold to reject', with the reason in words."),
  O("Provider comms thread", "retire", None, source="components/orders/CommsThreadDrawer.tsx:436", fork="F4",
    acts="One order's thread: DKIM state, Resume/Pause AI, a manual reply in the same email thread",
    went="Vendor answers reads the thread; the composer writes. <b>Pause / resume the AI on this thread</b> becomes a control in the responses sheet's head (decided 2026-09-05, F4) — a switch, not an overlay."),
  O("AI-detected deal", "retire", None, source="components/orders/DealApprovalModal.tsx:45",
    acts="A deal read from a vendor's mail: quantity, total, terms, a low-confidence warning; Decline / Ask for more",
    went="An answer kind inside Vendor answers; 'what the AI read' survives as the provenance line."),
  O("Active drafts", "retire", None, source="components/orders/ActiveConversationsPanel.tsx:65",
    acts="The AI's pending drafts: view, quick approve, discard", went="/communications lists threads with their drafts; approval is the panel drawn there."),
  O("AI draft ready", "retire", None, source="components/orders/DraftEmailApprovalPanel.tsx:130",
    acts="Review, edit and send the reply the house drafted", went="Drawn on /communications as <b>The house's reply, drafted</b> (owed)."),
  O("Recurring order (page)", "delete", None, source="pages/RecurringOrders.tsx:530 — nobody imports the page",
    acts="Automated reordering with a negotiated price, deal duration and manager override",
    went="Recurrence lives on the order (Make this order repeat). Delete."),
  O("Record an auction purchase", "retire", None, source="components/orders/AuctionPurchaseModal.tsx:133 — nobody imports it", fork="F4",
    acts="Hammer price, buyer's premium, lot number, into inventory", went="Built as a fourth start of <b>Carry this bottle</b> on /inventory — 'An auction lot' (decided 2026-09-05, F4). The dead file is deleted once that start exists."),
])

# ─────────────────────────────────────────── receiving · door · receipts · documents ──
P("/receiving · /receiving/:orderId/door", "receiving", "receiving.md",
  "No overlays. The door is six points on one page; a sealed step is a panel-shaped section inside the page, not a portal (DoorNext.tsx:697 declares a local Panel).",
  flag="mudavym_design_receiving · mudavym_design_receiving_door", overlays=[])
P("/receipts", "receipts", "receipts.md",
  "No overlays. Editable-and-confirmable in one step wants no dialog; SwipeToConfirm is inline.",
  flag="mudavym_design_receipts", overlays=[])
P("/documents/:id", "document", "documents-reports.md",
  "No overlays. CanonicalSheet is a page section, not a portal.", flag="mudavym_design_document", overlays=[])

# ─────────────────────────────────────────── inventory ──
P("/inventory", "inventory", "inventory.md",
  "The one page whose flag turns on nothing new: legacy and next are the same component (App.tsx:311), so its eight fixed-inset modals are live inside a house-flagged page today. Seven migrate; one retires to /receipts.",
  flag="mudavym_design_inventory", overlays=[
  O("Carry this bottle", "migrate", "sheet", eyebrow="The register", title="Carry this bottle",
    source="components/inventory/AddWineToInventoryModal.tsx:253 (opened at InventoryCommandPage.tsx:1438)",
    body=[["sect","Start from"],["item","The library","search the 4,120 bottles the house knows",True],
          ["item","A label photo","the reader names it; you confirm"],["item","A menu scan","many at once"],
          ["field","","Search the library — Öküzgözü, Banfi, Talisker…",True],
          ["two",["Initial quantity","12 bottles"],["Cost per bottle","₺ 190.00"]],
          ["two",["Vendor","Kavaklıdere"],["Zone","Cellar · rack B"]],
          ["btns",["Carry it",True]]],
    footer="A house item exists only through 'carry this' (ADR 0115). One component, shared with /cellar.",
    why="One bottle entering the book is one object; three ways to start, one sheet."),
  O("Carry this bottle · an auction lot", "owed", "sheet", eyebrow="The register", title="Carry this bottle", fork="F4",
    source="components/orders/AuctionPurchaseModal.tsx:133 (legacy, unreachable); built by the founder's ruling 2026-09-05 as a start of the carry sheet",
    body=[["sect","Start from"],["item","The library","",False],["item","A label photo",""],["item","A menu scan",""],["item","An auction lot","hammer price and premium make the cost",True],
          ["two",["Auction house","Sotheby's"],["Lot","118"]],["two",["Hammer price","$ 1,900"],["Buyer's premium","25% · $ 475"]],
          ["fact","Cost per bottle","$ 395.83 · 6 bottles · written to the lot"],["two",["Auction date","28 Aug 2026"],["Zone","Cellar · rack A"]],
          ["btns",["Carry it",True]]],
    footer="A lot's cost is the hammer plus the premium; the ledger keeps both (ADR 0070).",
    why="The same sheet, a fourth start: an auction bottle is still one bottle entering the book."),
  O("Place 14 bottles by their zones?", "migrate", "panel", eyebrow="Auto-locate · preview", title="Place 14 bottles by their zones?",
    source="components/inventory/AutoLocatePreviewModal.tsx:70",
    body=[["table",["Bottle","Proposed zone","Score","Why"],
           [["Öküzgözü 2022","Cellar · rack B","0.92","same producer shelved here"],
            ["Talisker 10","Bar · back shelf","0.81","spirits zone, room left"],
            ["Efes Pilsen","Walk-in · door","0.77","beer, kept cold"]]],
          ["fact","Skipped","3 · no zone matched"],["chips",["Include bottles already placed",False]],
          ["btns",["Place them",True],["Leave them"]]],
    why="A question about a batch. Bulk, so no wax — the plain die."),
  O("A delivery without an order", "migrate", "sheet", wide=True, eyebrow="Receiving", title="A delivery without an order", fork="F3",
    source="components/inventory/ManualReceiptWorkspace.tsx:234",
    body=[["two",["Vendor","Sevilen"],["Invoice or reference","INV-4471"]],["field","Default zone for new lines","Cellar · rack C"],
          ["field","","Search the library to add a line…",True],["sect","Lines"],
          ["item","Sevilen Kalecik Karası 2021","6 bottles · ₺ 240.00",False,"₺ 1,440"],
          ["item","Free sample · Sevilen Blanc de Noir","2 bottles · ₺ 0.00 (sample)",False,"₺ 0"],
          ["quiet","Stock that arrived without a purchase order — including free samples."],["btns",["Record the delivery",True]]],
    why="Lines read as a table; 640 like the composer. Decided 2026-09-05 (F3): a sheet here, not a route."),
  O("POS buttons and stock", "migrate", "sheet", eyebrow="The queue", title="POS buttons and stock",
    source="components/inventory/PosMappingPanel.tsx:294",
    body=[["quiet","12 POS lines have arrived and moved no stock. 41 units unaccounted for across 4 buttons — a floor, not the total."],
          ["sect","Öküzgözü glass · 27 sales"],["btns",["One glass",True],["One bottle"],["Not this"]],
          ["sect","Efes 50cl · 9 sales"],["btns",["One bottle",True],["Not this"]]],
    footer="No inventory row matched 'Rakı Yeni' — carry the bottle first.",
    why="One queue, worked line by line, the register still visible beneath."),
  O("Write off 6 bottles?", "migrate", "panel", seal=True, eyebrow="Öküzgözü 2022 · Kavaklıdere", title="Write off 6 bottles?",
    source="components/inventory/RemoveFromInventoryModal.tsx:121",
    body=[["fact","On-hand value","₺ 1,140.00 leaves the book"],["field","Reason","Broken in transit — 2 Sept delivery"],
          ["quiet","Keeps the bottle in the library — carry it again anytime."],["hold","Hold to write it off"]],
    why="A ledger write is a real commitment — wax."),
  O("The zones", "migrate", "sheet", eyebrow="Cellar floor", title="The zones",
    source="components/inventory/StorageLocationManager.tsx:327",
    body=[["item","Cellar · rack A","capacity 96 · 88 bottles"],["item","Cellar · rack B","capacity 96 · 61 bottles"],
          ["item","Bar · back shelf","capacity not recorded · 24 bottles"],["item","Walk-in · door","12 bottles"],
          ["btns",["Add a zone"]],["quiet","Drag to reorder. A zone holding bottles cannot be deleted until they are moved."]],
    footer="Zones are confirmed on the cellar floor first (2026-09-04) — this is that same list, opened from /inventory.",
    why="The zones are one object the house owns."),
  O("Spot count", "migrate", "sheet", seal=True, eyebrow="Öküzgözü 2022 · Cellar · rack B", title="Spot count",
    source="pages/inventory/command/SpotCountPanel.tsx:210 (opened from RowExpansion.tsx:384)",
    body=[["two",["Counted","9"],["On the book","11"]],["fact","Difference","−2 bottles"],
          ["field","","Why, if you know — e.g. two poured for a tasting, unrecorded",True],["hold","Hold to record the count"]],
    footer="The count writes a correction; the book keeps both figures.",
    why="Opened from the row expander; one bottle's count is one record."),
  O("Receipt record", "retire", None, source="pages/inventory/command/ReceivingWorkspace.tsx:376",
    acts="Ordered · shipped · invoiced · accepted per line, agreed vs invoice price, credit due, a line not on the invoice",
    went="/receipts is the receipts desk (ReceiptsNext). /inventory links there and never overlays it."),
])

# ─────────────────────────────────────────── cellar ──
P("/cellar · /wines · /beer · /whiskey · /cocktails · /spirits · /non-alcoholic · /soft-drinks", "cellar", "wines.md",
  "The old library added a bottle through six modals and a scanner. The register keeps one — 'carry this bottle', shared with /inventory — plus two panels for the reader's questions. The register still mounts one legacy modal today.",
  flag="mudavym_design_cellar", overlays=[
  O("Carry these bottles (from a menu scan)", "migrate", "sheet", eyebrow="The register", title="Carry these bottles",
    source="pages/cellar/next/WineRegister.tsx imports components/wines/MenuScannerModal.tsx:21 (legacy, fixed-inset)",
    body=[["sect","From the menu scan · 9 found"],
          ["item","Öküzgözü 2022 · Kavaklıdere","read with confidence 0.91",True],
          ["item","Boğazkere 2021 · Kavaklıdere","0.88",True],
          ["item","Chianti Classico 2021 · Banfi","0.74 — check the producer"],
          ["btns",["Carry the 8 I ticked",True]]],
    footer="The detection half is real; the approve half wrote nothing before (WineRegister.tsx:32-47).",
    why="The same sheet as /inventory's, opened at its 'menu scan' start."),
  O("Is this the bottle?", "owed", "panel", eyebrow="The label reader", title="Is this the bottle?",
    source="components/wines/WineValidationModal.tsx:162 · components/wines/AddWineModal.tsx:148 ('Wine detected')",
    body=[["two",["Name","Öküzgözü"],["Producer","Kavaklıdere"]],["two",["Vintage","2022"],["Type","Red"]],
          ["two",["Region","Elazığ"],["Grape","Öküzgözü"]],
          ["note","The reader is sure of the producer and unsure of the vintage — check the <b>2</b> before you confirm."],
          ["btns",["Yes, carry it",True],["Fix a field"],["Not this bottle"]]],
    why="A question the reader must answer before anything is written."),
  O("Photograph the label", "target", "panel", eyebrow="Camera", title="Photograph the label",
    source="components/scanner/CameraCapture.tsx:607 — also mounted by /get-started and the orders scanner",
    body=[["frame","viewfinder"],["quiet","Hold the bottle so the label fills the frame."],
          ["btns",["Take the photo",True],["Upload a file instead"]]],
    why="A step answered once; the page stays dimmed beneath."),
  O("Wine detail", "retire", None, source="pages/WineLibrary.tsx:1297",
    acts="Country and region, grape, vintage, stock against threshold; add to inventory, reorder, remove",
    went="The register row expands in place (sketch 095 — the house pattern for ledger tables)."),
  O("Reorder wine", "retire", None, source="pages/WineLibrary.tsx:1486",
    acts="Quantity, custom price vs 'ask provider', providers, notes, auto-reorder frequency",
    went="An order is written on /orders (What was agreed · Make this order repeat)."),
  O("How to add (chooser)", "retire", None, source="components/wines/AddWineSelectionModal.tsx:33",
    acts="Single wine · Menu scanner · Receive a delivery · Spreadsheet", went="The carry sheet's 'Start from'."),
  O("Add wine (label photo)", "retire", None, source="components/wines/AddWineModal.tsx:148",
    acts="Upload a label, the AI reads it, detected fields", went="Carry this bottle + Is this the bottle?"),
  O("Add to inventory from the library", "retire", None, source="components/wines/AddToInventoryFromLibraryModal.tsx:498",
    acts="Quick add; already in inventory → add stock or a separate entry; presets, cost, providers", went="Carry this bottle."),
  O("Dev: manual wine entry", "delete", None, source="components/wines/DevManualWineEntry.tsx:330",
    acts="Keyboard rapid entry for developers", went="Dev-only. Delete, or move under /dev-sandbox."),
  O("Dev: label test photos", "delete", None, source="components/wines/DevWinePhotoUpload.tsx:106",
    acts="'YOLOv8 + OCR detection — programmer access only'", went="Dev-only. Delete."),
  O("Add wine (unified chooser)", "delete", None, source="components/wines/AddWineUnifiedModal.tsx:53 — nobody imports it",
    acts="Choose how to add wines", went="Dead code. Delete."),
  O("Wine research queue", "delete", None, source="components/wines/WineResearchQueue.tsx:225 — nobody imports it",
    acts="Queue unknown wines for research", went="Dead code. Delete."),
])

# ─────────────────────────────────────────── providers ──
P("/providers", "providers", "providers.md",
  "The twin sheet is built and carries the vendor's terms. Adding a vendor is owed: the catalogue search, the custom vendor and the duplicate check are one sheet and one question.",
  flag="mudavym_design_providers", overlays=[
  O("The vendor's twin", "built", "sheet", eyebrow="Wine distributor", title="Kavaklıdere",
    source="pages/providers/next/TwinSheet.tsx:68",
    body=[["sect","What the platform has learned"],["fact","Contact","Hasan Demir"],["fact","Phone","+90 312 000 00 00"],
          ["fact","Lead time","4 days · from 11 deliveries"],["fact","Payment terms","Net 30 · written 2 Sept by Ayşe"],
          ["fact","Minimum order","₺ 5,000"],["fact","Regions","Ankara · Antalya"],["fact","Last contact","3 Sept · a reply on order 118"]],
    footer="Terms sit on the vendor's row with a provenance per field (ADR 0116).",
    why="One vendor, opened from the list you can still see."),
  O("A new vendor", "owed", "sheet", eyebrow="The book of vendors", title="A new vendor",
    source="components/providers/AddProviderModal.tsx:361 (+ Add Provider Type :629) · components/providers/VendorSearchModal.tsx:161",
    body=[["field","","Search the catalogue — Sevilen",False],["sect","From the catalogue · 2 found"],
          ["item","Sevilen Şarapları","İzmir · importer and distributor · verified",True],["item","Sevilen US Imports","New Jersey · importer"],
          ["sect","Or a vendor of your own"],["two",["Name","Premium Wine Distributors",True],["Contact","First and last name",True]],
          ["two",["Phone","",True],["Email","",True]],["field","Address","Start typing the address…",True],
          ["btns",["Add to the book",True]]],
    footer="Terms are written on the vendor's row afterwards, each with its provenance.",
    why="The vendor being added is one object; the old page split it across three modals."),
  O("A vendor you already have?", "owed", "panel", eyebrow="Possible duplicate", title="This looks like a vendor already in the book",
    source="components/providers/VendorMatchModal.tsx:108",
    body=[["item","Kavaklıdere","in your providers · 14 orders",True],["item","Kavaklidere Şarapları (new)","same phone, same city"],
          ["btns",["Use the one on file",True],["Keep both — they are different"]]],
    why="A question with two answers before a write."),
  O("Edit provider", "retire", None, source="components/providers/EditProviderModal.tsx:678",
    acts="Rating, type, terms, minimum order, contact, recent orders", went="The twin sheet's edit half; terms on the row."),
  O("Send message", "retire", None, source="components/providers/SendMessageSlideOver.tsx:319",
    acts="Email or SMS from a template", went="The composer (letters); the text sender is ADR 0121."),
  O("Provider card", "retire", None, source="pages/Providers.tsx:1355",
    acts="Email, website, portfolio, address, contacts, regions; favourite, edit, remove, call", went="The twin sheet."),
  O("Add provider type", "retire", None, source="components/providers/AddProviderModal.tsx:629",
    acts="A custom business type with an icon", went="A field inside the new-vendor sheet."),
])

# ─────────────────────────────────────────── communications ──
P("/communications", "communications", "communications.md",
  "The composer and the template library are built at 640. Eight legacy modals retire with the two builders (ADR 0118). One act is owed: approving a reply the house drafted.",
  flag="mudavym_design_communications", overlays=[
  O("A letter from the house", "built", "sheet", wide=True, seal=True, eyebrow="The house writes", title="A letter from the house",
    source="pages/communications/next/Compose/ComposeSheet.tsx:209",
    body=[["sect","Start from"],["chips",["A blank letter",True],["Something the house noticed",False]],
          ["two",["To","Hasan Demir · Kavaklıdere"],["From","orders@meyhanesim.mudavym.com"]],
          ["field","Subject","Order 118 — delivery Thursday"],
          ["text","Hasan Bey, thank you for confirming Thursday. Five cases of the 2022 at ₺2,400 per case, held to the 15th — we will take it. Ayşe"],
          ["hold","Hold to send"]],
    footer="Nothing was queued and nothing was sent.",
    why="A letter is prose; 440 minus padding is ~46 characters — the one wide case ADR 0112 anticipated."),
  O("Templates", "built", "sheet", wide=True, eyebrow="House letters", title="Templates",
    source="pages/communications/next/TemplateSheet.tsx:132",
    body=[["btns",["Write a new template",True]],["sect","Start from something the house noticed"],
          ["item","Öküzgözü sold 41% above its 30-day pace","reports · 2 Sept · the engine's sentence, with its provenance"],
          ["sect","On file · 4"],["item","Delivery confirmation","used 12 times · last 3 Sept"],["item","Price check","used 3 times"],
          ["two",["Name","Delivery confirmation"],["Purpose","Confirm a delivery day with the vendor"]],
          ["field","Subject","Order {{order}} — delivery {{day}}"]],
    why="The library is one object; a template is edited in place inside it."),
  O("The house's reply, drafted", "owed", "panel", seal=True, eyebrow="Drafted · order 118 · round 2", title="The house's reply, drafted",
    source="components/orders/DraftEmailApprovalPanel.tsx:130 (legacy, on /orders)",
    body=[["fact","To","Hasan Demir · Kavaklıdere"],["field","Subject","Re: Order 118 — five cases"],
          ["text","Thank you — five cases of the 2022 at ₺2,400 per case, delivery Thursday. Please confirm the hold to the 15th."],
          ["quiet","The Mudavym disclaimer is appended and cannot be removed."],
          ["hold","Hold to send"],["btns",["Edit first"],["Discard"]]],
    footer="A draft never looks sent (prc-02).",
    why="A question with the seal — nothing reaches a vendor without a person's hold (ADR 0118)."),
  O("Gmail template builder", "retire", None, source="components/documents/GmailTemplateBuilder.tsx:852",
    acts="The old email builder: subject, to, cc, bcc, blocks, categories", went="The composer and the template library (ADR 0118 retires both builders)."),
  O("SMS template builder", "retire", None, source="components/documents/SMSTemplateBuilder.tsx:423",
    acts="SMS templates with variables", went="The house's text sender (ADR 0121, research)."),
  O("Select report type", "retire", None, source="components/communications/ReportTypeModal.tsx:122",
    acts="Pick a report type and a template for a report email", went="'Start from something the house noticed'."),
  O("Create category", "retire", None, source="components/documents/NewCategoryModal.tsx:112",
    acts="A template category with icon and colour", went="A template's Purpose."),
  O("Switch component type", "retire", None, source="components/documents/VariationSelectorModal.tsx:124",
    acts="Convert a builder block to another format", went="Builder-internal; goes with the builder."),
  O("Quick Gmail send", "retire", None, source="components/emails/QuickGmailModal.tsx:238",
    acts="Send from a saved template or compose custom; CC/BCC", went="The composer."),
  O("Send email (saved template)", "retire", None, source="components/documents/SavedTemplates.tsx:580",
    acts="Recipient, subject, 'Email sent!'", went="The composer; the seal on the subdomain, an undo window on the house's own mailbox."),
  O("Send SMS (saved template)", "retire", None, source="components/documents/SavedSMSTemplates.tsx:619",
    acts="Recipient phone, preview, 'SMS sent!'", went="The text sender (ADR 0121)."),
  O("Template library (new template · sent)", "delete", None, source="components/documents/TemplateLibrary.tsx:606 and :945 — nobody imports it",
    acts="'Choose how you'd like to start' and a 'Sent!' confirmation", went="Dead code. Delete."),
])

# ─────────────────────────────────────────── calendar ──
P("/calendar", "calendar", "calendar.md",
  "The entry sheet is built and says a failed save in words. The meeting-note prompt is owed as a panel; the ⌘K day-book assistant (ADR 0111) is planned as a panel.",
  flag="mudavym_design_calendar", overlays=[
  O("The entry", "built", "sheet", eyebrow="The entry", title="Kavaklıdere delivery",
    source="pages/calendar/next/EventSheet.tsx:230",
    body=[["chips",["Delivery",True],["Meeting",False],["Shift",False],["Reminder",False],["custom",False]],
          ["field","Title","Kavaklıdere delivery"],["two",["Date","Thu 11 Sept"],["All day","No"]],
          ["two",["Starts","10:00"],["Ends","11:00"]],["field","Repeat","Does not repeat"],["field","Status","Expected"],
          ["alert","Not saved","The gateway refused the dates: 'Ends' is before 'Starts'. The entry is unchanged."],
          ["btns",["Keep it",True],["Remove"]]],
    why="One entry is one object; the month stays readable beneath."),
  O("A note from this meeting?", "owed", "panel", eyebrow="Tuesday's meeting · Kavaklıdere tasting", title="A note from this meeting?",
    source="pages/calendar/MeetingMemoPrompt.tsx:109",
    body=[["field","","What was said, what was decided…",True],
          ["two",["Filed under","Vendors · Kavaklıdere"],["Document type","Meeting note"]],
          ["quiet","Obsidian sync — coming soon."],["btns",["Save the note",True],["Later"],["Skip"]]],
    why="A question asked once, after the meeting ends (ADR 0111 unifies meetings, notes and reminders)."),
  O("Ask the day-book", "target", "panel", eyebrow="⌘K on the calendar", title="Ask the day-book",
    source="sketch 098 · ADR 0111 (planned, not built)",
    body=[["field","","Move Thursday's delivery to Friday…",True],["sect","It would do"],
          ["item","Move 'Kavaklıdere delivery' to Fri 12 Sept, 10:00","one entry changes"],
          ["item","Tell Hasan Demir","a letter, drafted — you hold to send"],
          ["btns",["Do it",True],["Not that"]]],
    footer="The assistant proposes; the seal applies (ADR 0113).",
    why="A question — the palette's shape, scoped to one page."),
  O("Event modal", "retire", None, source="pages/calendar/EventModal.tsx:1511 (1,593 lines)",
    acts="The old event editor", went="The entry sheet."),
  O("Mobile sidebar scrim", "none", None, source="pages/calendar/CalendarPage.tsx:597",
    acts="Dims the page behind the calendar's mobile sidebar", went="Paint only — not a shape."),
])

# ─────────────────────────────────────────── reports ──
P("/reports", "reports", "reports.md",
  "Ask the book is built; the insight palette and the KPI spotlight retire into it and into cuttings that expand in place. Seven dashboard-builder modals are dead code.",
  flag="mudavym_design_reports", overlays=[
  O("Ask the book", "built", "panel", title="Ask the book", source="pages/reports/next/AskTheBook.tsx:94",
    body=[["field","","Search what the engine has already said…",True],["sect","The register · 2 match"],
          ["item","Öküzgözü sold 41% above its 30-day pace","2 Sept · velocity · confidence high"],
          ["item","Kavaklıdere's price is 6% under its 30-day average","1 Sept · market price"],
          ["quiet","The book holds no sentence about 'labour' for this house — nothing is invented to fill the gap (ADR 0020)."]],
    why="A question; the answer is only what the engine already said."),
  O("Insight palette", "retire", None, source="components/reports/organisms/AICommandPalette.tsx:77",
    acts="Search insights (⌘K)", went="Ask the book."),
  O("KPI spotlight", "retire", None, source="components/reports/molecules/KPISpotlightView.tsx:507",
    acts="Detailed breakdown of one KPI", went="A cutting is a question and expands in place (sketch 096)."),
  O("Arrange charts", "delete", None, source="components/reports/ChartArrangementModal.tsx:108 — nobody imports it",
    acts="Drag to reorder, toggle visibility, reset", went="The sheet is arranged from the keyboard (sketch 096). Delete."),
  O("Configure chart", "delete", None, source="components/reports/ChartConfigModal.tsx:104 — reached only from dead files",
    acts="Data source, chart type, size", went="Dead code. Delete."),
  O("Add widget", "delete", None, source="components/reports/DashboardGrid.tsx:361 — nobody imports it", acts="Choose a widget type", went="Dead code. Delete."),
  O("Edit layout", "delete", None, source="components/reports/EditLayoutPanel.tsx:223 — nobody imports it", acts="Layout presets, edit mode", went="Dead code. Delete."),
  O("Widget selector", "delete", None, source="components/reports/WidgetSelector.tsx:119 — nobody imports it", acts="Search widget options", went="Dead code. Delete."),
  O("Choose KPI metric · Add KPI card", "delete", None, source="components/reports/organisms/KPISection.tsx:148 and :217 — nobody imports it",
    acts="Pick what a KPI card displays", went="Dead code. Delete."),
  O("Preview overlay", "delete", None, source="components/reports/preview/PreviewOverlay.tsx:73 — nobody imports it", acts="Full-screen preview", went="Dead code. Delete."),
])

# ─────────────────────────────────────────── documents-reports ──
P("/documents-reports", "documents-reports", "documents-reports.md",
  "No overlay on the rebuilt page: the Sorting Office's reading pane is the detail surface (Direction D). One legacy preview retires.",
  flag="mudavym_design_documents_reports", overlays=[
  O("Document preview", "retire", None, source="pages/DocumentsPage.tsx:985",
    acts="Preview a report: download, print, email, copy link, delete", went="The reading pane."),
])

# ─────────────────────────────────────────── notifications ──
P("/notifications", "notifications", "notifications.md",
  "The rebuilt page opens a row in place and has no overlay of its own. The ratified rule is drawn: a one-click approval from the bell opens the panel first.",
  flag="mudavym_design_notifications", overlays=[
  O("Approve from the bell", "owed", "panel", seal=True, eyebrow="From the bell · order 118", title="Approve the Kavaklıdere order?",
    source="ADR 0112, founder answer 2026-09-04 — 'a one-click approval from the bell opens the panel first'; not built",
    body=[["fact","Lines","5 cases Öküzgözü 2022"],["fact","Agreed","₺ 2,400 per case · ₺ 12,000"],["fact","Delivery","Thu 11 Sept"],
          ["hold","Hold to approve"]],
    footer="The seal never sits in a popover; the bell hands off to this panel.",
    why="The bell is a menu; a commitment needs a room that cannot be dismissed by accident."),
  O("Notification detail", "retire", None, source="pages/Notifications.tsx:1513",
    acts="'Gathering context…', suggested next steps, review and approve a draft, take action",
    went="The row expands in place (`.nt-expand`); a sealed act opens the panel above."),
  O("Create one-tap action", "retire", None, source="pages/Notifications.tsx:1705", fork="F4",
    acts="Categories, quick-start templates, a trigger: time-based, threshold or manual",
    went="One-tap actions moved to the dashboard rail; a person-authored action is built as <b>A one-tap action of your own</b> on / (decided 2026-09-05, F4)."),
  O("Add vendor deadline", "delete", None, source="components/notifications/VendorDeadlineSettings.tsx:184 — nobody imports it",
    acts="A vendor's order cutoff by weekday and time, hours-before notice", went="Cutoffs live in vendor terms (ADR 0116). Delete."),
])

# ─────────────────────────────────────────── recommendations ──
P("/recommendations", "recommendations", "recommendations.md",
  "The docket dismisses inline and schedules through a route. The old assignee picker is rebuilt as the popover drawn here — the fifth F4 act, confirmed by the founder 2026-09-06.",
  flag="mudavym_design_recommendations", overlays=[
  O("Who takes this?", "owed", "popover", eyebrow="Assign", title="Who takes this?", fork="F4",
    source="pages/Recommendations.tsx:980 — not on the rebuilt docket",
    body=[["item","Mehmet Kaya","bar",True],["item","Elif Şahin","floor"],["item","Nobody — clear it"]],
    why="A choice from a short list, anchored to the entry's control. **Confirmed by the founder 2026-09-06**: the fifth F4 act is built like the other four — the docket keeps assignment, and the roster it reads is the team's."),
])

# ─────────────────────────────────────────── settings ──
P("/settings", "settings", "settings.md",
  "The four location dialogs migrated on 2026-09-04. Two shared dialogs still render legacy inside the rebuilt page — both are questions.",
  flag="mudavym_design_settings", overlays=[
  O("Add a location", "built", "sheet", eyebrow="The locations", title="Add New Location",
    source="components/locations/AddLocationDialog.tsx:185 (opened at pages/settings/next/LocationsSection.tsx)",
    body=[["field","Location name","Meyhane Sim · Lara"],["field","Chain / Brand","Meyhane Sim"],["field","Country","Türkiye"],
          ["field","Street address","Lara Cd. 112"],["two",["City","Antalya"],["Postal","07230"]],["field","Phone","",True],
          ["btns",["Add the location",True]],["quiet","Not added — nothing is written until you do."]],
    why="One location being written."),
  O("New chain", "built", "sheet", eyebrow="The locations", title="New chain", source="components/locations/CreateChainDialog.tsx:121",
    body=[["field","Chain name","Meyhane Sim"],["sect","Add locations to this chain"],
          ["chips",["Kaleiçi",True],["Lara",True],["The Grill Co.",False]],["btns",["Create the chain",True]]],
    why="One chain being written."),
  O("Edit location", "built", "sheet", eyebrow="The locations", title="Edit location", source="components/locations/EditLocationChainDialog.tsx:134",
    body=[["two",["Name","Meyhane Sim · Lara"],["City","Antalya"]],["field","Chain","Meyhane Sim"],
          ["note","Moving from <b>Standalone</b> — this places Lara under Meyhane Sim in the branch switcher."],["btns",["Save",True]]],
    why="One location's record."),
  O("Add to Meyhane Sim", "built", "panel", eyebrow="The locations", title="Add to Meyhane Sim", source="components/locations/AssignToChainDialog.tsx:106",
    body=[["quiet","Pick existing locations to move into this chain."],["chips",["Lara",True],["Kaş",False]],
          ["btns",["Add them",True],["Create a brand-new location instead"]]],
    why="A question about which."),
  O("Share this with the engine?", "migrate", "panel", eyebrow="Consent", title="Turn on the reading of sales?",
    source="components/settings/ConsentDialog.tsx:71 (opened from components/settings/ServicesPermissions.tsx:300)",
    body=[["sect","What gets shared"],["item","Sale lines by item and hour"],["item","Stock levels"],
          ["sect","What never leaves"],["item","Guest names, card details, staff pay"],
          ["quiet","Read the privacy notice."],["btns",["Turn it on",True],["Keep it off"]]],
    why="A question. Settings stay asserted, not sealed (2026-09-04)."),
  O("Carry your vendors to the new location?", "migrate", "panel", eyebrow="Lara · just added", title="Carry your vendors to the new location?",
    source="components/providers/BranchProviderTransferModal.tsx:109",
    body=[["chips",["Kavaklıdere",True],["Sevilen",True],["Southern Glazer's",False]],["btns",["Carry them",True],["Skip for now"]]],
    why="A question about a batch, asked once after a write."),
])

# ─────────────────────────────────────────── team ──
P("/team", "team", "team.md",
  "Eleven house overlays are built, including the wave's one named exception. The legacy desk's seven surfaces retire with it the day a house's flag turns on; certifications have no house surface (fork F4).",
  flag="mudavym_design_team", overlays=[
  O("People", "built", "sheet", eyebrow="The roster", title="People", action="Add", source="pages/team/next/RosterSheet.tsx:219",
    body=[["item","Mehmet Kaya","bar · full time · Kaleiçi"],["item","Elif Şahin","floor · part time"],
          ["item","Team member","display name not yet linked — 'links the account on signup'"]],
    why="The roster is one object."),
  O("On the roster", "built", "sheet", eyebrow="On the roster", title="Mehmet Kaya", source="pages/team/next/RosterSheet.tsx:392 (MemberSheet)",
    body=[["two",["Name","Mehmet Kaya"],["Email","mehmet@example.com"]],["two",["Phone","+90 5xx"],["Position","Bartender"]],
          ["two",["Employment","Full time"],["Home location","Kaleiçi"]],["two",["Hourly wage","₺ 180"],["Status","Active"]],
          ["field","Skills","bar, somm, closer"],["btns",["Keep them",True],["Remove"]]],
    why="One person's record."),
  O("Edit this shift", "built", "sheet", eyebrow="Shift on the schedule", title="Edit this shift", source="pages/team/next/ShiftSheet.tsx:98",
    body=[["field","Who","Mehmet Kaya"],["two",["Date","Thu 11 Sept"],["Station","Main bar"]],["two",["Start","16:00"],["End","00:30"]],
          ["field","Kind","Service"],["alert","Not removed","The shift was not removed. It is still on the schedule."],
          ["btns",["Keep it",True],["Remove"]]],
    why="One shift's record; the week stays visible beneath."),
  O("Publish this week", "built", "panel", seal=True, eyebrow="8–14 Sept", title="Publish this week", source="pages/team/next/TeamOverlays.tsx:90 (PublishPanel)",
    body=[["fact","Shifts","34 · 2 open"],["sect","Who has opened the week"],["item","Elif Şahin","yesterday"],["item","Mehmet Kaya","not yet"],
          ["field","","The week's note",True],["hold","Hold to publish"],["btns",["Not yet"]]],
    why="A commitment the whole crew sees — wax."),
  O("Copy last week", "built", "panel", seal=True, eyebrow="into 15–21 Sept", title="Copy last week", source="pages/team/next/TeamOverlays.tsx:167 (CopyWeekPanel)",
    body=[["fact","Last week","34 shifts · 6 people"],["note","Replaces what is on 15–21 Sept."],["hold","Hold to replace the week"],["btns",["Leave it"]]],
    why="A question about a batch that overwrites — the hold, because it replaces."),
  O("A note to the crew", "built", "sheet", eyebrow="On the week of 8 Sept", title="A note to the crew", source="pages/team/next/TeamOverlays.tsx:519 (CrewNoteSheet)",
    body=[["field","Note","Saturday is the Kavaklıdere tasting — Mehmet opens the bar at 15:00."],["sect","Delivered · read"],
          ["item","Elif Şahin","read 09:12"],["item","Mehmet Kaya","delivered"],["btns",["Send",True],["Cancel"]]],
    footer="Inbox and push only (2026-09-04).", why="One note with its receipts."),
  O("Time off", "built", "sheet", eyebrow="Requests on file", title="Time off", source="pages/team/next/TeamOverlays.tsx:640 (TimeOffSheet)",
    body=[["sect","Waiting on you"],["item","Elif Şahin · 20–22 Sept","family"],["btns",["Approve",True],["Deny"]],
          ["sect","Decided"],["item","Mehmet Kaya · 3 Sept","approved by Ayşe"],["btns",["File a request for someone"]],
          ["alert","Not recorded","The decision was not recorded, so the request is still where it was."]],
    why="The requests are one register."),
  O("Export the week", "built", "popover", title="Export the week", source="pages/team/next/TeamOverlays.tsx:828 (ExportPopover)",
    body=[["item","Print the floor sheet","opens the print dialog"]], why="A control's own menu."),
  O("Shift actions", "built", "popover", title="Shift actions", source="pages/team/next/WeekGrid.tsx:424",
    body=[["item","Edit shift"],["item","Duplicate onto the same day"],["item","Report a call-out"],["item","Offer cover","Cover, if this falls through"],["item","Delete shift"],
          ["alert","Did not send","The cover offer did not send. Nobody was asked."]],
    why="A row's own menu."),
  O("What changed here", "built", "sheet", eyebrow="The record", title="What changed here", source="pages/team/next/TeamRecord.tsx:273 (TrailSheet)",
    body=[["item","labor_target_pct 28 → unset","3 Sept · Ayşe · a default rendered as unset"],
          ["item","Mehmet Kaya · wage ₺160 → ₺180","1 Sept · Ayşe"],["item","Week 36 published","31 Aug · Ayşe"]],
    why="The audit trail of one record."),
  O("Invite a team member", "built", "popover", modal=True, eyebrow="The exception", title="Invite a team member",
    source="components/team/InviteTeamDialog.tsx:199 — 'Popover modal', the one exception ADR 0112 names; also opened from /get-started and /settings",
    body=[["field","Email (optional)","colleague@restaurant.com",True],["chips",["Manager",False],["Staff",True]],
          ["fact","Expires","7 days from generation · single-use"],["chips",["Add roster-only staff (no Mudavym login)",False]],
          ["btns",["Generate the code",True],["Cancel"]]],
    why="Anchored under its button like a popover, but a form that commits — so it traps focus and dims. The one exception; the studio invite reuses this component (F2, 2026-09-05)."),
  O("Certifications on file", "owed", "sheet", eyebrow="The roster · Mehmet Kaya", title="Certifications on file", fork="F4",
    source="pages/team/command/OpsRulesPanel.tsx:37 (legacy desk); team_certifications has no role or applies-to column; built by the founder's ruling 2026-09-05",
    body=[["item","Alcohol service","issued 12 Mar 2026 · expires 12 Mar 2028",True],["item","Food handler","issued 3 Jan 2025 · expires 3 Jan 2027"],
          ["alert","Expiring","Food handler expires in 120 days. The roster will say so on the shift."],
          ["sect","Add one"],["two",["Type","Fire safety"],["Issued","",True]],["field","Expires","",True],["btns",["Put it on file",True]]],
    footer="A certificate is a fact with two dates; the schedule reads the second one.",
    why="One person's certificates are one record; opened from the roster row."),
  O("Desk row menu", "retire", None, source="pages/team/command/ManagerShiftDesk.tsx:868",
    acts="Message · Edit shift · Duplicate · Delete shift · Copy last week · Re-publish", went="Shift actions, Publish this week, Copy last week."),
  O("Desk message composer", "retire", None, source="pages/team/command/ManagerShiftDesk.tsx:981", acts="A message to the crew", went="A note to the crew."),
  O("Desk confirm sheet", "retire", None, source="pages/team/command/ManagerShiftDesk.tsx:1061", acts="Confirm publish or copy", went="Publish this week · Copy last week."),
  O("Desk people sheet", "retire", None, source="pages/team/command/ManagerShiftDesk.tsx:1132", acts="People · Rules · Add", went="People (the roster sheet)."),
  O("Desk editors", "retire", None, source="pages/team/command/editors.tsx:23", acts="Shift and member editors", went="Edit this shift · On the roster."),
  O("Ops rules", "retire", None, source="pages/team/command/OpsRulesPanel.tsx:37", fork="F4",
    acts="Coverage rules (day, period, minimum staff, role) and certifications (type, issued, expires)",
    went="The first-rule form is inline on the rebuilt page (ADR 0089). <b>Certifications</b> are built as the sheet drawn above (decided 2026-09-05, F4)."),
  O("Import shift configurations", "delete", None, source="components/team/ShiftImportModal.tsx:135 — opened only from the legacy desk",
    acts="Upload CSV, Excel or JSON shift templates; the apply path was simulated (file.size / 80)", went="No import route exists. Delete with the desk."),
])

# ─────────────────────────────────────────── pages not yet rebuilt ──
P("/promotions", "promotions", "promotions.md",
  "Not rebuilt. Two legacy overlays take their shapes now so the rebuild inherits them.", rebuilt=False, overlays=[
  O("The offer", "target", "sheet", eyebrow="Sevilen · by mail · 2 Sept", title="12% off Kalecik Karası, cases of 6",
    source="pages/Promotions.tsx:336",
    body=[["fact","Ends","30 Sept"],["fact","Applies to","Kalecik Karası 2021 · 2022"],["fact","Code","SEV-KK-12"],["fact","Read with confidence","0.86"],
          ["btns",["Apply to a new order",True],["Dismiss"]]],
    footer="Offer dismissed — Undo.", why="One offer is one object."),
  O("Offer menu", "target", "popover", title="Offer", source="pages/Promotions.tsx:328",
    body=[["item","Copy code"],["item","Apply to a new order"],["item","Dismiss"]], why="A row's own menu."),
])
P("/distributors", "distributors", "distributors.md",
  "Not rebuilt. Already a right drawer — the shape was right, the primitive was not.", rebuilt=False, overlays=[
  O("Distributor detail", "target", "sheet", eyebrow="Distributor · verified by Mudavym", title="Southern Glazer's Wine & Spirits",
    source="pages/distributors/command/DistributorDrawer.tsx:125",
    body=[["sect","Contact"],["fact","Phone","+1 312 000 0000"],["fact","Email","orders@example.com"],
          ["sect","Where they can sell"],["fact","Licence territory","Illinois · Michigan"],
          ["sect","Portfolio"],["fact","Producers","Banfi · Kavaklıdere · 214 more"],
          ["sect","Data quality"],["fact","Verified","details verified by Mudavym · 2 Sept"],["btns",["Add to my providers",True]]],
    why="One distributor is one object."),
])
P("/studio/certify", "studio-certify", "studio-certify.md",
  "Not rebuilt. The same act as the team invite: it reuses the one exception component with a second opener (decided 2026-09-05, F2).", rebuilt=False, overlays=[
  O("Invite a contributor", "target", "popover", modal=True, eyebrow="Studio", title="Invite a contributor", fork="F2",
    source="pages/studio/certify/InviteDialog.tsx:106 (Radix dialog today)",
    body=[["field","Email","contributor@example.com",True],["chips",["Certified Contributor",True],["Developer",False],["Review Admin",False]],
          ["fact","Expiry","7 days (standard)"],["btns",["Generate the invite",True],["Cancel"]]],
    why="The same act as Invite a team member. Decided 2026-09-05 (F2): the same component — InviteTeamDialog's Popover modal — with a second opener; one component, however many openers, is one exception."),
])
P("/admin/health", "admin-health", "admin-health.md", "Not rebuilt. One overlay: a payload, which is a record.", rebuilt=False, overlays=[
  O("Live payload", "target", "sheet", eyebrow="Live payload from /api/v1/health/live", title="Live payload",
    source="pages/AdminHealth.tsx:226",
    body=[["mono","{ \"status\": \"ok\",\n  \"commit\": \"a26f265c\",\n  \"bootedAt\": \"2026-09-05T14:02:11Z\" }"],["fact","Fetched","14:02:19Z · 41 ms"]],
    why="One response is one object; reading it wants the page beside it."),
])
P("/get-started", "get-started", "get-started.md",
  "Not rebuilt. Mounts two overlays drawn elsewhere: Photograph the label (cellar) and Invite a team member (team).", rebuilt=False, overlays=[])

# ─────────────────────────────────────────── behaviours (research 2026-09-05) ──
# Sixteen behaviours the best products have, drawn on the house's own surfaces. Verdicts are the
# adversary's (research/E-adversary.md): KEEP / ADAPT. Nothing here is built or decided.
P("behaviours", "behaviours", None,
  "What the best products do, drawn on our surfaces. Three researchers read 72 patterns from command-first, ops-and-finance and AI-native products; an adversary judged 96 rows against the eight house rules (51 keep · 40 adapt · 5 reject) and named three things all of them missed. These sixteen survived. None is built; four of them are forks (F8–F11).",
  rebuilt=True, overlays=[
  O("Peek beside the list", "pattern", "peek", eyebrow="Order 118 · peek", title="Öküzgözü 2022 · Kavaklıdere",
    source="Linear — Peek (https://linear.app/docs/peek) · adversary A1: ADAPT, name it non-modal",
    body=[["fact","Status","Confirmed · delivery Thu"],["fact","Agreed","₺ 2,400 per case · 5 cases"],["fact","Last answer","Hasan, 3 Sept — a confirmation"],
          ["quiet","Space opens it beside the ledger; ↑ ↓ step rows; Enter promotes it to the sheet; Esc closes. No scrim, no focus trap — the list stays live."]],
    footer="Non-modal. Never a form, never the seal.",
    why="For the 80% of glance-then-move-on lookups, a sheet is too much and a hover card too little. It is not a fourth shape: it has no scrim and traps nothing — the non-modal class ADR 0112's carve-out allows, named (fork F8)."),
  O("The palette with pages and one argument", "pattern", "panel", title="Command palette",
    source="Raycast arguments (https://developers.raycast.com/information/lifecycle/arguments) · cmdk pages (https://dip-cmdk.mintlify.app/guides/nested-items) · adversary A3 KEEP, A4 ADAPT (cap at one argument)",
    body=[["field","","Approve",False],["sect","Approve … · 3 waiting"],
          ["item","Order 118 · Kavaklıdere · ₺ 12,000","confirmed Thursday",True,"↵"],["item","Order 121 · Sevilen · ₺ 3,120","awaiting a reply"],["item","Order 119 · Banfi · $ 420",""],
          ["quiet","↵ opens the approval panel with the seal; ⌫ or Esc steps back a page. One argument, never a form."]],
    footer="↑↓ · ↵ · ⌫ back · esc",
    why="One command box drills into a picker instead of a long tail of small popovers. The adversary's cap: a command that wants three arguments is a disguised form and belongs in a panel or a sheet."),
  O("A hover card on a referenced name", "pattern", "hover", eyebrow="Vendor", title="Kavaklıdere",
    source="GitHub hovercards (https://github.blog/changelog/2018-10-08-issue-and-pull-request-hovercards/) · Notion hover preview · adversary A15/A16 KEEP",
    body=[["fact","Terms","Net 30 · min ₺ 5,000"],["fact","Open orders","2 · ₺ 15,120"],["fact","Last contact","3 Sept"],["btns",["Open"],["Copy link"]]],
    why="Hovering substitutes for navigating: the reader confirms 'is this the right one' without leaving the row. Non-modal, dismissed by moving; its own menu is open/copy-link only, never a form."),
  O("Undo after, for what can be undone", "pattern", "toast", title="Entry dismissed — 'Öküzgözü is below par'",
    source="Linear undo (https://linear.app/changelog/undo-actions) · Sonner (https://sonner.emilkowal.ski/toast) · adversary A6/D5: ADAPT — reversible, non-money, non-send only",
    body=[["btns",["Undo",True]],["quiet","8 s"]],
    why="Fire the routine act, offer the way back — instead of a panel before it. Scoped hard: dismissals, archives, a removed shift, a note. Never money, never a send, never a ledger row: those keep the seal before (fork F10)."),
  O("Approve, then release", "pattern", "panel", seal=True, eyebrow="Order 118 · payment", title="Release ₺ 12,000 to Kavaklıdere?",
    source="Ramp Bill Pay approvals (https://support.ramp.com/bill-pay-approvals) · adversary B16 KEEP, verified",
    body=[["fact","Approved","by Ayşe · 3 Sept · sealed"],["fact","Invoice","INV-4471 · matches the order line by line"],["fact","From","the house account · ends 0412"],
          ["hold","Hold to release the payment"]],
    footer="Two moments, two seals: approving the order and releasing the money are never one hold (ADR 0110, 0125).",
    why="Ramp separates chain approval from the payer's release; the house already lists them as separate commitments. Drawn so the second seal is seen, not assumed."),
  O("Why this was flagged, on the row", "pattern", "inplace", eyebrow="Ledger row · expanded", title="Order 121 · Sevilen · held",
    source="Ramp flagging (https://support.ramp.com/hc/en-us/articles/4417662594195-Flagging-transactions-Accidental-purchase-fraud-and-out-of-policy) · adversary B14 KEEP",
    body=[["alert","Held by a threshold","₺ 260 per bottle is 11% above the agreed ₺ 234 — the house stops an order 10% over its agreement (ADR 0116). Vendor terms, written 2 Sept by Ayşe."],
          ["btns",["Ask Sevilen"],["Adjust the threshold (manager)"],["Leave it held"]]],
    why="Every figure names its rows; every flag names the rule it tripped, on the object itself — never in a separate log the approver has to go and find."),
  O("Select many, one plain bar", "pattern", "bar", title="4 selected",
    source="Linear select issues (https://linear.app/docs/select-issues) · adversary A17/B21 KEEP — adopt the fuller keyboard spec",
    body=[["btns",["Mark ordered",True],["Assign vendor"],["Export"]],["quiet","x toggles · ⇧ ranges · ⌘A all · Esc clears"]],
    why="Bulk gets the plain die: a bar at the bottom, no scrim, no seal. The house rule already says so; this is only the mechanic."),
  O("A manager's passcode at the point of action", "pattern", "panel", eyebrow="Order 118 · line 2", title="Correct the case count to 4?",
    source="Toast POS discounts — manager passcode prompt (https://support.toasttab.com/en/article/Basic-Discount-Configuration) · adversary §6: MISSED by all four files",
    body=[["fact","Proposed by","Mehmet Kaya · staff · 14:02"],["fact","Changes","5 cases → 4 cases · ₺ 12,000 → ₺ 9,600"],
          ["field","A manager's passcode","••••",False],["quiet","The manager's name is written on the line; the seal is theirs, not the staff member's."],
          ["hold","Hold to apply as manager"]],
    why="The restaurant industry's own second-authority ceremony: superior authority, completed in seconds at the point of action — not a multi-step chain. A different thing from a two-person rule; the founder should choose which acts get which (fork F11)."),
  O("Suggested edits, not applied edits", "pattern", "inplace", eyebrow="Vendor terms · Kavaklıdere", title="The engine suggests two changes",
    source="Notion suggested edits (https://www.notion.com/help/suggested-edits) · Granola black/grey (https://www.granola.ai/blog/how-to-use-ai-to-take-meeting-notes) · adversary C9 KEEP (verified), C16 KEEP",
    body=[["sugg","Lead time","4 days","5 days — from the last 11 deliveries","add"],["sugg","Delivery days","Tue · Thu","Tue · Thu · Sat — three Saturday deliveries since June","add"],
          ["quiet","A suggestion is a layer on the record, never an already-changed cell. The person's words stay ink; the engine's stay grey — permanently, not only until accepted."],
          ["btns",["Accept both",True],["Reject both"]]],
    why="The best structural proof that 'a draft never looks sent' is buildable: nothing is touched until a person disposes of each suggestion. Provenance is a colour that never fades."),
  O("Ask about this, with its sources", "pattern", "sheet", eyebrow="Order 118", title="Ask about this order",
    source="Grounded Q&A scoped to one object (adversary C10 KEEP) · Perplexity streaming citations (https://docs.perplexity.ai/docs/cookbook/articles/streaming-citations/README) · C15 KEEP",
    body=[["field","","Did we pay more than last time?",False],
          ["text","Yes — ₺ 2,400 per case against ₺ 2,250 on 24 July [1], the same unit [2]. The three orders before that were ₺ 2,250 too [3]."],
          ["item","[1] order 118 · agreed price · 3 Sept","price_history"],["item","[2] price unit · per case · ADR 0119",""],["item","[3] orders 109 · 112 · 114",""],
          ["quiet","When the book holds no line, the answer says so: 'The book holds no line about freight for this vendor.'"]],
    why="Every sentence cites a row or says 'no data'. Sources stream with the answer, not after it — an absence is reported as an absence."),
  O("A proposal you accept line by line, sealed once", "pattern", "panel", seal=True, eyebrow="The assistant proposes", title="Three changes to the house's configuration",
    source="GitHub Copilot Edits per-hunk accept (https://learn.microsoft.com/visualstudio/ide/copilot-edits) · adversary C1 ADAPT — the batch resolves to one seal",
    body=[["chips",["Quiet hours 23:00–08:00 · accepted",True],["Low-stock floor 90 days · accepted",True],["Report clock Europe/Istanbul · rejected",False]],
          ["quiet","Each line has its reason and its provenance; you accept or reject each, then one hold applies what stands."],["hold","Hold to apply 2 of 3"]],
    why="Three granularities of accept are right; a plain 'Accept all' button is wrong when the apply is a real commitment. The ticks choose, the seal commits (ADR 0113)."),
  O("The door's sheet rests at three heights", "pattern", "bottom", eyebrow="Delivery · Kavaklıdere", title="How many boxes?",
    source="Apple HIG sheets and detents · Material bottom sheets (https://m2.material.io/components/sheets-bottom/android) · Vaul snap points (https://www.npmjs.com/package/vaul/v/1.0.0) · adversary C18/C19/D1: ADAPT — ONE decision",
    body=[["two",["Boxes delivered","5"],["Visibly broken?","No"]],["btns",["Next: photograph the paper",True]],
          ["quiet","Peek shows the next step; half holds the count; full holds the photo. The grabber appears only because there is more than one height."]],
    why="On a phone the right sheet becomes a bottom sheet — same object, same head, same close-in-words — resting at detents instead of a fixed 440. Four files asked for this four ways; it is one decision (fork F9)."),
  O("Swipe up to record it; the stamp at the end", "pattern", "bottom", seal=True, eyebrow="Delivery · Kavaklıdere", title="Record this delivery",
    source="Robinhood swipe-up-to-submit (https://robinhood.com/us/en/support/articles/selling-a-stock/) — swipe confirmed, haptic detail dropped by the adversary (C20 ADAPT)",
    body=[["fact","Boxes","5 · none broken"],["fact","Paper","photographed · 1 page"],["fact","Signed","AK"],["pill","Swipe up to record"]],
    why="The founder's own ask, proven at scale in a high-stakes app: review, then one deliberate gesture; the house's stamp completes it. On desktop the same act is the hold."),
  O("Queued is never confirmed", "pattern", "inplace", eyebrow="Door · this phone", title="Delivery · Kavaklıdere · 14:06",
    source="WhatsApp offline queue and tick ladder · adversary C24 KEEP",
    body=[["item","Saved on this phone","14:06 · no signal",True],["item","Sent to the house","—"],["item","Recorded","—"],["item","Read by a manager","—"],
          ["quiet","A record made with no signal looks provisional and steps forward through named states; it never silently reads as recorded."]],
    why="The right vocabulary for the door: four states, each unmistakable. An absence (no signal) is reported as what it is."),
  O("Who else has this open", "pattern", "sheet", eyebrow="Spot count · Cellar · rack B", title="Öküzgözü 2022",
    source="Figma presence and multiplayer (https://help.figma.com/hc/en-us/articles/360040449713) · adversary §6: MISSED — answers B's own concurrent-count gap",
    body=[["avatars","Elif is counting rack B on her phone · started 14:01"],["two",["Counted","9"],["On the book","11"]],
          ["quiet","Two people may count at once; the sheet says so, so neither writes over the other unknowing."],["hold","Hold to record the count"]],
    why="Concurrency is not the failure mode — invisibility is. A presence line on shared records makes a split count safe (fork F11)."),
  O("The invoice beside the order, cell by cell", "pattern", "inplace", eyebrow="Receipt · INV-4471", title="Order 118 · Kavaklıdere",
    source="Ramp PO matching · Restaurant365 discrepancy view · Toast AI invoice scanning split view (https://support.toasttab.com/en/article/Get-Started-With-AI-Invoice-Scanning) · adversary B17/B-R2 KEEP",
    body=[["table",["Line","Ordered","Invoiced","Read from the paper"],[["Öküzgözü 2022","5 cases","5 cases","5 × 12 · ₺ 2,400"],["Boğazkere 2021","2 cases","3 cases ⚑","3 × 12 · ₺ 2,600"],["Freight","—","₺ 180 ⚑","not on the order"]]],
          ["quiet","The paper stays visible while you correct the read; a mismatched cell is marked on the cell, not in a message."],["btns",["Accept 5 · query 2",True]]],
    why="Both cited products do this in place, not in a popup — the founder's own 'side-by-side inside an overlay' ask is answered by rule 6: the row expands and shows its working."),
  O("Step up before the money moves", "pattern", "panel", eyebrow="Order 118 · payment", title="Your session is three hours old",
    source="GitHub sudo mode (https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/sudo-mode) — fetched, holds: two hours; password, passkey or 2FA · G: ADAPT",
    body=[["quiet","Before ₺ 12,000 leaves the house, say who you are again. The hold is intent; this is identity."],
          ["field","Your passcode","••••",False],["btns",["Use my passkey"]],["hold","Then hold to release"]],
    footer="Only before money or a config apply, and only when the session is older than two hours.",
    why="A device left unlocked is the common failure; re-authentication at the moment of a real commitment closes it without touching routine work."),
  O("What the seal bound", "pattern", "inplace", eyebrow="Seal receipt · order 118", title="Released ₺ 12,000 to Kavaklıdere",
    source="FIDO Secure Payment Confirmation (https://fidoalliance.org/white-paper-secure-payment-confirmation/) — fetched, holds: amount and payee signed by the authenticator (PSD2 dynamic linking) · AWS CloudTrail digest chain (https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-log-file-validation-intro.html) · G: KEEP",
    body=[["fact","Sealed by","Ayşe Yılmaz · 3 Sept · 14:07:41"],["fact","Bound into the challenge","₺ 12,000 · Kavaklıdere · IBAN …0412 · order 118"],
          ["fact","Authority","Ayşe · owner — one approval suffices (the authority rule)"],["fact","Chain","a9f3…41c0 → 7d2e…b8a1 · verified"],
          ["quiet","The challenge minted when the hold began carries the amount and the payee; a receipt that does not match them is not a seal (ADR 0112, 0125)."]],
    why="The provable seal made visible: what was bound, by whom, and the link to the record before it. Verifiable after the fact, not asserted."),
  O("A new bank detail waits", "pattern", "panel", seal=True, eyebrow="Kavaklıdere · vendor terms", title="Kavaklıdere's bank detail changed today",
    source="City National Bank dual control and call-back (https://www.cnb.com/business-banking/insights/what-is-dual-approval.html) · UK Finance Confirmation of Payee (https://www.ukfinance.org.uk/policy-and-guidance/guidance/confirmation-payee) · G: ADAPT — bank-detail changes only, never every new vendor",
    body=[["fact","Changed by","a letter from orders@kavaklidere… · 11:02 · read by the house"],["fact","Was → is","IBAN …0412 → …7731"],
          ["alert","Held","The first payment to the new detail waits 24 hours and is released by someone with valid authority who is not the confirmer. Every owner has been told of the change."],
          ["quiet","Call the number on file — +90 312 000 00 00 — not the number in the letter."],["hold","I called; hold to confirm the detail"]],
    why="Vendor-impersonation is the single highest-fraud act on the list; a rare ceremony is worth it precisely because it is rare. The house's own separation of duties in one line."),
  O("Held for a look", "pattern", "inplace", eyebrow="Ledger row · expanded", title="Payment 3 of today · Sevilen · ₺ 3,600",
    source="Stripe Radar rules and review (https://docs.stripe.com/radar/rules) · Ramp limits (https://support.ramp.com/hc/en-us/articles/10881975647763-Card-limits-and-spend-programs) · G: KEEP, silent on the common case",
    body=[["alert","Held for a manager","Third payment to Sevilen today, four times its usual ₺ 900 — outside this house's own pattern of the last 90 days. A manager's day limit is ₺ 5,000 (ADR 0128)."],
          ["btns",["Release (manager · seal)",True],["Ask Sevilen"],["Leave it held"]]],
    why="A velocity check adds nothing to the common case and names its reason on the row when it trips — the house's rule for flags, applied to money."),
  O("The door tablet locks itself", "pattern", "bottom", eyebrow="The door · shared tablet", title="Locked after 90 seconds",
    source="Toast POS screen timeout (https://support.toasttab.com/en/article/Adjust-POS-Screen-Timeout) · Square passcodes at the point of sale (https://squareup.com/help/us/en/article/8357-require-passcodes-at-point-of-sale) · G: KEEP — the precondition for the manager's passcode",
    body=[["avatars","Elif was counting rack B · 14:01"],["field","Your passcode","",True],["quiet","Whoever picks this up is not Elif until they say so. Her count is saved on this device and waits for her."]],
    why="A shared device left open hands every person's authority to whoever picks it up; an idle lock is what makes the passcode ceremony mean anything."),
  O("Break the glass", "pattern", "panel", seal=True, eyebrow="Owner only · order 118", title="Bypass the two-person rule for this payment?",
    source="AWS Well-Architected break-glass procedures (https://docs.aws.amazon.com/wellarchitected/latest/devops-guidance/ag.sad.5-implement-break-glass-procedures.md) · G: ADAPT — rare, reasoned, told to everyone",
    body=[["field","Why, in words (required)","Hasan is unreachable and the delivery is on the truck.",False],
          ["quiet","Every owner is told the moment you hold. The trail marks this release in red and it cannot be made routine."],["hold","Hold to break the glass"]],
    why="Emergency access exists in every serious system; the house's version is owner-only, written down, and loud — never a quiet backdoor."),
])


FIT_PER_ACT = [
  ("Approve an order", "the seal (built) · a second person above the tier threshold (ADR 0128) · a passkey-backed seal for owners and managers on their own devices"),
  ("Release a payment", "the seal bound to amount and payee, with a receipt (What the seal bound) · one approval when the approver holds valid authority — owner, manager, or a person the owner authorized — double approval otherwise (the founder's amendment to the two-person rule) · step up when the session is older than two hours · a velocity hold that names why · every owner told on every move"),
  ("Add or change a vendor's bank detail", "a call to the number on file · the first payment held 24 hours and released by someone with valid authority who is not the confirmer (A new bank detail waits) · the change itself is told to every owner, as every security change is"),
  ("Write off stock", "the seal (drawn) · above a per-role daily limit, a manager's passcode · the tamper-evident trail"),
  ("A price override by staff", "the manager's passcode at the point of action (F11) · the device lock as its precondition"),
  ("Publish a week", "the seal, kept — not on F10's list · re-publish exists · the trail marks a republished week"),
  ("A config change by the assistant", "the seal on the proposal (ADR 0113) · step up when the session is old · the sealed batch stays revocable for seven days (built 2026-09-04)"),
  ("A door delivery on a shared tablet", "the idle lock (The door tablet locks itself) · a count correction within ten minutes as undo-after (added to F10's list by the founder, 2026-09-05)"),
  ("A tool write", "challenge-and-redeem (ADR 0107, built) · break-glass, owner-only with a reason, during an incident"),
]
MORE_ACCESS = [
  ("One box, many scopes", "GitHub's ⌘K routes one input across five object kinds with sigils (> # ! @ /) instead of five search fields — ours: `>` an act, `#` an order, `@` a vendor, `/` a page.", "https://github.blog/changelog/2021-10-27-command-palette-beta/"),
  ("Two-key chords from anywhere", "Linear's g + letter jumps to any view without a menu — `g o` orders, `g i` inventory, `g t` team.", "https://fastshortcuts.com/shortcuts/linear/"),
  ("The shortcut sheet is one key away", "`?` opens a searchable sheet of everything the keyboard can do here (the Keyboard shortcuts panel, already built).", "https://linear.app/changelog/2021-03-25-keyboard-shortcuts-help"),
  ("Every overlay has an address", "Vercel gives every state a URL the moment it exists; Raycast deep-links commands. Ours: `?sheet=order:118` opens the sheet — but an unapplied proposal never travels as if decided (adversary A22 ADAPT).", "https://vercel.com/docs/deployments/sharing-deployments"),
  ("Hover instead of navigate", "GitHub and Notion preview a referenced record on hover; the reader confirms without leaving the row.", "https://github.blog/changelog/2018-10-08-issue-and-pull-request-hovercards/"),
  ("The palette knows where you are", "Vercel's ⌘K resolves differently inside a deployment — on /orders the first commands are the order's own acts.", "https://vercel.com/changelog/command-menu-now-available-in-deployments"),
  ("A notification lands in the panel", "Gmail and Linear put the reversing action in the confirmation itself; the house's version: approving from the bell opens the panel with the seal, never applies on the tap (adversary C23 REJECT for bare approve).", "https://linear.app/changelog/undo-actions"),
  ("Quick capture, honestly scoped", "Raycast's floating notes work above the OS; a web app cannot (adversary A11 REJECT). What we can do: a global hotkey while the tab has focus that opens the palette on 'Write a note …'.", "https://developers.raycast.com/information/lifecycle/deeplinks"),
]

NO_OVERLAY = ["/login","/register","/forgot-password","/reset-password","/verify-email","/invite/:code","/no-access","/privacy",
  "/v/:slug","/onboarding (redirect)","/studio","/studio/queue","/studio/invite/:token","/simpos/:restaurantId (+orders, scenarios)",
  "/authorize/:integrationId","/inventory-legacy (redirect)","/vendor-prices","/dev/truth","/recommendations/catalog","/credits","/logs",
  "/profile","/connections","/help","/admin","/sommelier (HOLD)","/services","/dev-sandbox (mounts the retiring builders)","/calendar-classic"]

ANSWERS = {
  "F1": "Ratified 2026-09-05 — ADR 0112 is Locked.",
  "F2": "Reuse InviteTeamDialog with a second opener. One component, however many openers, is one exception.",
  "F5": "The owed sheet on /orders is the manual entry.",
  "F7": "The KPI row expands in place; no overlay.",
  "F3": "A 640 sheet on /inventory, not a route.",
  "F4": "All five get built, to their full purpose — functionality, endpoints, UI/UX, smoothness and above all the design (the founder's bar, 2026-09-05). Pause/resume the AI becomes a control on the responses sheet; a person's own one-tap action, an auction lot and certifications are drawn as owed sheets; assigning a recommendation to a person is the fifth, confirmed 2026-09-06.",
  "F6": "HouseHeader's bell and user menu survive; Header.tsx's house branch is deleted, its legacy branch stays byte-identical.",
  "F8": "Name the class now — six non-modal surfaces, two constraints (no scrim, no focus trap; never a form, never the seal).",
  "F9": "Yes to both — detents on the phone, stacking capped at three with a breadcrumb.",
  "F10": "Yes, with that exact line — undo-after for dismiss, archive, a removed shift, a note; money, sends and ledger rows keep the seal before.",
  "F12": "Every ceremony asked was adopted (2026-09-05 evening), with three amendments from the founder: (1) ceremonies must suit a high-paced operating environment — fast, never a chain; (2) the two-person rule becomes an AUTHORITY rule: one approval when the approver holds valid authority (owner, manager, or a person the owner has authorized), double approval otherwise; (3) any security change — a bank detail, an authority grant, a passcode reset, a limit, a device — is always told to the owners. The door count correction within ten minutes joins F10's list; publishing a week stays sealed. The deeper pass on the assistant's and tool-write ceremonies (research H, checked in I) closed the same night: step-up and the house's passkey seal ship together on web and mobile (never on a device-local prompt); break-glass is reviewed within 48 hours by another owner and the outcome told; any owner may revoke any grant; one tamper-evident security ledger.",
  "F11": "All three — the manager's passcode, presence on shared records, and a two-person rule for money as the house's own rule — and 'any other possible security like that': a security-ceremonies research pass is running (F12).",
}
FORKS = [
  ("F1","Ratify the three shapes.","ADR 0112 is still Proposed. Everything drawn here assumes Sheet · Panel · Popover; if the founder wants one shape everywhere, this census is the list of what that costs (the sheet exists so the list stays readable; an anchored menu with no anchor has lost its meaning)."),
  ("F2","The studio invite.","Reuse the one exception component (Popover modal) with a second opener — my recommendation: one component, however many openers, is still one exception — or collapse the policy to two modal shapes as the ADR's revisit clause says."),
  ("F3","A delivery without an order.","A 640 sheet on /inventory (drawn), or a route under /receipts where the receipts desk already lives."),
  ("F4","Acts no house surface recreates.","Pause AI on a thread · a person-authored one-tap action or quick-action bookmark · an auction purchase · certifications on file · assign a recommendation to a person. One call per act: delete, or build the drawn shape."),
  ("F5","Where a manual order starts.","The owed 'A new order' sheet on /orders, or from a register row, the palette, or Ask AI — OrdersNext has no create path today."),
  ("F6","Two bells, two user menus.","Header.tsx's house branch and HouseHeader's HouseBell/HouseUserMenu both exist. Which survives when the house header lands on every page."),
  ("F7","The figure behind a dashboard number.","A sheet ('the working', drawn) or the house idiom — the KPI row expands in place."),
  ("F8","The non-modal class.","Name peek · hover card · undo toast · bulk bar · the standard bottom sheet as what they are: not shapes (no scrim, no focus trap, never a form, never the seal). ADR 0112's own carve-out allows them; four files asked for them four ways — one amendment, or none."),
  ("F9","The sheet on a phone.","A bottom sheet with detents (peek / half / full) as the right sheet's phone form, and sheet stacking capped at three with a breadcrumb — one decision covering Apple detents, Material sheets and Vaul snap points together."),
  ("F10","Undo after, for what can be undone.","Fire the routine act and offer Undo (dismiss, archive, a removed shift, a note); keep the seal before for money, sends and ledger rows. The adversary's fight #4: the line must be written down or it creeps."),
  ("F11","A second authority.","Two ceremonies the research surfaced that the house has not chosen between: a manager's passcode at the point of action (Toast) for staff → manager acts, and presence on shared records (Figma) so a split count is safe. Which acts get which."),
  ("F12","Every other security ceremony like that.","The founder's addendum to F11. Twenty-four ceremonies catalogued (research/F), judged by the lead (research/G: 3 rejected — a retired ledger product, JIT sessions for staff, an out-of-band call per payment), six drawn above, and a fit per act proposed below. Decided act by act, not as a set."),
]
