#!/usr/bin/env python3
"""Regenerate only the routing table in the existing decision index."""
import argparse
from collections import Counter
import hashlib
from pathlib import Path
import re
import sys

import yaml

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- BEGIN GENERATED ADR INDEX -->"
END = "<!-- END GENERATED ADR INDEX -->"


def header(path):
    text = path.read_text()
    body = text
    meta = {}
    if text.startswith("---\n"):
        parts = text.split("---\n", 2)
        if len(parts) != 3:
            raise ValueError(f"Unclosed frontmatter: {path}")
        try:
            meta = yaml.safe_load(parts[1]) or {}
        except yaml.YAMLError:
            print(f"WARNING: malformed YAML in {path.name}; using legacy headings/bullets", file=sys.stderr)
            meta = {}
        if not isinstance(meta, dict):
            raise ValueError(f"Invalid frontmatter: {path}")
        body = parts[2]

    def bullet(name):
        match = re.search(rf"^- \*\*{name}:\*\*\s*(.+)$", body, re.M | re.I)
        return match[1] if match else ""

    heading = re.search(r"^#\s+(.+)$", body, re.M)
    title = str(meta.get("title") or (heading[1] if heading else path.stem))
    title = re.sub(r"^\d{4}\s*[-\u2014\u2013:]\s*", "", title)
    raw_status = str(meta.get("status") or bullet("Status")).lstrip("* ")
    # Extract a label, not an invented semantic judgment about the decision.
    known = re.match(r"(locked|proposed|accepted|superseded|deprecated|rejected|draft|open|merged|implemented)\b", raw_status, re.I)
    status = known[1].lower() if known else (raw_status or "unrecorded")
    date = str(meta.get("date") or bullet("Date") or meta.get("updated") or "unrecorded")
    date_match = re.search(r"\d{4}-\d{2}-\d{2}", date)
    date = date_match[0] if date_match else "unrecorded"
    return title, status, date, bool(meta)


def render(decisions):
    files = sorted(p for p in decisions.glob("*.md") if re.match(r"^\d{4}-", p.name))
    if not files:
        raise ValueError("No numbered ADR files found; refusing an empty index")
    ids = [p.name[:4] for p in files]
    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate ADR numbers; resolve before generating")
    rows = [(p, header(p)) for p in files]
    counts = Counter(data[1] for _, data in rows)
    digest = hashlib.sha256()
    for path in files:
        digest.update(path.name.encode() + b"\0" + path.read_bytes() + b"\0")

    def cell(value):
        return str(value).replace("|", "\\|").replace("\n", " ")

    lines = [BEGIN, f"<!-- source-sha256: {digest.hexdigest()} -->", "",
             f"{len(files)} numbered ADR files. Header labels: " + ", ".join(f"{n} {s}" for s, n in sorted(counts.items())) + ".",
             "", "Generated by `python3 scripts/build_decision_index.py`; verify with `--check`.",
             "Search this table, then read the matching ADR. Labels are source metadata, not revalidated decisions.",
             "Dates use the recorded decision date, falling back to frontmatter updated; missing dates remain unrecorded.",
             f"{sum(data[3] for _, data in rows)} files have parseable YAML frontmatter; the others use legacy headings and bullets.",
             "", "| # | Subject | Status | Date |", "|---|---|---|---|"]
    for path, (title, status, date, _) in rows:
        lines.append(f"| [{path.name[:4]}](../decisions/{path.name}) | {cell(title)} | {cell(status)} | {date} |")
    return "\n".join(lines + ["", END])


def replace_table(document, table):
    if document.count(BEGIN) != 1 or document.count(END) != 1:
        raise ValueError("Expected exactly one generated index region")
    before, remainder = document.split(BEGIN, 1)
    _, after = remainder.split(END, 1)
    return before + table + after


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / ".planning/00-index/DECISION-INDEX.md"
    current = target.read_text()
    expected = replace_table(current, render(ROOT / ".planning/decisions"))
    if args.check:
        if current != expected:
            print("Decision index is stale: run python3 scripts/build_decision_index.py")
            return 1
        print("Decision index matches all numbered ADR files")
    else:
        target.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
