#!/usr/bin/env python3
"""Lift loop blocks from fenced YAML bodies into queryable frontmatter + build LOOP-MAP."""
import re, json, pathlib, collections

R = pathlib.Path("/Users/aldemirkonuk/Projects/restaurant-ai-automation/.planning")
files = sorted(list((R/"01-org").rglob("*-loops.md")) + list((R/"02-advisory").rglob("*-loops.md")))

SCALAR = ("id", "owner", "close_time", "status")
LIST = ("measures", "changes", "inputs_from", "outputs_to")

# Closed vocabularies, LOCKED by OD-47 in foundation/ORG_STRUCTURE.md §5.1.
# A value outside these sets is a defect, not a variant — see the check below.
CLOSE_TIMES = ("per-pr", "hourly", "daily", "weekly", "fortnightly",
               "monthly", "quarterly", "per-event", "one-shot")
STATUSES = ("proposed", "blocked", "dormant", "gated", "active", "running")

def parse_blocks(body):
    loops = []
    for m in re.finditer(r"```ya?ml\s*\n(.*?)```", body, re.S):
        blk = m.group(1)
        if not re.search(r"^\s*id:", blk, re.M):
            continue
        d = {}
        for k in SCALAR:
            mm = re.search(rf"^\s*{k}:\s*(.+?)\s*$", blk, re.M)
            if mm:
                d[k] = mm.group(1).strip().strip('"\'')
        for k in LIST:
            mm = re.search(rf"^\s*{k}:\s*\[(.*?)\]", blk, re.M | re.S)
            if mm:
                d[k] = [x.strip().strip('"\'') for x in mm.group(1).split(",") if x.strip()]
        if "id" in d:
            loops.append(d)
    return loops

all_loops, pending, changed = [], [], 0
for f in files:
    txt = f.read_text()
    if not txt.startswith("---"):
        continue
    _, fm, body = txt.split("---", 2)
    loops = parse_blocks(body)
    if not loops:
        continue
    unit = f.name.replace("-loops.md", "")
    dm = re.search(r"^division:\s*(.+)$", fm, re.M)
    tm = re.search(r"^department:\s*(.+)$", fm, re.M)
    for L in loops:
        L["unit"] = unit
        L["division"] = dm.group(1).strip() if dm else ""
        L["department"] = tm.group(1).strip() if tm else ""
        L["file"] = str(f.relative_to(R))
    all_loops += loops
    pending.append((f, fm, body, loops))

# ORG_STRUCTURE §5.1 is a contract, not a convention: refuse to index a vocabulary
# violation. Checked across every file before any file is written, so a failure leaves
# the vault untouched rather than half-rewritten.
violations = []
for L in all_loops:
    for field, allowed in (("close_time", CLOSE_TIMES), ("status", STATUSES)):
        if L.get(field) not in allowed:
            violations.append(f"  {L['file']} :: {L['id']} :: {field}={L.get(field)!r}")
if violations:
    raise SystemExit(
        f"ORG_STRUCTURE §5.1 (OD-47) vocabulary violation — {len(violations)} loop(s):\n"
        + "\n".join(violations)
        + "\n\nPermitted close_time: " + " · ".join(CLOSE_TIMES)
        + "\nPermitted status:     " + " · ".join(STATUSES)
        + "\nNothing was written. Fix the loop blocks, or amend §5.1 first if the"
          " vocabulary itself is wrong.")

for f, fm, body, loops in pending:
    # inject queryable arrays (idempotent)
    fm = re.sub(r"^loop_(count|ids|close_times|owners|statuses):.*\n", "", fm, flags=re.M)
    def arr(key):
        return "[" + ", ".join('"%s"' % L.get(key, "") for L in loops) + "]"
    fm = fm.rstrip("\n") + "\n"
    fm += f"loop_count: {len(loops)}\n"
    fm += f"loop_ids: {arr('id')}\n"
    fm += f"loop_close_times: {arr('close_time')}\n"
    fm += f"loop_statuses: {arr('status')}\n"
    f.write_text("---" + fm + "---" + body)
    changed += 1

(R/"00-index").mkdir(exist_ok=True)
(R/"00-index/loops.json").write_text(json.dumps(all_loops, indent=1))

# LOOP-MAP.md — 56 docs link to it and it did not exist
ct = collections.Counter(L.get("close_time", "—") for L in all_loops)
st = collections.Counter(L.get("status", "—") for L in all_loops)
by_div = collections.defaultdict(list)
for L in all_loops:
    by_div[L["division"]].append(L)

out = ["---", "type: moc", "title: Loop Map", "updated: 2026-08-24", "---", "",
 "# Loop Map", "",
 "> Generated by `scripts/build_loop_index.py` from every `*-loops.md`. **Do not hand-edit.**",
 "",
 f"**{len(all_loops)} loops** across **{len(files)} units** in **{len(by_div)} divisions**.", "",
 "Loop data now also lives in each file's frontmatter (`loop_ids`, `loop_close_times`,",
 "`loop_statuses`) so Dataview can query it — the fenced YAML bodies alone were not",
 "machine-readable, which broke the promise in ORG_STRUCTURE §5.", "",
 "## Status", "", "| Status | Loops |", "|---|---|"]
out += [f"| `{k}` | {v} |" for k, v in st.most_common()]
out += ["", f"> Only the `active`/`running` rows describe something that actually runs today —"
 f" **{st['active'] + st['running']} of {len(all_loops)}**. The other statuses are written down, not cycling.", "",
 "## Close-time distribution", "", "| close_time | Loops |", "|---|---|"]
out += [f"| `{k}` | {v} |" for k, v in ct.most_common()]
out += ["", f"**{len(ct)} of the {len(CLOSE_TIMES)} permitted `close_time` values are in use.**"
 " Both `close_time` and `status` are closed vocabularies, locked by OD-47 in"
 " ORG_STRUCTURE §5.1 and enforced by this script — a value outside either set fails the"
 " build rather than landing here.", "",
 "## By division", "", "| Division | Units | Loops |", "|---|---|---|"]
for d in sorted(by_div):
    out.append(f"| {d} | {len({L['unit'] for L in by_div[d]})} | {len(by_div[d])} |")
out += ["", "## Live Dataview query", "",
 "```dataview", "TABLE loop_count, loop_ids, loop_close_times",
 'FROM "01-org" OR "02-advisory"', "WHERE type = \"loops\"", "SORT loop_count DESC", "```"]
(R/"00-index/LOOP-MAP.md").write_text("\n".join(out))

print(f"files updated: {changed} | loops indexed: {len(all_loops)}")
print(f"distinct close_time values: {len(ct)}")
print("status:", dict(st.most_common(6)))
