#!/usr/bin/env python3
"""OD-41: create questions.md (artifact #8) for every unit + the index MOCs."""
import json, pathlib, collections

R = pathlib.Path("/Users/aldemirkonuk/Projects/restaurant-ai-automation/.planning")
m = json.load(open(R / "00-index/UNIT-MANIFEST.json"))

TPL = """---
type: questions
division: {division}
department: {department}{team_line}
status: open
updated: 2026-08-24
open_questions: 0
links: ["[[{slug}-charter]]", "[[{slug}-agenda-full]]", "[[architecture-review-charter]]", "[[red-team-charter]]", "[[decision-office-charter]]"]
---

# {title} — Questions & Findings

> **Delivery point for advisory findings** ([ORG_STRUCTURE §3](../../../foundation/ORG_STRUCTURE.md)).
> Advisory is **findings-only**: nothing here blocks. The founder arbitrates.
> Also holds questions this unit cannot answer alone.

## Open

| ID | From | Raised | Question or finding | Next action | Age-out |
|---|---|---|---|---|---|
| — | — | — | *(none yet)* | — | — |

## Answered

| ID | From | Raised | Closed | Outcome |
|---|---|---|---|---|

---

## How this file works

**Who writes here.** Architecture Review, Red Team, and Decision Office write findings
against this unit. This unit writes its own unanswerable questions. Nobody else edits it.

**ID format.** `{prefix}-Q<n>` for this unit's own questions; advisory keeps its own
prefix (`AR-`, `RT-`, `DO-`) so provenance survives a copy-paste.

**Escalation.** A finding still Open after **42 days** must resolve to a binary — fix it,
or accept it in writing with a named owner and a date. *Accepting is an honourable close.*
Anything implying a decision also gets a row in
[`OPEN-DECISIONS.md`](../../../decisions/OPEN-DECISIONS.md); this file is not a decision log.

**Why this file exists.** The advisory layer was specified with `questions.md` as its
delivery target and then built without one — so all three functions were inert on arrival
(OD-41). Created 2026-08-24 by `scripts/build_questions_files.py`.

```dataview
TABLE open_questions, updated
FROM "01-org" OR "02-advisory"
WHERE type = "questions" AND open_questions > 0
SORT open_questions DESC
```
"""

made = 0
for u in m["units"]:
    d = R / u["dir"]
    if not d.exists():
        continue
    f = d / f"{u['slug']}-questions.md"
    if f.exists():
        continue
    team_line = f"\nteam: {u['slug']}" if u["kind"] == "team" else ""
    f.write_text(TPL.format(
        division=u.get("division", ""), department=u.get("department", u["slug"]),
        team_line=team_line, slug=u["slug"], title=u["title"],
        prefix=u["slug"][:3].upper()))
    u["files"]["questions"] = str(f.relative_to(R))
    made += 1

json.dump(m, open(R / "00-index/UNIT-MANIFEST.json", "w"), indent=1)

# ---- ORG-MAP.md ----
by_div = collections.defaultdict(lambda: collections.defaultdict(list))
adv = []
for u in m["units"]:
    if u["kind"] == "advisory":
        adv.append(u)
    elif u["kind"] == "department":
        by_div[u["division"]][u["slug"]]
    else:
        by_div[u["division"]][u["department"]].append(u)

out = ["---", "type: moc", "title: Org Map", "updated: 2026-08-24", "---", "",
       "# Org Map", "",
       "> Generated by `scripts/build_questions_files.py`. **Do not hand-edit.**", "",
       f"**{len(m['divisions'])} divisions · "
       f"{sum(1 for u in m['units'] if u['kind']=='department')} departments and sub-layers · "
       f"{sum(1 for u in m['units'] if u['kind']=='team')} teams · "
       f"{len(adv)} advisory** — {len(m['units'])} units, 8 artifacts each.", ""]
for d in m["divisions"]:
    out.append(f"## {d['title']}")
    out.append("")
    for dept in d["departments"]:
        teams = by_div[d["slug"]].get(dept, [])
        out.append(f"- **[[{dept}-charter|{dept}]]** — {len(teams)} teams")
        for t in teams:
            gate = " ⏸" if t.get("gated") else ""
            out.append(f"  - [[{t['slug']}-charter|{t['title']}]]{gate}")
    out.append("")
out += ["## Advisory (cross-cutting, findings-only)", ""]
out += [f"- [[{a['slug']}-charter|{a['title']}]]" for a in adv]
out += ["", "## Live queries", "",
        "```dataview", "TABLE division, status, updated",
        'FROM "01-org" OR "02-advisory"', 'WHERE type = "charter"',
        "SORT division ASC", "```", "",
        "Open questions across the org:", "",
        "```dataview", "TABLE open_questions",
        'FROM "01-org" OR "02-advisory"',
        'WHERE type = "questions" AND open_questions > 0', "```"]
(R / "00-index/ORG-MAP.md").write_text("\n".join(out))

# ---- HOME.md ----
(R / "00-index/HOME.md").write_text("""---
type: moc
title: Home
updated: 2026-08-24
---

# Mudavym — Vault Home

Autonomous restaurant operations platform. One entity; many small softwares inside it.

## Start here

| Map | What it answers |
|---|---|
| [[ORG-MAP]] | Who exists — divisions → departments → teams → advisory |
| [[LOOP-MAP]] | What feeds back into what, and how fast it closes |
| [[OPEN-DECISIONS]] | What is still undecided, and what unblocks it |
| [[README]] *(foundation)* | The 7-layer stack, skills, neural footprint |

## Reading order for a new session

1. `CLAUDE.md` — how we work here
2. `decisions/README.md` — what is locked
3. `foundation/ORG_STRUCTURE.md` — the org contract
4. `foundation/README.md` — the stack and the metric spine

## Honest state

```dataview
TABLE WITHOUT ID status AS "Charter status", length(rows) AS Units
FROM "01-org" OR "02-advisory"
WHERE type = "charter"
GROUP BY status
```

The org is **designed, not operating**. See [[LOOP-MAP]]: of 482 loops, only a handful
carry status `active` or `running`. Treat the corpus as a plan, not as capability.
""")
print(f"questions.md created: {made}")
print("wrote 00-index/ORG-MAP.md and 00-index/HOME.md")
