#!/usr/bin/env python3
"""
Concatenate all SQL migrations into a single SQL file.

Usage:
  python3 scripts/concat_migrations.py
"""

from pathlib import Path


def main() -> None:
    root = Path(__file__).parent.parent
    migrations_dir = root / "services" / "database" / "migrations"
    output_file = root / "md" / "02-architecture" / "FULL_MIGRATIONS.sql"

    migration_files = sorted(migrations_dir.glob("*.sql"))
    if not migration_files:
        raise SystemExit(f"No migration files found in {migrations_dir}")

    lines = [
        "-- ============================================================================\n",
        "-- WineOps AI Full Migration Bundle\n",
        "-- Source: services/database/migrations/*.sql\n",
        "-- Generated by: scripts/concat_migrations.py\n",
        "-- ============================================================================\n",
        "\n",
    ]

    for path in migration_files:
        lines.append(f"-- ==============================================\n")
        lines.append(f"-- BEGIN {path.name}\n")
        lines.append(f"-- ==============================================\n")
        content = path.read_text(encoding="utf-8").rstrip()
        lines.append(content)
        lines.append("\n\n")

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text("".join(lines), encoding="utf-8")
    print(f"✅ Wrote {output_file}")


if __name__ == "__main__":
    main()
