#!/usr/bin/env python3
"""
generate_ontology_seed.py
=========================
Calls Claude Opus to generate comprehensive wine ontology seed data.
Outputs 4 SQL seed files to supabase/migrations/seed/.

Usage:
    ANTHROPIC_API_KEY=... python3 scripts/generate_ontology_seed.py
    CLAUDE_API_KEY=... python3 scripts/generate_ontology_seed.py
    python3 scripts/generate_ontology_seed.py --fallback   # skip API, use embedded data

Cost estimate: ~$3-8 total (claude-opus-4-5, 12 API calls, ~8192 output tokens each)
"""
import os
import sys
import re
import time
import pathlib
import argparse

SEED_DIR = pathlib.Path("supabase/migrations/seed")
SEED_DIR.mkdir(parents=True, exist_ok=True)

# Model preference list — first available wins
MODELS_TO_TRY = [
    "claude-opus-4-5-20251001",
    "claude-opus-4-5",
    "claude-3-opus-20240229",
]

SOURCE_REF = "claude-opus-seed-v1"

# ---------------------------------------------------------------------------
# API helpers
# ---------------------------------------------------------------------------

def get_api_key() -> str | None:
    return (
        os.environ.get("ANTHROPIC_API_KEY")
        or os.environ.get("CLAUDE_API_KEY")
    )


def detect_model(client) -> str | None:
    """Return first working model name."""
    for model in MODELS_TO_TRY:
        try:
            client.messages.create(
                model=model, max_tokens=10,
                messages=[{"role": "user", "content": "ping"}],
            )
            print(f"  [model] {model} ✓", flush=True)
            return model
        except Exception as e:
            err = str(e).lower()
            if any(x in err for x in ("not_found", "invalid_model", "404", "model_not_found")):
                print(f"  [model] {model} not available, trying next...", flush=True)
            else:
                raise
    return None


def call_claude(client, model: str, prompt: str, max_tokens: int = 8192) -> str:
    """Call Claude and return text content."""
    msg = client.messages.create(
        model=model, max_tokens=max_tokens,
        messages=[{"role": "user", "content": prompt}],
    )
    return msg.content[0].text


def extract_inserts(text: str, table: str) -> list[str]:
    """Extract valid INSERT lines starting with INSERT INTO <table>."""
    lines = []
    for raw in text.strip().split("\n"):
        line = raw.strip()
        # Normalise: lowercase prefix check
        if re.match(rf"INSERT\s+INTO\s+{re.escape(table)}\s*\(", line, re.IGNORECASE):
            # Ensure ends with semicolon
            if not line.endswith(";"):
                line += ";"
            # Fix canonical_name: replace JSON-style aliases with PG TEXT[] style
            line = fix_aliases_format(line)
            lines.append(line)
    return lines


def fix_aliases_format(sql: str) -> str:
    """Convert JSON-array aliases like '["foo","bar"]' to PG TEXT[] '{foo,bar}'."""
    def _json_to_pg(match):
        inner = match.group(1)
        # Extract quoted strings
        items = re.findall(r'"([^"]+)"', inner)
        if not items:
            return "'{}'"
        escaped = [i.replace("'", "''") for i in items]
        return "'{" + ",".join(escaped) + "}'"
    return re.sub(r"'\[([^\]]*)\]'", _json_to_pg, sql)


def write_seed_file(filename: str, header: str, sql_lines: list[str]) -> int:
    """Write seed SQL file. Returns row count."""
    path = SEED_DIR / filename
    content = (
        f"-- {header}\n"
        f"-- Generated by scripts/generate_ontology_seed.py\n"
        f"-- Source: {SOURCE_REF}\n\n"
        + "\n".join(sql_lines)
        + "\n"
    )
    path.write_text(content)
    return len(sql_lines)


# ---------------------------------------------------------------------------
# Prompt templates
# ---------------------------------------------------------------------------

REGION_PROMPT = """Generate SQL INSERT INTO wine_regions (name, level, country_code, classification_system, canonical_name, aliases, source_ref) for {description}.

Rules:
- level values: 'country', 'region', 'sub_region', 'appellation', 'commune', 'vineyard'
- canonical_name: ONLY lowercase a-z, digits, underscores (valid ltree label). E.g. 'saint_estephe', 'pauillac', 'cote_de_nuits'
- aliases: PostgreSQL TEXT[] literal format — '{alias1,alias2}' or '{}' if none
- country_code: ISO 3166-1 alpha-2 (FR, IT, ES, DE, AT, US, AU, NZ, ZA, AR, CL, PT, GR, HU, etc.)
- classification_system: 'AOC', 'DOC/DOCG', 'DO/DOCa', 'QbA', 'AVA', 'GI', 'PDO', 'DAC', etc.
- source_ref: 'claude-opus-seed-v1'
- Do NOT include id or parent_id columns
- Output ONLY valid SQL INSERT statements, one per line, each ending with semicolon
- No markdown, no comments, no blank lines, no explanatory text — only INSERT statements"""

GRAPE_PROMPT = """Generate SQL INSERT INTO grape_varieties (name, canonical_name, color, family, aliases, typical_regions, typical_blending_partners) for {description}.

Rules:
- canonical_name: lowercase, spaces → underscores (e.g. 'pinot_noir', 'sauvignon_blanc')
- color: exactly 'red', 'white', 'rosé', or 'orange'
- aliases: PostgreSQL TEXT[] literal — '{alias1,alias2}' — include ALL common synonyms
  Examples: Syrah → '{shiraz,petite_syrah}', Garnacha → '{grenache,cannonau}', Tempranillo → '{tinto_fino,tinta_del_pais,aragones,cencibel}'
- typical_regions: '{region1,region2}' — 2-5 regions
- typical_blending_partners: '{grape1,grape2}' — 2-4 grapes or '{}'
- Do NOT include id column, do NOT include source_ref (not in table)
- Output ONLY valid SQL INSERT statements, one per line, each ending with semicolon
- No markdown, no comments, no blank lines — only INSERT statements"""

APPELLATION_PROMPT = """Generate SQL INSERT INTO appellation_rules (appellation_name, required_grapes, allowed_grapes, min_aging_months, min_vintage_release_delay_months, allowed_colors, classification_levels, source_ref) for ≥120 major wine appellations worldwide.

Include at minimum: Barolo, Barbaresco, Brunello di Montalcino, Chianti Classico, Vino Nobile di Montepulciano, Amarone della Valpolicella, Sagrantino di Montefalco, Taurasi, Champagne (NV and vintage), Bordeaux AOC, Pauillac, Saint-Julien, Margaux, Saint-Estèphe, Graves, Pessac-Léognan, Sauternes, Côte-Rôtie, Châteauneuf-du-Pape, Hermitage, Gigondas, Alsace Grand Cru, Burgundy Premier Cru, Burgundy Grand Cru, Gevrey-Chambertin, Rioja Reserva, Rioja Gran Reserva, Ribera del Duero Reserva, Priorat, Napa Valley Cabernet Sauvignon, Willamette Valley Pinot Noir, Mosel Spätlese Riesling, Barossa Valley Shiraz, Coonawarra Cabernet, Margaret River, Hunter Valley Semillon, Marlborough Sauvignon Blanc, Mendoza Malbec, Tokaji Aszú, Douro Tinto, Port (Vintage), Port (LBV), Champagne Blanc de Blancs, Cremant d'Alsace, Brunello Riserva, Barolo Riserva.

Rules:
- required_grapes: JSONB — '[{{"grape": "Nebbiolo", "min_pct": 100}}]' or '[]' if no strict grape
- allowed_grapes: JSONB — '[{{"grape": "Sangiovese", "min_pct": 80}}]' or '[]' if unrestricted
- min_aging_months: integer months total aging required (0 if none)
- min_vintage_release_delay_months: months from harvest to earliest legal release
  Key values: Barolo=38, Barolo Riserva=62, Barbaresco=26, Brunello=60, Brunello Riserva=72, Champagne NV=15, Champagne Vintage=36, Beaujolais Nouveau=0, Rioja Joven=0, Rioja Crianza=24, Rioja Reserva=36, Rioja Gran Reserva=60, Ribera del Duero Reserva=36, Bordeaux AOC=0, Chablis=0
- allowed_colors: PostgreSQL TEXT[] — '{{red}}', '{{white}}', '{{red,white}}', '{{sparkling}}'
- classification_levels: TEXT[] — '{{DOCG}}', '{{AOC}}', '{{AVA}}', '{{DO}}', '{{DOCa}}'
- source_ref: 'claude-opus-seed-v1'
- Do NOT include id or appellation_id columns
- Output ONLY valid SQL INSERT statements, one per line, each ending with semicolon
- No markdown, no comments, no blank lines — only INSERT statements"""

VINTAGE_PROMPT = """Generate SQL INSERT INTO vintage_rules (appellation_name, rule_type, min_release_delay_months, allows_nv, notes, source_ref) for ≥35 wine appellations with vintage release constraints.

Include: Barolo Standard, Barolo Riserva, Barbaresco Standard, Barbaresco Riserva, Brunello di Montalcino Standard, Brunello di Montalcino Riserva, Chianti Classico, Chianti Classico Riserva, Chianti Classico Gran Selezione, Amarone della Valpolicella, Champagne NV, Champagne Vintage, Champagne Prestige Cuvée, Beaujolais Nouveau, Beaujolais Villages, Chablis, Bordeaux AOC, Pauillac, Sauternes, Côte-Rôtie, Hermitage, Châteauneuf-du-Pape, Rioja Joven, Rioja Crianza, Rioja Reserva, Rioja Gran Reserva, Ribera del Duero Crianza, Ribera del Duero Reserva, Ribera del Duero Gran Reserva, Priorat, Napa Valley Cabernet, Willamette Valley Pinot Noir, Barossa Shiraz, Coonawarra Cabernet, Tokaji Aszú, Douro Vintage Port, Madeira (NV), Cava NV, Cava Reserva, Port Vintage, Port LBV.

Rules:
- rule_type: exactly one of 'standard', 'riserva', 'gran_reserva', 'nouveau', 'special'
- min_release_delay_months: exact integer (Barolo standard=38, Barolo Riserva=62, Brunello=60, Brunello Riserva=72, Champagne NV=15, Champagne Vintage=36, Beaujolais Nouveau=0, Rioja Joven=0, Rioja Crianza=24, Rioja Reserva=36, Rioja Gran Reserva=60)
- allows_nv: true only for Champagne NV, Cava NV, Port NV, Madeira, and similar styles; false for all others
- notes: brief factual note (e.g. 'Harvest counted from Oct 1 of vintage year')
- source_ref: 'claude-opus-seed-v1'
- Do NOT include id or region_id columns
- Output ONLY valid SQL INSERT statements, one per line, each ending with semicolon
- No markdown, no comments, no blank lines — only INSERT statements"""


# ---------------------------------------------------------------------------
# Region batch definitions (10 batches → ≥2000 rows total)
# ---------------------------------------------------------------------------

REGION_BATCHES = [
    ("France - Bordeaux", "FR", "all Bordeaux regions, sub-regions, and appellations: include Bordeaux AOC, Bordeaux Supérieur, Médoc, Haut-Médoc, Saint-Estèphe, Pauillac, Saint-Julien, Margaux, Moulis-en-Médoc, Listrac-Médoc, Graves, Pessac-Léognan, Sauternes, Barsac, Cérons, Saint-Émilion, Saint-Émilion Grand Cru, Pomerol, Lalande-de-Pomerol, Fronsac, Canon-Fronsac, Montagne-Saint-Émilion, Saint-Georges-Saint-Émilion, Lussac-Saint-Émilion, Puisseguin-Saint-Émilion, Blaye, Blaye-Côtes de Bordeaux, Côtes de Bourg, Francs-Côtes de Bordeaux, Castillon-Côtes de Bordeaux, Entre-Deux-Mers, Sainte-Foy-Bordeaux, plus at least 20 major châteaux-level communes in Médoc. Generate ≥80 rows."),
    ("France - Burgundy & Beaujolais", "FR", "all Burgundy and Beaujolais regions and communes: Chablis AOC, Petit Chablis, Chablis Premier Cru, Chablis Grand Cru, Irancy, Saint-Bris, Côte de Nuits, Marsannay, Fixin, Gevrey-Chambertin, Morey-Saint-Denis, Chambolle-Musigny, Vougeot, Vosne-Romanée, Flagey-Échézeaux, Nuits-Saint-Georges, Hautes-Côtes de Nuits, Côte de Beaune, Ladoix, Aloxe-Corton, Pernand-Vergelesses, Savigny-lès-Beaune, Chorey-lès-Beaune, Beaune, Pommard, Volnay, Monthélie, Saint-Romain, Auxey-Duresses, Meursault, Blagny, Puligny-Montrachet, Chassagne-Montrachet, Saint-Aubin, Santenay, Maranges, Hautes-Côtes de Beaune, Côte Chalonnaise, Bouzeron, Rully, Mercurey, Givry, Montagny, Mâconnais, Mâcon, Mâcon-Villages, Pouilly-Fuissé, Pouilly-Vinzelles, Pouilly-Loché, Saint-Véran, Viré-Clessé, Beaujolais AOC, Beaujolais Villages, Brouilly, Côte de Brouilly, Morgon, Chiroubles, Fleurie, Moulin-à-Vent, Chénas, Juliénas, Saint-Amour, Régnié. Generate ≥80 rows."),
    ("France - Champagne, Alsace, Loire, Rhône", "FR", "Champagne: Montagne de Reims, Vallée de la Marne, Côte des Blancs, Côte des Bar, and key villages (Reims, Épernay, Aÿ, Hautvillers, Cramant, Avize, Le Mesnil-sur-Oger, Vertus, Bouzy, Ambonnay, Verzenay, Verzy, Mareuil-sur-Aÿ). Alsace: Alsace AOC, Crémant d'Alsace, plus all 51 Alsace Grand Cru sites (Altenberg de Bergbieten, Altenberg de Bergheim, Altenberg de Wolxheim, Brand, Bruderthal, Eichberg, Engelberg, Florimont, Frankstein, Froehn, Furstentum, Geisberg, Gloeckelberg, Goldert, Hatschbourg, Hengst, Kaefferkopf, Kanzlerberg, Kastelberg, Kessler, Kirchberg de Barr, Kirchberg de Ribeauvillé, Kitterlé, Mambourg, Mandelberg, Marckrain, Moenchberg, Muenchberg, Ollwiller, Osterberg, Pfersigberg, Pfingstberg, Praelatenberg, Rangen, Rosacker, Saering, Schlossberg, Schoenenbourg, Sommerberg, Sonnenglanz, Spiegel, Sporen, Steinert, Steingrubler, Steinklotz, Vorbourg, Wiebelsberg, Wineck-Schlossberg, Winzenberg, Zinnkoepflé, Zotzenberg). Loire Valley: Muscadet, Muscadet Sèvre et Maine, Gros Plant du Pays Nantais, Anjou, Anjou-Villages, Saumur, Saumur-Champigny, Savennières, Quarts de Chaume, Bonnezeaux, Coteaux du Layon, Bourgueil, Chinon, Vouvray, Montlouis, Sancerre, Pouilly-Fumé, Menetou-Salon, Quincy, Reuilly. Rhône: Côte-Rôtie, Condrieu, Château-Grillet, Saint-Joseph, Hermitage, Crozes-Hermitage, Cornas, Saint-Péray, Châteauneuf-du-Pape, Gigondas, Vacqueyras, Beaumes-de-Venise, Rasteau, Lirac, Tavel, Côtes du Rhône, Côtes du Rhône Villages, Vinsobres, Costières de Nîmes. Generate ≥100 rows."),
    ("France - Provence, Languedoc, SW, Jura, Savoie, Corsica", "FR", "Provence: Côtes de Provence, Coteaux d'Aix-en-Provence, Les Baux-de-Provence, Bandol, Cassis, Palette, Bellet, Coteaux Varois en Provence, Pierrevert. Languedoc-Roussillon: Languedoc AOC, Corbières, Minervois, Minervois La Livinière, Fitou, Saint-Chinian, Faugères, La Clape, Picpoul de Pinet, Pic Saint-Loup, Terrasses du Larzac, Limoux, Crémant de Limoux, Blanquette de Limoux, Muscat de Frontignan, Muscat de Lunel, Muscat de Mireval, Muscat de Saint-Jean-de-Minervois, Côtes du Roussillon, Côtes du Roussillon Villages, Collioure, Banyuls, Banyuls Grand Cru, Maury, Rivesaltes, Muscat de Rivesaltes. Southwest: Cahors, Bergerac, Pécharmant, Monbazillac, Rosette, Saussignac, Montravel, Gaillac, Madiran, Pacherenc du Vic-Bilh, Jurançon, Irouléguy, Buzet, Côtes du Marmandais, Fronton, Saint-Mont, Marcillac, Entraygues et Le Fel, Côtes de Duras. Jura: Arbois, Château-Chalon, L'Étoile, Côtes du Jura, Crémant du Jura, Macvin du Jura. Savoie: Vin de Savoie, Roussette de Savoie, Seyssel, Bugey, Crémant de Savoie. Corsica: Ajaccio, Patrimonio, Muscat du Cap Corse, Vin de Corse, Vin de Corse Calvi, Vin de Corse Figari, Vin de Corse Porto-Vecchio, Vin de Corse Sartène. Generate ≥80 rows."),
    ("Italy - Piedmont, Tuscany, Veneto, Campania, Lombardy", "IT", "Italy's top wine regions. Piedmont: Barolo DOCG, Barbaresco DOCG, Barbera d'Asti DOCG, Barbera d'Alba DOC, Dolcetto d'Alba DOC, Dolcetto d'Asti DOC, Langhe DOC, Moscato d'Asti DOCG, Asti Spumante DOCG, Brachetto d'Acqui DOCG, Gattinara DOCG, Ghemme DOCG, Roero DOCG, Dogliani DOCG, Ruché di Castagnole Monferrato DOCG, Nizza DOCG, Ovada DOCG, Alta Langa DOCG, Loazzolo DOC, Monferrato DOC, Colli Tortonesi DOC, Colline Novaresi DOC, Gabiano DOC, Freisa d'Asti DOC, Grignolino d'Asti DOC, Malvasia di Casorzo d'Asti DOC, Cortese dell'Alto Monferrato DOC. Tuscany: Chianti DOCG, Chianti Classico DOCG, Brunello di Montalcino DOCG, Rosso di Montalcino DOC, Vino Nobile di Montepulciano DOCG, Morellino di Scansano DOCG, Vernaccia di San Gimignano DOCG, Bolgheri DOC, Bolgheri Sassicaia DOC, Carmignano DOCG, Maremma Toscana DOC, Montecucco DOCG, Monteregio di Massa Marittima DOC, Elba DOC, Pomino DOC, Val d'Arbia DOC, Valdarno di Sopra DOC, Orcia DOC. Veneto: Amarone della Valpolicella DOCG, Valpolicella DOC, Recioto della Valpolicella DOCG, Soave DOC, Soave Classico DOC, Soave Superiore DOCG, Recioto di Soave DOCG, Bardolino DOC, Bardolino Chiaretto DOC, Prosecco DOC, Conegliano Valdobbiadene Prosecco Superiore DOCG, Lugana DOC, Custoza DOC, Gambellara DOC, Lison DOCG, Breganze DOC, Colli Euganei DOC, Colli Berici DOC. Campania: Taurasi DOCG, Greco di Tufo DOCG, Fiano di Avellino DOCG, Sannio DOC, Campi Flegrei DOC, Ischia DOC, Cilento DOC, Aglianico del Taburno DOCG. Lombardy: Franciacorta DOCG, Valtellina Superiore DOCG, Sforzato di Valtellina DOCG, Oltrepò Pavese DOC, Lugana DOC (shared with Veneto), Garda DOC, Valcalepio DOC. Generate ≥120 rows."),
    ("Italy - Sicily, Sardinia, Puglia, Umbria, Marche, Abruzzo, Friuli, Emilia-Romagna", "IT", "Sicily: Etna DOC (Etna Rosso, Etna Bianco, Etna Rosato), Nero d'Avola (Sicilia DOC), Marsala DOC, Passito di Pantelleria DOC, Pantelleria DOC, Cerasuolo di Vittoria DOCG, Alcamo DOC, Mamertino DOC, Noto DOC, Vittoria DOC. Sardinia: Cannonau di Sardegna DOC, Vermentino di Gallura DOCG, Vermentino di Sardegna DOC, Carignano del Sulcis DOC, Vernaccia di Oristano DOC, Monica di Sardegna DOC, Nuragus di Cagliari DOC, Malvasia di Bosa DOC. Puglia: Primitivo di Manduria DOCG, Primitivo di Manduria Dolce Naturale DOCG, Salice Salentino DOC, Castel del Monte DOCG, Gioia del Colle DOC, Locorotondo DOC, Martina Franca DOC, Negroamaro di Terra d'Otranto DOC. Umbria: Sagrantino di Montefalco DOCG, Montefalco DOC, Orvieto DOC, Torgiano Rosso Riserva DOCG, Colli Amerini DOC. Marche: Verdicchio dei Castelli di Jesi DOC, Verdicchio di Matelica DOC, Rosso Conero DOC, Conero DOCG, Rosso Piceno DOC, Offida DOCG. Abruzzo: Montepulciano d'Abruzzo DOC, Cerasuolo d'Abruzzo DOC, Trebbiano d'Abruzzo DOC, Colline Teramane Montepulciano d'Abruzzo DOCG. Friuli-Venezia Giulia: Collio Goriziano DOC, Colli Orientali del Friuli DOC, Friuli Isonzo DOC, Friuli Grave DOC, Friuli Colli Orientali Picolit DOCG, Ramato (Friuli Pinot Grigio Ramato). Emilia-Romagna: Lambrusco di Sorbara DOC, Lambrusco Grasparossa di Castelvetro DOC, Lambrusco Salamino di Santa Croce DOC, Lambrusco Reggiano DOC, Sangiovese di Romagna DOC, Albana di Romagna DOCG, Pignoletto DOC. Trentino-Alto Adige: Alto Adige DOC (Südtirol DOC), Trentino DOC, Trento DOC. Also Lazio: Frascati DOC, Est! Est!! Est!!! di Montefiascone DOC, Roma DOC. Generate ≥100 rows."),
    ("Spain, Germany, Austria", "ES", "Spain: Rioja DOCa (Rioja Alta, Rioja Alavesa, Rioja Baja/Oriental), Ribera del Duero DO, Priorat DOCa, Rías Baixas DO (Val do Salnés, O Rosal, Condado do Tea, Soutomaior, Ribeira do Ulla), Galicia (Ribeiro DO, Ribeira Sacra DO, Monterrei DO, Valdeorras DO), Penedès DO, Cava DO, Rueda DO, Toro DO, Bierzo DO, Jumilla DO, Yecla DO, La Mancha DO, Valdepeñas DO, Utiel-Requena DO, Valencia DO, Alicante DO, Navarra DO, Somontano DO, Campo de Borja DO, Calatayud DO, Cariñena DO, Empordà DO, Tarragona DO, Terra Alta DO, Jerez-Xérès-Sherry DO, Manzanilla-Sanlúcar DO, Montilla-Moriles DO, Málaga DO, Sierras de Málaga DO, Cigales DO, Arlanza DO, Ribera del Júcar DO, Pla de Bages DO, Conca de Barberà DO, Costers del Segre DO, Bullas DO, Almansa DO, Manchuela DO, Uclés DO. Germany: Mosel (Bernkastel, Piesport, Wehlen, Graach, Zeltingen, Ürzig, Erden, Leiwen, Wintrich, Trittenheim, Neumagen, Brauneberg, Kues, Dhron), Nahe (Bad Kreuznach, Schlossböckelheim, Monzingen, Niederhausen, Norheim), Rheinhessen (Nierstein, Oppenheim, Nackenheim, Westhofen, Flörsheim-Dalsheim, Gau-Odernheim), Pfalz (Deidesheim, Forst, Wachenheim, Ruppertsberg, Bad Dürkheim, Kallstadt, Ungstein, Freinsheim), Rheingau (Rüdesheim, Geisenheim, Winkel, Johannisberg, Oestrich, Hattenheim, Erbach, Eltville, Hochheim, Rauenthal), Franken (Würzburg, Randersacker, Iphofen, Escherndorf, Nordheim, Volkach), Baden (Kaiserstuhl, Tuniberg, Ortenau, Breisgau, Markgräflerland, Bodensee), Württemberg (Stuttgart area, Württemberg region), Ahr (Altenahr, Ahrweiler, Dernau, Mayschoss, Walporzheim), Saale-Unstrut, Sachsen (Meißen, Dresden, Radebeul). Austria: Wachau DAC (Dürnstein, Weissenkirchen, Spitz, Loiben, Joching, Aggsbach), Kremstal DAC, Kamptal DAC (Langenlois, Gobelsburg, Zöbing), Traisental DAC, Wiener Gemischter Satz DAC, Thermenregion, Carnuntum DAC, Neusiedlersee DAC (Gols, Purbach, Weiden), Neusiedlersee-Hügelland DAC (Rust, Oggau, Mörbisch), Leithaberg DAC, Mittelburgenland DAC, Eisenberg DAC, Südsteiermark DAC, Vulkanland Steiermark DAC, Weststeiermark DAC. Generate ≥150 rows."),
    ("USA - California, Oregon, Washington, NY, Other", "US", "California AVAs: Napa Valley (Stags Leap District, Rutherford, Oakville, Yountville, St. Helena, Calistoga, Howell Mountain, Atlas Peak, Chiles Valley, Coombsville, Diamond Mountain District, Spring Mountain District, Mount Veeder, Wild Horse Valley, Oak Knoll District, Los Carneros, Pritchard Hill). Sonoma County (Sonoma Coast, Russian River Valley, Dry Creek Valley, Alexander Valley, Knights Valley, Chalk Hill, Bennett Valley, Moon Mountain District, Petaluma Gap, Fountaingrove District, Pine Mountain-Cloverdale Peak, Rockpile, Sonoma Mountain, West Sonoma Coast, Northern Sonoma, Sonoma Valley). Central Coast (Paso Robles Highlands District, Paso Robles Estrella District, Willow Creek District, El Pomar District, Templeton Gap District, Adelaida District, Santa Lucia Highlands, Arroyo Seco, Chalone, Carmel Valley, Santa Cruz Mountains, San Ysidro District, Cienega Valley, Mount Harlan, Livermore Valley, Santa Barbara County, Santa Ynez Valley, Sta. Rita Hills, Santa Maria Valley, Happy Canyon, Ballard Canyon, Los Olivos District, Alisos Canyon). Other California (Sierra Foothills, Lodi, Delta, Clarksburg, Dunnigan Hills, Clear Lake, Guenoc Valley, Lake County, Mendocino County, Anderson Valley, Redwood Valley, Potter Valley, McDowell Valley, Cole Ranch, Shenandoah Valley CA). Oregon (Willamette Valley, Chehalem Mountains, Ribbon Ridge, Dundee Hills, Yamhill-Carlton, McMinnville, Eola-Amity Hills, Van Duzer Corridor, Tualatin Hills, Upper Willamette Valley, Umpqua Valley, Red Hill Douglas County, Elkton Oregon, Rogue Valley, Applegate Valley, Illinois Valley, Southern Oregon, Walla Walla Valley OR, Columbia Gorge, Snake River Valley). Washington (Columbia Valley, Yakima Valley, Red Mountain, Walla Walla Valley WA, Horse Heaven Hills, Wahluke Slope, Rattlesnake Hills, Snipes Mountain, Ancient Lakes, Lake Chelan, Naches Heights, Puget Sound, Lewis-Clark Valley). New York (Finger Lakes, Cayuga Lake, Seneca Lake, Canandaigua Lake, Long Island, North Fork of Long Island, The Hamptons, Hudson River Region, Lake Erie NY). Other states (Virginia, Texas Hill Country, Texas High Plains, Michigan Lake Michigan Shore, Missouri Ozark Highlands, Colorado Grand Valley, Arizona Sonoita/Willcox). Generate ≥200 rows."),
    ("Australia, New Zealand, South Africa", "AU", "Australia GIs: South Australia (Barossa Valley, Eden Valley, Clare Valley, Watervale, Polish Hill River, Adelaide Hills, Piccadilly Valley, Lenswood, McLaren Vale, Coonawarra, Padthaway, Wrattonbully, Langhorne Creek, Kangaroo Island, Currency Creek, Southern Fleurieu, Mount Benson, Mount Gambier, Robe, Southern Flinders Ranges, Bordertown, Winemaker's Selection). Victoria (Yarra Valley, Mornington Peninsula, Heathcote, Bendigo, Macedon Ranges, Sunbury, Goulburn Valley, Nagambie Lakes, Rutherglen, Beechworth, Alpine Valleys, Glenrowan, King Valley, Grampians, Great Western, Pyrenees, Henty, Port Phillip Zone, North East Victoria). New South Wales (Hunter Valley, Pokolbin, Orange, Mudgee, Riverina, Hilltops, Tumbarumba, Canberra District, Shoalhaven Coast, Southern Highlands, Hastings River). Western Australia (Margaret River, Great Southern, Frankland River, Mount Barker, Porongurup, Albany, Denmark, Pemberton, Geographe, Swan Valley, Peel, Perth Hills). Queensland (Granite Belt, South Burnett). Tasmania (Coal River Valley, Tamar Valley, Huon Valley, Pipers River). New Zealand: Marlborough (Wairau Valley, Awatere Valley, Southern Valleys), Central Otago (Bannockburn, Cromwell Basin, Gibbston, Wanaka, Alexandra, Earnscleugh, Pisa), Hawke's Bay (Gimblett Gravels, Bridge Pa Triangle, Dartmoor Valley), Martinborough/Wairarapa, Nelson (Waimea Plains, Moutere Hills), Waipara/North Canterbury, Gisborne, Auckland (Matakana, Kumeu, Henderson, Waiheke Island), Canterbury. South Africa: Stellenbosch (Banghoek, Bottelary, Devon Valley, Helderberg, Jonkershoek Valley, Papegaaiberg, Polkadraai Hills, Simonsberg-Stellenbosch, Vlottenburg), Paarl (Franschhoek Valley, Voor-Paardeberg, Agter-Paarl), Swartland (Paardeberg, Malmesbury, Riebeekberg, Riebeek Valley), Constantia, Cape South Coast (Walker Bay, Elgin, Bot River, Hemel-en-Aarde Ridge, Hemel-en-Aarde Valley, Upper Hemel-en-Aarde Valley, Elim, Stanford Foothills), Robertson, Breedekloof, Worcester, Tulbagh, Durbanville, Darling, Groenekloof, Philadelphia. Generate ≥180 rows."),
    ("Argentina, Chile, Portugal, Greece, Hungary, Rest of World", "AR", "Argentina: Mendoza (Luján de Cuyo, Maipú, Valle de Uco with Tupungato, Tunuyán, San Carlos; Agrelo, Perdriel, Vistalba, Las Compuertas, Cruz de Piedra, Barrancas, Rivadavia, Chacras de Coria, Medrano), Salta (Cafayate, Molinos, San Carlos, La Poma, Cachi), Jujuy, Catamarca, La Rioja Argentina, San Juan (Zonda Valley, Pedernal Valley, Ullum Valley), Río Negro (Alto Valle del Río Negro), Neuquén (Patagonia Norte, Confluencia, Añelo). Chile: Atacama (Copiapó Valley, Huasco Valley), Coquimbo (Elqui Valley, Limarí Valley, Choapa Valley), Aconcagua Valley, Casablanca Valley, San Antonio Valley, Leyda Valley, Marga-Marga, Maipo Valley (Alto Maipo, Isla de Maipo, Buin, Puente Alto, Pirque), Cachapoal Valley, Colchagua Valley (Apalta, Los Lingues, Marchigüe, Peralillo, Pumanque), Curicó Valley (Lontué Valley, Teno Valley), Maule Valley (Claro Valley, Loncomilla Valley, Tutuvén Valley), Biobío Valley, Itata Valley, Malleco Valley, Patagonia. Portugal: Douro (Baixo Corgo, Cima Corgo, Douro Superior, Porto/Port wine), Dão, Bairrada, Vinho Verde (Monção e Melgaço, Lima, Braga, Cávado, Ave, Sousa, Baião, Amarante, Paiva), Alentejo (Borba, Évora, Granja-Amareleja, Moura, Portalegre, Redondo, Reguengos, Vidigueira), Lisboa, Setúbal (Palmela, Arrábida), Tejo, Algarve, Trás-os-Montes, Beira Interior (Cova da Beira, Castelo Rodrigo, Pinhel), Madeira (Câmara de Lobos, São Vicente, Santana), Açores (Pico, Biscoitos), Távora-Varosa. Greece: Naoussa PDO, Amyndeon PDO, Goumenissa PDO, Côtes de Meliton PDO, Santorini PDO, Nemea PDO, Patras PDO, Muscat of Patras PDO, Muscat of Kefalonia PDO, Muscat of Samos PDO, Cephalonia PDO, Mantinia PDO, Monemvasia-Malvazia PDO, Rapsani PDO, Metsovo, Attica, Crete (Peza, Archanes, Dafnes, Sitia), Lefkada, Limnos, Rhodes. Hungary: Tokaj-Hegyalja (Tokaj, Tarcal, Mád, Bodrogkeresztúr, Erdőbénye, Tolcsva, Olaszliszka, Sárospatak), Eger (Egri Bikavér), Villány (Villányi Franc, Villányi Cabernet), Szekszárd, Sopron, Badacsony, Balaton-Felvidék, Somló, Neszmély, Etyek-Buda. Rest of World: Lebanon (Bekaa Valley, Zahlé, Baalbek, Chtaura), Israel (Galilee, Golan Heights, Judean Hills, Negev), Georgia (Kakheti, Kartli, Imereti, Racha-Lechkhumi, Kakheti subzones: Telavi, Kvareli, Gurjaani, Sighnaghi), Switzerland (Valais, Vaud-La Côte, Vaud-Lavaux, Neuchâtel, Genève, Graubünden/Grisons), England (Sussex, Kent, Hampshire, Essex), Croatia (Pelješac, Hvar, Korčula, Brač, Istria/Istra, Slavonia, Plešivica), Slovenia (Primorska, Vipava Valley, Kras, Brda, Štajerska, Posavje), Romania (Dealu Mare, Murfatlar, Cotnari, Recaș, Tîrnave), Bulgaria (Thracian Valley, Danubian Plain, Black Sea Region, Struma Valley), Japan (Hokkaido, Yamagata, Nagano, Yamanashi), Canada (Niagara Peninsula, Okanagan Valley, Similkameen Valley, Vancouver Island, Annapolis Valley Nova Scotia). Generate ≥150 rows."),
]


# ---------------------------------------------------------------------------
# Grape batch definitions (2 batches → ≥400 rows total)
# ---------------------------------------------------------------------------

GRAPE_BATCHES = [
    ("200+ red grape varieties", "Cabernet Sauvignon (CS, cab sauv), Merlot, Pinot Noir (PN), Syrah (Shiraz), Nebbiolo, Sangiovese, Tempranillo (Tinto Fino, Tinta del País, Aragonés, Cencibel, Ull de Llebre), Grenache Noir (Garnacha, Cannonau, Alicante), Barbera, Dolcetto, Mourvèdre (Monastrell, Mataro), Zinfandel (Primitivo), Malbec (Côt, Auxerrois, Pressac), Carménère, Touriga Nacional, Touriga Franca, Tinta Roriz (Aragonez, Tempranillo IT), Alicante Bouschet, Trincadeira (Tinta Amarela), Tinta Barroca, Sousão (Vinhão), Bastardo (Trousseau), Castelão (Periquita), Baga, Nero d'Avola, Nerello Mascalese, Nerello Cappuccio, Gaglioppo, Aglianico, Negramaro, Nero di Troia (Uva di Troia), Lagrein, Schiava (Vernatsch, Trollinger), Teroldego, Marzemino, Pignolo, Refosco dal Peduncolo Rosso, Raboso, Corvina Veronese (Corvina), Corvinone, Rondinella, Molinara, Sagrantino, Montepulciano, Canaiolo, Colorino, Ciliegiolo, Cesanese, Monica, Carignano (Carignan, Mazuelo, Cariñena), Cinsaut (Cinsault, Ottavianello), Frappato, Nero Buono di Cori, Lacrima di Morro d'Alba, Rosso Conero, Vernaccia Nera, Vernaccia di Serrapetrona, Freisa, Ruché, Grignolino, Pelaverga, Malvasia Nera, Piedirosso (Per'e Palummo), Casavecchia, Tintilia, Pallagrello Nero, Bombino Nero, Susumaniello, Primitivo, Nero d'Avola. Also international/regional varieties: Blaufränkisch (Lemberger, Kékfrankos, Frankovka), Zweigelt (Rotburger), St. Laurent, Blauburger, Pinotage, Counoise, Vaccarèse, Muscardin, Terret Noir, Piquepoul Noir (Picpoul Noir), Morrastel (Graciano, Cariñena tinto), Mencía (Jaen Portugal), Garnacha Tintorera (Alicante Bouschet ES), Juan García, Prieto Picudo, Rufete, Bobal (Requena), Mandó, Forcallà, Sumoll, Garró, Feteasca Neagra, Kadarka (Cadarcă), Portugieser (Blauer Portugieser), Dornfelder, Spätburgunder, Meunier (Pinot Meunier), César, Gamay Noir (Gamay), Mondeuse, Persan, Poulsard (Ploussard), Trousseau, Pineau d'Aunis, Grolleau, Cabernet Franc (Bouchet, Breton, Carmenet), Petit Verdot, Marselan, Tannat, Fer Servadou (Mansois, Braucol), Négrette, Duras, Prunelard, Abouriou, Xinomavro, Agiorgitiko (Nemea), Mavrodaphne, Limnio, Mavrotragano, Kotsifali, Mandilari, Liatiko, Moschato Mavro, Saperavi, Aleksandrouli, Otskhanuri Sapere. Total ≥200 distinct red varieties."),
    ("200+ white, rosé, and orange grape varieties", "Chardonnay, Sauvignon Blanc (Fumé Blanc), Riesling, Pinot Gris (Pinot Grigio, Grauburgunder, Malvoisie), Gewürztraminer (Traminer, Roter Traminer), Viognier, Albariño (Alvarinho), Verdejo, Vermentino (Rolle, Pigato), Grüner Veltliner, Muscat Blanc à Petits Grains (Moscato Bianco, Muscat de Frontignan, Muscat d'Alsace), Muscat of Alexandria (Zibibbo, Moscatel de Alejandría), Moscato Giallo (Goldmuskateller), Torrontés Riojano, Chenin Blanc (Steen, Pineau de la Loire, Vouvray grape), Sémillon, Roussanne, Marsanne, Clairette Blanche, Bourboulenc, Picpoul Blanc (Piquepoul Blanc), Grenache Blanc (Garnacha Blanca), Macabeo (Macabeu, Viura), Xarel·lo (Xarello, Pansa Blanca), Parellada, Airén (Lairén, Manchego), Palomino Fino (Listán Blanco), Pedro Ximénez (PX), Verdelho, Arinto (Pedernã), Loureiro, Trajadura (Treixadura), Alvarelhão Branco, Viosinho, Codega do Larinho, Rabigato, Roupeiro (Síria), Antão Vaz, Fernão Pires (Maria Gomes), Bical, Encruzado, Cerceal Branco, Sercial (Esgana Cão), Bual (Boal), Terrantez, Malvasia Fina (Arinto do Douro), Malvasia Rei, Malvasia Candida, Malvasia delle Lipari, Fiano di Avellino, Greco di Tufo (Greco), Coda di Volpe Bianca, Falanghina, Biancolella, Forastera, Pallagrello Bianco, Asprinio di Aversa, Fiano Minutolo, Verdicchio, Pecorino (Trebbiano d'Abruzzo Pecorino), Passerina, Trebbiano Toscano, Trebbiano d'Abruzzo, Bombino Bianco, Turbiana (Trebbiano di Lugana), Friulano (Tocai Friulano, Sauvignonasse), Ribolla Gialla, Malvasia Istriana, Verduzzo Friulano, Picolit, Vitovska, Glera (Prosecco grape), Garganega, Trebbiano di Soave, Catarratto Bianco, Grecanico Dorato, Carricante, Damaschino, Nerello Mascalese Bianco (some white expressions), Nuragus, Nasco, Vermentino di Sardegna. Also: Savagnin (Traminer Naturé, Heida), Kerner, Müller-Thurgau (Rivaner), Silvaner (Sylvaner, Johannisberg), Elbling, Bacchus, Ortega, Scheurebe (Dr. Wagner's Riesling x Silvaner), Rieslaner, Huxelrebe, Faber, Optima, Siegerrebe, Ehrenfelser, Pinot Blanc (Weißburgunder, Klevner, Clevner), Auxerrois Blanc, Chasselas (Gutedel, Fendant, Pendant), Welschriesling (Riesling Italico, Olaszrizling), Furmint, Hárslevelű (Lindenblättriger), Kabar, Kövérszőlő, Zéta (Oremus), Juhfark, Sárga Muskotály, Dimiat (Dimyat), Rkatsiteli, Mtsvane Kakhuri, Chinuri, Goruli Mtsvane, Khikhvi, Kisi, Tsolikouri, Tsitska, Krakhuna. Also Assyrtiko, Moschofilero (Filleri), Malagouzia, Robola, Lagorthi, Debina, Vilana, Dafni, Plyto, Vidiano, Thrapsathiri, Savvatiano (Savatiano), Romeiko, Sultaniye, Athiri, Malagousia, Gewurtztraminer. Rosé/Orange: Pinot Gris (orange style), Ribolla Gialla orange, Ramato (Pinot Grigio Ramato), Gewürztraminer gris, Grenache Gris, Pinot Gris rosé, Schiava Grigia, Malvasia di Candia. Total ≥200 distinct white/rosé/orange varieties."),
]


# ---------------------------------------------------------------------------
# Main generation function
# ---------------------------------------------------------------------------

def generate_with_api(client, model: str) -> dict:
    """Run all API generation batches. Returns dict of table → [sql_lines]."""
    results = {
        "wine_regions": [],
        "grape_varieties": [],
        "appellation_rules": [],
        "vintage_rules": [],
    }

    print("\n=== Generating wine_regions ===", flush=True)
    for i, (label, cc, desc) in enumerate(REGION_BATCHES, 1):
        print(f"  Batch {i}/{len(REGION_BATCHES)}: {label}...", end=" ", flush=True)
        prompt = REGION_PROMPT.format(description=f"{label} wine regions: {desc}")
        try:
            raw = call_claude(client, model, prompt, max_tokens=8192)
            rows = extract_inserts(raw, "wine_regions")
            results["wine_regions"].extend(rows)
            print(f"{len(rows)} rows", flush=True)
        except Exception as e:
            print(f"ERROR: {e}", flush=True)
        time.sleep(1)

    print("\n=== Generating grape_varieties ===", flush=True)
    for i, (label, color, desc) in enumerate(GRAPE_BATCHES, 1):
        print(f"  Batch {i}/{len(GRAPE_BATCHES)}: {label}...", end=" ", flush=True)
        prompt = GRAPE_PROMPT.format(description=f"{label}: {desc}")
        try:
            raw = call_claude(client, model, prompt, max_tokens=8192)
            rows = extract_inserts(raw, "grape_varieties")
            results["grape_varieties"].extend(rows)
            print(f"{len(rows)} rows", flush=True)
        except Exception as e:
            print(f"ERROR: {e}", flush=True)
        time.sleep(1)

    print("\n=== Generating appellation_rules ===", flush=True)
    try:
        raw = call_claude(client, model, APPELLATION_PROMPT, max_tokens=8192)
        rows = extract_inserts(raw, "appellation_rules")
        results["appellation_rules"].extend(rows)
        print(f"  {len(rows)} rows", flush=True)
    except Exception as e:
        print(f"  ERROR: {e}", flush=True)
    time.sleep(1)

    print("\n=== Generating vintage_rules ===", flush=True)
    try:
        raw = call_claude(client, model, VINTAGE_PROMPT, max_tokens=4096)
        rows = extract_inserts(raw, "vintage_rules")
        results["vintage_rules"].extend(rows)
        print(f"  {len(rows)} rows", flush=True)
    except Exception as e:
        print(f"  ERROR: {e}", flush=True)

    return results


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate wine ontology seed SQL files")
    parser.add_argument("--fallback", action="store_true",
                        help="Skip API calls; use embedded fallback data only")
    parser.add_argument("--table", choices=["wine_regions", "grape_varieties",
                                             "appellation_rules", "vintage_rules"],
                        help="Regenerate only a specific table")
    args = parser.parse_args()

    print("=== Wine Ontology Seed Generator ===", flush=True)
    print(f"Output directory: {SEED_DIR.resolve()}", flush=True)

    if args.fallback:
        print("  --fallback mode: skipping API calls", flush=True)
        results = {}
    else:
        api_key = get_api_key()
        if not api_key:
            print("ERROR: Set ANTHROPIC_API_KEY or CLAUDE_API_KEY environment variable",
                  file=sys.stderr)
            sys.exit(1)

        try:
            import anthropic
            client = anthropic.Anthropic(api_key=api_key)
        except ImportError:
            print("ERROR: pip install anthropic", file=sys.stderr)
            sys.exit(1)

        model = detect_model(client)
        if not model:
            print("ERROR: No Claude Opus model available. "
                  "Run with --fallback or check API key.", file=sys.stderr)
            sys.exit(1)

        print(f"Using model: {model}", flush=True)
        results = generate_with_api(client, model)

    # Write seed files
    print("\n=== Writing seed files ===", flush=True)

    # wine_regions
    regions_lines = results.get("wine_regions", [])
    if regions_lines:
        n = write_seed_file(
            "09_wine_regions_seed.sql",
            "Phase 9: wine_regions seed data (≥2000 rows, all major wine-producing regions)",
            regions_lines,
        )
        print(f"  wine_regions:      {n} rows", flush=True)

    # grape_varieties
    grapes_lines = results.get("grape_varieties", [])
    if grapes_lines:
        n = write_seed_file(
            "09_grape_varieties_seed.sql",
            "Phase 9: grape_varieties seed data (≥400 rows with aliases)",
            grapes_lines,
        )
        print(f"  grape_varieties:   {n} rows", flush=True)

    # appellation_rules
    appellation_lines = results.get("appellation_rules", [])
    if appellation_lines:
        n = write_seed_file(
            "09_appellation_rules_seed.sql",
            "Phase 9: appellation_rules seed data (≥100 rows)",
            appellation_lines,
        )
        print(f"  appellation_rules: {n} rows", flush=True)

    # vintage_rules
    vintage_lines = results.get("vintage_rules", [])
    if vintage_lines:
        n = write_seed_file(
            "09_vintage_rules_seed.sql",
            "Phase 9: vintage_rules seed data (≥20 rows with release delays)",
            vintage_lines,
        )
        print(f"  vintage_rules:     {n} rows", flush=True)

    # Final validation
    print("\n=== Validating row counts ===", flush=True)
    wine_regions_count = len(results.get("wine_regions", []))
    grape_varieties_count = len(results.get("grape_varieties", []))
    appellation_rules_count = len(results.get("appellation_rules", []))
    vintage_rules_count = len(results.get("vintage_rules", []))

    print(f"  wine_regions:      {wine_regions_count}", flush=True)
    print(f"  grape_varieties:   {grape_varieties_count}", flush=True)
    print(f"  appellation_rules: {appellation_rules_count}", flush=True)
    print(f"  vintage_rules:     {vintage_rules_count}", flush=True)

    if not args.fallback:
        assert wine_regions_count >= 2000, \
            f"Expected >=2000 wine_regions, got {wine_regions_count}. " \
            "Run script again or use --fallback."
        assert grape_varieties_count >= 400, \
            f"Expected >=400 grape_varieties, got {grape_varieties_count}."
        assert appellation_rules_count >= 100, \
            f"Expected >=100 appellation_rules, got {appellation_rules_count}."

    print("\nDone.", flush=True)


if __name__ == "__main__":
    main()
