-- ADR 0222 (Proposed, 2026-09-25): passkey enrolment on /profile.
--
-- The founder's pick, 2026-09-21, round 6r, verbatim: "Passkey + paste
-- (Recommended)" -- ADR 0134 §7's SC 3.3.8 bullet. As recorded there: WebAuthn;
-- per user (never per house, never per device); owner and manager only; a peer
-- path beside the manager passcode, neither replacing the other; enrolment and
-- revocation on /profile; audited.
--
-- Why the gateway keeps these rows rather than Supabase Auth: this product does
-- not sign people in through Supabase Auth. The gateway checks bcrypt hashes on
-- public.users and signs its own JWT (auth.service.ts generateTokens), and
-- auth.users and public.users are disjoint. A Supabase-native WebAuthn factor
-- would hang off an identity nobody signs in with.
--
-- Two tables, both additive and idempotent, both written only by the gateway
-- (service_role); no client role can read or write either:
--   1. user_passkeys -- one row per enrolled credential. A revoked credential
--      keeps its row with revoked_at set: a credential that once existed must
--      not become indistinguishable from one that never did, and its id can
--      never be enrolled again.
--   2. webauthn_challenges -- one row per ceremony in flight. A challenge is
--      consumed once (the gateway deletes it as it reads it) and expires after
--      five minutes, so a captured response cannot be replayed.

-- 1. The credentials ----------------------------------------------------------
create table if not exists public.user_passkeys (
  id uuid primary key default gen_random_uuid(),
  -- public.users.user_id, from the signed token. Never an auth.users id.
  user_id uuid not null references public.users(user_id) on delete cascade,
  -- The authenticator's credential id, base64url. Unique across every user:
  -- one authenticator credential belongs to one account.
  credential_id text not null,
  -- The COSE public key, base64url. Public by definition, never a secret.
  public_key text not null,
  -- The authenticator's signature counter. 0 for most synced passkeys.
  sign_count bigint not null default 0 check (sign_count >= 0),
  transports text[] not null default '{}',
  -- 'singleDevice' | 'multiDevice' (a synced passkey), as the authenticator said.
  device_type text not null check (device_type in ('singleDevice', 'multiDevice')),
  backed_up boolean not null default false,
  -- The authenticator model id; all zeros when the authenticator does not say.
  aaguid text,
  -- The relying party the credential is bound to (mudavym.com in production).
  rp_id text not null,
  -- A name the person chose ("Work laptop"); null when they gave none.
  nickname text check (nickname is null or char_length(nickname) between 1 and 60),
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz,
  revoked_by uuid references public.users(user_id) on delete set null
);
create unique index if not exists user_passkeys_credential_id_key
  on public.user_passkeys (credential_id);
create index if not exists user_passkeys_user_live_idx
  on public.user_passkeys (user_id) where revoked_at is null;
alter table public.user_passkeys enable row level security;
revoke all on public.user_passkeys from public, anon, authenticated;
grant select, insert, update, delete on public.user_passkeys to service_role;
drop policy if exists user_passkeys_service_only on public.user_passkeys;
create policy user_passkeys_service_only on public.user_passkeys
  for all to service_role using (true) with check (true);
comment on table public.user_passkeys is
  'ADR 0222 (Proposed) / ADR 0134 §7 (founder 2026-09-21: "Passkey + paste (Recommended)"): WebAuthn passkeys, one row per credential, per user. Enrolled and revoked on /profile by anyone in the house (staff too: ADR 0229, founder 2026-09-26 round 6); every enrolment and revocation files a system_audit_log row (passkey_enrolled / passkey_revoked). A revoked row is kept with revoked_at set; a password reset revokes every live row (revoked_by = the account, audit reason password_reset).';

-- 2. Ceremonies in flight -----------------------------------------------------
create table if not exists public.webauthn_challenges (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  purpose text not null check (purpose in ('registration', 'authentication')),
  -- base64url, generated by the gateway.
  challenge text not null,
  rp_id text not null,
  -- The exact origin the ceremony was started from; the response must match it.
  origin text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists webauthn_challenges_expiry_idx
  on public.webauthn_challenges (expires_at);
alter table public.webauthn_challenges enable row level security;
revoke all on public.webauthn_challenges from public, anon, authenticated;
grant select, insert, update, delete on public.webauthn_challenges to service_role;
drop policy if exists webauthn_challenges_service_only on public.webauthn_challenges;
create policy webauthn_challenges_service_only on public.webauthn_challenges
  for all to service_role using (true) with check (true);
comment on table public.webauthn_challenges is
  'ADR 0222 (Proposed): one row per WebAuthn ceremony in flight. The gateway deletes the row as it reads it (single use) and refuses one past expires_at (five minutes). Expired rows are swept by the gateway when a new ceremony starts.';
